### ISSUE TITLE
Missing `focusedmon` event in `socket2`

### ISSUE THREAD

**Issue by JustSimplyKyle** [hyprwm/Hyprland#1036]
When you have these in config
![image](https://user-images.githubusercontent.com/68589851/202496449-4632aa5d-4367-4718-a077-bad89d70c434.png)
And you focus to workspace 10, and then you use dispatcher `workspace 2` to move to workspace 2, your focus moves to workspace two, as expectantly.

But the event `focusedmon>>DP,3,2` isn't here! Which I think it *should* be here? 
![image](https://user-images.githubusercontent.com/68589851/202497402-ea3e51ac-71c6-4407-82cb-3b0ac718fd21.png)

**Comment by vaxerski** [comment]
fixed in 5d39223239d86479ffd9639661c92006f8ba6489

**Comment by JustSimplyKyle** [comment]
It's... not fixed?(latest commit)
![image](https://user-images.githubusercontent.com/68589851/202718612-d221afdb-921f-4673-9e30-67383c08d800.png)

**Comment by vaxerski** [comment]
huh odd

**Comment by vaxerski** [comment]
should be fixed in e427d9f622d852c20d0f24966dbe35a34f600de4

**Comment by JustSimplyKyle** [comment]
Can confirm that this is in fact fixed!
