### ISSUE TITLE
Some windows disapear when an app goes fullscreen

### ISSUE THREAD

**Issue by DiedByDisgust** [hyprwm/Hyprland#1047]
Steps to reproduce:
put some windows in a workspace then execute an app or game (world of warcraft running on wine in my case) . in fullscreen mode.

Noted outcome:
when you close app/game or move it to a different workspace the prior mentioned windows go hidden or something. hyprctl clients still shows them in the same workspace

Expected outcome:
Not get disappeared i guess

**Comment by DiedByDisgust** [comment]
under latest release v0.18.0beta
Hyprland, built from branch main at commit c02bfc3897137439596df4670cef2441d24c8367dirty (fix extents in shadow deco).

**Comment by vaxerski** [comment]
not able to repro. Any app that isnt a 20GB game?

**Comment by DiedByDisgust** [comment]
Yes, also happen with LibreOffice Writer. but isn't the exactly same behavior.

**Comment by vaxerski** [comment]
I have NEVER seen that with LO - how to repro?

**Comment by diced** [comment]
I had the same issue, it happened only when the full screen game opened on top of all the other windows. In my case I launched Fall Guys, and I had heroic games launcher open on the same workspace and it became invisible after I moved Fall Guys to another workspace.

**Comment by Sincide** [comment]
Having the same issue when launching Dying Light 2 via steam

**Comment by vaxerski** [comment]
fixed in be03a6186c22f915d3d92df71d2e74c64e816245

**Comment by Sincide** [comment]
Hi, I still have this issue, some games reappear when fiddling with the fullscreen to not fullscreen, but not Dying Light 2, it just dissapears and you hear the music in the background.

Version:
Hyprland, built from branch main at commit be03a6186c22f915d3d92df71d2e74c64e816245dirty (fix invisible windows on moving fullscreen out).

**Comment by vaxerski** [comment]
This issue is about the tiled windows going invisible, not the fullscreen one. Open another issue for that.

**Comment by felixsanz** [comment]
@vaxerski can you re-open it? it's still happening. i'm new to hyprland and this is happening to me all the time :/

**Comment by vaxerski** [comment]
I need a reproducible example on something that aint a game

**Comment by felixsanz** [comment]
> 

im not opening a game. all I was doing is opening some wezterm terminals and firefox. I dont know how to reproduce it, all i was doing is playing with floating windows, opening and closing them, moving to another workspace, etc. and after a few moments im experiencing glitches and bugs like windows dissapearing but process still alive. some firefox windows dissapear and i have to restart the whole browser to get them back

**Comment by vaxerski** [comment]
define disappear. are they closing or just becoming invisible?

**Comment by felixsanz** [comment]
> define disappear. are they closing or just becoming invisible?

they dissapear visually. the process is still alive but no way to recover the window. it's nowhere.

**Comment by vaxerski** [comment]
I assume this means "close", as in you can't interact with it because it's gone, and not that it's still on the workspace, just fully transparent.

**Comment by felixsanz** [comment]
agree.

to be clear, for example with firefox... it says that the window (with its tabs) is open. But can't see that window anywhere, in any workspace.

The window doens't ocupy any workspace space (ie: it's NOT transparent ocuppying space, it's just like it doesn't exist).

I know it's not closed because firefox keeps saying that I have 2 windows opened with 40 tabs in them, even if one window dissapeared. It's still eating ram, playing sound if its a youtube video, etc.

But the window is nowhere and there is no way to recover it visually!

**Comment by vaxerski** [comment]
that seems like a problem with your system and is not relevant to this issue then

**Comment by felixsanz** [comment]
> that seems like a problem with your system and is not relevant to this issue then

why it doesn't happen on sway or river then? i want to use hyprland but can't because of that, it's a critical bug. it happens after just a few minutes and actions, every single time. now i'm on sway for days and never experienced that

**Comment by vaxerski** [comment]
I've got no clue, but a window closing means either you or the app requested for it to be as such.

This issue is about a completely different bug, if you want to get help with yours, open a separate one.

**Comment by felixsanz** [comment]
It's happening on firefox windows, on foot terminals, on thunar instances... are you sure it's not a bug?

**Comment by vaxerski** [comment]
> and again, it's not "window closing". the window doesn't close, it just dissapears.

a window can close without the app itself shutting down.

it probably is a bug, just not this one.

>  or reproduce it

well it either happens or not. It would help, and having it in a separate thread would make it easier.

**Comment by vaxerski** [comment]
so @felixsanz can you open a separate issue, and while you're at it, check if 0.18.0beta has the same problem?

**Comment by felixsanz** [comment]
> so @felixsanz can you open a separate issue, and while you're at it, check if 0.18.0beta has the same problem?

yes give me a few hours please, i'm trying to fix some other issues with nvidia, just in case that's the problem
