### ISSUE TITLE
Weird Lag when dragging floating windows

### ISSUE THREAD

**Issue by System-x64** [hyprwm/Hyprland#1127]
on setting `misc{animate_manual_resizes}` to true, the window gets a weird lag or idk what to call it

https://user-images.githubusercontent.com/90208727/204487118-c616074f-5d5d-4f64-9a72-7112c315d42d.mp4

Is their anyway we could fix it cuz i really love animated resize but i hate this lag thing

**Comment by vaxerski** [comment]
only happens for a few people which does not include me, so I don't know what is the root cause.

**Comment by System-x64** [comment]
nvm

**Comment by ad-on-is** [comment]
Me too, I noticed this happens when I enable animations. Otherwise it's fine.

**Comment by vaxerski** [comment]
can someone share a minimal reproducible config?

**Comment by System-x64** [comment]
[hyprland.txt](https://github.com/hyprwm/Hyprland/files/10129831/hyprland.txt)

**Comment by System-x64** [comment]
> Me too, I noticed this happens when I enable animations. Otherwise it's fine.

Yeah...but turning animations off also removes this resize animation...maybe thats why it works?

**Comment by System-x64** [comment]
it's something to do with `animate_manual_resize` only

**Comment by System-x64** [comment]
@vaxerski I found the possible cause of this issue, while looking through my config file, I noticed I had a separate `windowMove` animation with its own separate bezier curve, I removed the `windowMove` line and Voila! It is working as expected, my guess is that this lag issue only persists when we explicitly set a separate beizier curve for `windowMove`?

**Comment by System-x64** [comment]
Is it possible to set this `windowsMove` thing to only apply to keybinds instead of both key and mouse binds? I suppose this would fix this issue without having to sacrifice my bezier style

**Comment by vaxerski** [comment]
thanks for identifying. I'll look into this.

> Is it possible to set this windowsMove thing to only apply to keybinds instead of both key and mouse binds? I suppose this would fix this issue without having to sacrifice my bezier style

No.

**Comment by System-x64** [comment]
The lag does seem to get better (it's more responsive) but it's not completely gone, the best bet for now is to not put bezier for windowsMove all together

**Comment by System-x64** [comment]
Can you share me your config? @ad-on-is

**Comment by DashieTM** [comment]
@vaxerski sorry for the ping, but I have a likely cause for this, animate manual resizes = true.
At least that setting causes this exact issue on 3 different pcs

**Comment by vaxerski** [comment]
umm thats exactly what the reporter said...
![image](https://user-images.githubusercontent.com/43317083/221711062-203e049d-be2c-4348-af2c-b0aa7eb6083d.png)

it's just that I can't repro it. Been always using it on true and nothing's amiss

**Comment by DashieTM** [comment]
So I tried to build version 14, but I have no idea how to get the compatible wlroots for that.
Either way I remember this starting to happen between version 14 to 16. I can't pinpoint it though sadly.

**Comment by vaxerski** [comment]
> So I tried to build version 14, but I have no idea how to get the compatible wlroots for that.

`git reset --hard <hash> --recurse-submodules && sudo make install`
?

**Comment by DashieTM** [comment]
Ah thanks for the info, personally never used submodules with git, that's why I didn't understand that part, in the meantime I tried your binaries, and the problem starts at version 17.
Tomorrow I might be able to be pinpoint when it started.

**Comment by vaxerski** [comment]
thank you. `git bisect` may come in handy.

**Comment by DashieTM** [comment]
Found it, this commit creates the bug:
https://github.com/hyprwm/Hyprland/commit/8ffd244ef6cca76af51e283355ae048557510349

**Comment by vaxerski** [comment]
well that's anticlimactic. That's the commit that _introduced_ the animations on dragging floating windows.

**Comment by DashieTM** [comment]
I was also extremely surprised, and I still can't figure out why though.
When I move the window extremely slowly it works. But the moment I do it with a normal speed it has these small stops where it freezes.
A brief guess would be a performance issue, but I doubt that an rx6600xt or a gtx 1070 wouldn't be good enough.

**Comment by vaxerski** [comment]
I mean, it could also be your curve.

How it's currently animated is that whenever you move your window by 1 pixel, it restarts the animation.

My guess is that it's not lag, but the animation curve snapping back to the start. 

Can you try with a `linear` curve? it's `0.5,0.5,0.5,0.5`.

**Comment by DashieTM** [comment]
Hmm, it doesn't make much of a difference, I guess there is always going to be a slight "delay" with animations, but it definitely doesn't feel right.
Perhaps polling rate might cause some issues here as well ?

**Comment by DashieTM** [comment]
I added that config flag for now, not necessarily a fix, but this allows users to still get manual resizes without floating window animations.

**Comment by vaxerski** [comment]
you can't really fix it cuz it works as intended...

**Comment by vaxerski** [comment]
I also suppose `misc:vfr = false` doesn't fix this right?

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/10859147/patch.txt)

please check out this patch

**Comment by DashieTM** [comment]
Neither of them made the result much different sadly.

**Comment by vaxerski** [comment]
can you try with the "default" curve?

**Comment by DashieTM** [comment]
I tried different curves, including the default one with different "speeds".

**Comment by vaxerski** [comment]
I still can't repro it, even with configs provided by other people.

I'll be posting patches then and I'd like for everyone affected to try and report the results.

If someone has posted it doesn't work already, no need to affirm them. If someone posted it works though, feel free to double their comment so that I know it's not fixed just for them.

Please test this patch:
[patch.txt](https://github.com/hyprwm/Hyprland/files/10865183/patch.txt)

**Comment by jacekpoz** [comment]
no changes to the bug with this patch

**Comment by vaxerski** [comment]
IIRC @jacekpoz your issue was not the _lag_ but _delay_, which is intended.

**Comment by jacekpoz** [comment]
what do you mean intended it didn't happen before

**Comment by vaxerski** [comment]
`misc:animate_manual_resizes` and `misc:animate_manual_windowdragging` to `false` to get the "old" behavior.

**Comment by jacekpoz** [comment]
whoopsie daisy

**Comment by DashieTM** [comment]
Alright, here some feedback and some questions.

The performance has been improved by a lot on the default curves, but now it definitely does depend on the curve used, some are still extremely bad, which makes sense ofc. Not every curve fits this animation.

Does the performance in the debug version differ much? I have not tested the regular installation yet, only via the debug environment. If so I will retest with the regular version.

And lastly, because of the dependency on a specific curve, I would suggest leaving this behind a config flag, might be enabled by default ofc should that be the idea.

Either way, nice work!

**Comment by vaxerski** [comment]
> And lastly, because of the dependency on a specific curve, I would suggest leaving this behind a config flag, might be enabled by default ofc should that be the idea.

it is.

Patch pushed in 34685a836a40648167848060b48b62788cdcc85f. Lmk how it runs in a real session.

I am only interested in the choppiness. If it's delayed / slow, that's an effect of your `windowsMove` animation setting.

**Comment by GrabbenD** [comment]
> Patch pushed in [34685a8](https://github.com/hyprwm/Hyprland/commit/34685a836a40648167848060b48b62788cdcc85f). Lmk how it runs in a real session.

I tried this commit and here's my observations:
- Moving the window around very slowly is slightly choppy but it's very minor. It feels like something is catching the window or as if the window is moving between "blocks".
- Moving it fast across the screen makes the animation really choppy.
- Moving it as fast as possible from one corner of the screen to another makes the window freeze for a split second and then the window moves really quickly over to the cursor's location (it looks smooth at this point but it's hard to tell since it happens really fast)
- **As soon as I start a screen recording with `wf-recorder` (wl-roots native) ALL choppiness is gone and there's just minor micro stuttering/tearing while moving the window around**

**Comment by GrabbenD** [comment]
> can you see if `debug:damage_tracking=1` fixes the stutter? (tho don't keep it at that setting after testing god-forbid)

This made huge difference!
* Moving the window around slowly is butter smooth.
* Moving it between two points at medium speed (like if you were to demo this feature to your friend) is quite smooth. It's very inconsistent between each attempt (even though I try to move the mouse the same way multiple times between the same points on the screen):
  * Usually it's butter smooth for 2 seconds and then it stutters for a split second, it's like it's catching a hiccup.
  * Sometimes it stutters as soon as I start moving it and then it "shakes it off" and becomes smooth.
  * At times there's absolutely no choppiness while moving the window.
  * Occasionally there's micro stutter.
* Moving it really fast from one corner of the screen to another feels like the window is hitting multiple obstacles along the way and breaking free (clearly choppy but it's not as extreme as before).

**Comment by vaxerski** [comment]
Can you (without the damage_tracking opt changed now, you can remove it) turn on `debug:damage_blink` (warning: epilepsy) and see whether if you move the window quickly the pink highlight follows it correctly?

**Comment by vaxerski** [comment]
reproduced, found the issue. Fix on the way. 10 month old bug. Nice.

**Comment by System-x64** [comment]
Finally 😭

**Comment by vaxerski** [comment]
fixed with 64f35c0e3190f3b56a1c17e81c775966bd0a2251

I was searching in all the wrong places. Murphy's law at its finest.

The source of the issue was invalid bezier calculations for very small $t$ values.

@ sample size 1200:
![image](https://user-images.githubusercontent.com/43317083/222733507-956697b7-0282-458d-8882-865e8f3498d7.png)

This was causing the perceived "hiccups"

**Comment by NextWork123** [comment]
Hello, I tried the latest commit but I'm still experiencing the same issue :/. I have an AMD RX 6600 with Mesa-stable. I also tried setting misc{animate_manual_resizes} to both false and true to test, but the result was the same.


https://user-images.githubusercontent.com/46625863/222792947-3346668e-b70e-4602-a1b5-470fb081e291.mp4

**Comment by vaxerski** [comment]
verify that fact with `hyprctl version`

**Comment by NextWork123** [comment]
@vaxerski done. i think we compiled on that commit [#51ce3dd](https://github.com/hyprwm/Hyprland/commit/51ce3ddd670ca9fb7d359ec8be617354c23ba072)
![immagine](https://user-images.githubusercontent.com/46625863/222811001-54fd0a8a-ed4a-4c76-9883-7be03c459a47.png)

**Comment by vaxerski** [comment]
huh. Can anyone else confirm it's still an issue?

**Comment by GrabbenD** [comment]
> fixed with [64f35c0](https://github.com/hyprwm/Hyprland/commit/64f35c0e3190f3b56a1c17e81c775966bd0a2251)

Most impressive that you managed to find this edge case, well done :)

> huh. Can anyone else confirm it's still an issue?

I tried your fix https://github.com/hyprwm/Hyprland/commit/64f35c0e3190f3b56a1c17e81c775966bd0a2251 and I removed `debug:damage_tracking` from my config. Here's my observations:
- It didn't resolve the original issue.
- If I now disable `misc:animate_mouse_windowdragging` it feels even smoother than before so that's a win.

With OBS and wlrobs plugin I'm able to actually record this issue! Here's a demo (all stuttering/choppiness in the video is what's actually happening on the screen):

https://user-images.githubusercontent.com/45666572/222845057-5a72b845-f8e3-4a7a-95c4-057ee8131256.mp4

---

> Can you (without the damage_tracking opt changed now, you can remove it) turn on debug:damage_blink (warning: epilepsy) and see whether if you move the window quickly the pink highlight follows it correctly?

I jumped a few commits forward to https://github.com/hyprwm/Hyprland/commit/fe007fd36a050103c7953bf5ba68d6ba7187b6e1 and enabled `debug:damage_blink` (while `debug:damage_tracking` is still removed). Had to keep it super short due to file size limit:

https://user-images.githubusercontent.com/45666572/222847399-6ba82262-f984-4489-9c37-9bae18e5214e.mp4

---

Here's my config file, it's mostly default for testing purposes:

<details open>
<summary>hyprland.conf spoiler</summary>

```
# https://wiki.hyprland.org/
autogenerated = 0

# hyprctl monitors
monitor = DP-3, 3840x1600@119.982002, 0x0,1, bitdepth, 10

# Cursor
exec=hyprctl setcursor Bibata-Modern-Classic 32

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
# exec-once = waybar & hyprpaper & firefox & brave & ironbar

# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

### BUG TESTING ###
misc {
    animate_manual_resizes = 1
    animate_mouse_windowdragging = 1
}

debug {
    #damage_tracking = 1
    damage_blink = 1
}
### BUG TESTING ###

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    # Keyboard
    kb_layout = se
    kb_model = pc105

    # Mouse
    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 50
    gaps_out = 50
    border_size = 1
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 5
    blur = yes
    blur_size = 3
    blur_passes = 1
    blur_new_optimizations = on

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = true
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = off
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
device:epic mouse V1 {
    sensitivity = -0.5
}

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more


# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, T, exec, foot
bind = $mainMod, C, killactive, 
bind = $mainMod, M, exit, 
bind = $mainMod, R, exec, dolphin
bind = $mainMod, V, togglefloating, 
bind = $mainMod, B, exec, brave
bind = $mainMod, I, exec, firefox
bind = $mainMod, E, exec, codium
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle
bind = $mainMod, L, exec, wayshot

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
```

</details>

**Comment by vaxerski** [comment]
> If I now disable misc:animate_mouse_windowdragging it feels even smoother than before so that's a win.

placebo, didnt have anything to do with this

> It didn't resolve the original issue.

reeee it did for me and now I can't repro againnnnn

**Comment by vaxerski** [comment]
https://user-images.githubusercontent.com/43317083/222852852-9859e697-1138-45e0-be9f-ea2f934fb14b.mp4

your exact config.

:woe:

**Comment by vaxerski** [comment]
Curves are perfectly fine now (1200 samples)

can't see what's going wrong.

![20230303_23h24m54s_grim](https://user-images.githubusercontent.com/43317083/222853774-08f2de2e-a764-40ef-8e00-62a8f4179a59.png)
![20230303_23h23m46s_grim](https://user-images.githubusercontent.com/43317083/222853778-50326e21-e803-4c27-a019-2045f0c49f3d.png)

**Comment by GrabbenD** [comment]
> placebo, didnt have anything to do with this
My eyes are playing tricks on me after playing around with this for too long 😅 

> reeee it did for me and now I can't repro againnnnn
Flying blind 💀 

I tried various monitor configurations to see if that could be the issue but nope (also, just one monitor is plugged in to DP-3 while trying this):

1. 10 bit + default scaling (0x0,1) with:
- `3840x1600@119.982002` (`hyprctl monitors` recommendation)
- `3840x1600@119`
- `3840x1600@120`

2. default scaling (0x0,1) with:
- `3840x1600@119.982002`
- `3840x1600@119`
- `3840x1600@120`

3. I also tried a different 8bit monitor. Default scaling (0x0,1):
- `1920x1080@60`

**Comment by GrabbenD** [comment]
Also confirmed that this doesn't fix the issue either:
```
misc {
    vfr = 0
}
```

**Comment by vaxerski** [comment]
> Flying blind :skull:

wat

> I tried various monitor configurations to see if that could be the issue but nope

turn on the debug overlay and check the `var` on animation ticking - if it's not higher than your avg frametime, it should be fine.

curves we know are fine

you say DT on monitor solves the issue partially - frame scheduling is off? but then vfr should fix that

that leaves damage tracking to be the culprit, but if that was the case we'd see "tearing"-ish artifacts and furthermore that should then affect more than just resizing manually but all animations. Besides, it should be reproducible.

wtf.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/10886929/patch.txt)

@GrabbenD try this patch.

**Comment by Estebiu** [comment]
It seems to be gone. The animations still aren't as smooth as they could be, tho.

**Comment by vaxerski** [comment]
Nice. I accidentally committed that patch yesterday. Can someone test if the stuttering still persists?

**Comment by NextWork123** [comment]
i can confirm, is fixed thanks.
