### ISSUE TITLE
swayidle stopped working, compositor doesnt implement protocol

### ISSUE THREAD

**Issue by Hellzbellz123** [hyprwm/Hyprland#2692]
temporary fix: *roll back swayidle too 1.8.0*

started talking about this in discord, figured id open a bug report too
i updated my system sometime in the last month and i finally noticed yesterday that swayidle stopped working, looking through swayidles commits the only change  was dropping KDEs idle protocol in favor of the native wayland protocol

so i did some digging, and if im understanding the Hyprland code properly its using the dropped kde protocol instead of idle_notify-v1

wlroots/types/wlr_idle.c               <---- old kde protocol
wlroots/types/wlr_idle_notify.c   <---- new protocol

wl-roots still has a 8month old pr too drop support for it but
"
We might want to wait a bit for this. In the past we've waited a bit, then removed the protocol from Sway, then waited a bit, then removed the protocol from wlroots. Removing from wlroots impacts all compositors.
That said, this protocol has few clients, so might be able to go faster than usual.
"

**Comment by jbeich** [comment]
See also https://github.com/swaywm/sway/pull/7200

**Comment by vaxerski** [comment]
fixed in f8def68e7e761e33dd51c197ac89194a51fcb60f

**Comment by primalmotion** [comment]
it still does not work for me. I run `swayidle -d -w timeout 5 lockscreen.sh timeout 10 suspend.sh ` and nothing happens

**Comment by primalmotion** [comment]
So with Hyprland 0.27 and latest version of swayidle, it works. But f8def68 broke it for me. I tried cleaning everything, but that does not change anything. It seems the idle message is never received by swayidle, and the timeouts never starts

**Comment by primalmotion** [comment]
new data point: it works when I disconnect my HDMI monitor. After unplugging it, and replugging it, it continues to work

**Comment by beh-10257** [comment]
@primalmotion do you have waybar if you do I guess for some reason enabling the idle inhibitor will actually allow the inhibition instead of stopping it
at least that's my case

**Comment by primalmotion** [comment]
wut? lol let me try

**Comment by primalmotion** [comment]
yeah you're right. So is that a waybar issue or an Hyprland issue? :/

**Comment by vaxerski** [comment]
fexd 459afcc47f7a8fd0b85c4b89645099e2643732b3

**Comment by primalmotion** [comment]
nice! thanks
