### ISSUE TITLE
Odd Artifacts

### ISSUE THREAD

**Issue by exformation** [hyprwm/Hyprland#2812]
### Hyprland Version

23eda1411b2dc990a159b64ad73ac182d12fb4f9

### Bug or Regression?

Bug

### Description

Odd screen artifacts that *seem* to be created by this commit? I don't get the problem on any commits before this. 
https://github.com/hyprwm/Hyprland/commit/23eda1411b2dc990a159b64ad73ac182d12fb4f9

Shown and discussed here (warning loud):
https://discord.com/channels/961691461554950145/961694014615208048/1133481241128222821

My config: 
https://github.com/exformation/nix/blob/main/conf/hyprland.conf

### How to reproduce

Run any version built on the provided commit or later. I'm not sure why it just happens to me unless my config has something weird in it or it's a hardware issue. It didn't used to happen. I think 1-2 weeks ago this didn't happen.

### Crash reports, logs, images, videos

https://discord.com/channels/961691461554950145/961694014615208048/1133481241128222821

**Comment by exformation** [comment]
Oh, never mind it happens before that commit as well, but inconsistently. 
Here's a log file of my latest boot if that's helpful: 
https://gist.github.com/exformation/58b7f731c52b4157bd0814d2bd2a1f18

**Comment by vaxerski** [comment]
update to HEAD. I believe this is fixed.

**Comment by exformation** [comment]
> update to HEAD. I believe this is fixed.

I'm on HEAD right now and still have the problem. My wording is probably confusing. The version I mentioned was the one I thought might've introduced the issue after booting a bunch of different hyprland versions, but it happens so inconsistently that it's been hard for me to pin down. 

`hyprctl version` tells me I'm on a9b8e2159c2813a6951d0b0186fbb7f2f8554d3e.
