### ISSUE TITLE
Wallpaper and window decorations are not rendered when using gestures on a fullscreen window

### ISSUE THREAD

**Issue by alba4k** [hyprwm/Hyprland#2898]
### Hyprland Version

Hyprland, built from branch  at commit b08b72358ad549fd066e5be0fc3aa4c9df367607 dirty ().

### Bug or Regression?

Bug

### Description

When using 1:1 gestures to switch workspaces, the workspace one is switching to has no background nor window decorations until the switch is made.

![immagine](https://github.com/hyprwm/Hyprland/assets/84153269/e6d412f7-b162-451a-b81e-1093f0a6adbe)

I know this is not fully a bug and is a side effect of the current implementation of this, but I'm still opening this issue as I think it deserves at least some attention, since Hyprland "doesn't sacrifice on its looks". Using keyboard shortcuts works just fine

### How to reproduce

Open a window fullscreen
Switch to another workspace using gestures

**Comment by vaxerski** [comment]
that commit is very old and this bug has been fixed a while back

**Comment by alba4k** [comment]
![immagine](https://github.com/hyprwm/Hyprland/assets/84153269/e94633fa-6663-4ad5-8e10-08d24fb9a4fb)

While the wallpaper does show, window decorations still do not

**Comment by alba4k** [comment]
This is not the case anymore. However, it appears to have gotten replaced by https://github.com/hyprwm/Hyprland/issues/3882

**Comment by alba4k** [comment]
Nevermind. It only happens, however, when the starting workspace has a fullscreen window in it

**Comment by alba4k** [comment]
No windows at all are now rendered in `Hyprland, built from branch main at commit e2f18f8c7f95e4094acb94c5a06dc6d75d7fc9c1 dirty (groupbar: more safety around gradient textures).


https://github.com/hyprwm/Hyprland/assets/84153269/d49db627-fc1b-4564-b16c-d23672e580a3

`

**Comment by vaxerski** [comment]
video seems broken to me

**Comment by alba4k** [comment]
https://github.com/hyprwm/Hyprland/assets/84153269/f3f6e351-c1a0-4433-ba85-d6a33a3eb210

**Comment by alba4k** [comment]
no clue

**Comment by alba4k** [comment]
Fixed in `v0.33.1-20-gefdf07e2`

However, https://github.com/hyprwm/Hyprland/issues/4117 is an issue now :P
