### ISSUE TITLE
Nautilus (GTK4 apps) context menus wrong placed and flashing

### ISSUE THREAD

**Issue by tagomaco** [hyprwm/Hyprland#3038]
### Hyprland Version

Hyprland, built from branch main at commit 7713daa86adf7980fd73cae40203ab6deb6be8b8 dirty (compositor: log thrown runtime exceptions). Tag: v0.28.0-71-g7713daa8  flags: (if any) debug

### Bug or Regression?

Bug

### Description

![grafik](https://github.com/hyprwm/Hyprland/assets/80169692/b54218bb-a1ac-4342-9aa9-decdff62f9ad)

Screenshot showing the wrong placed context menu cutting off at the bottom edge with above the flashing context menu not usable. These context menus are correctly positioned and displayed on Sway. 

I have noticed that on Sway, unlike Hyprland there appears this message in case it's relevant: "(org.gnome.Nautilus:231187): Gdk-WARNING **: 20:15:51.861: Compositor doesn't support moving popups, relying on remapping"

### How to reproduce

Have Nautilus installed with version >=43 and Hyprland at any version and right click at the bottom or the right of the window.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/12389201/patch.txt)

can't repro, but try this.

**Comment by tagomaco** [comment]
Issue still persists. I hope I did it right with git apply and copying the Hyprland bin.

**Comment by vaxerski** [comment]
scaling? anything that can help to repro?

**Comment by tagomaco** [comment]
That is very weird. I have tested Hyprland on 3 different PCs and on all I have the same problem with basic config. I have tested this on a variety of pc components and Hyprland settings like AMD GPU, NVIDIA GPU, AMD CPU, INTEL CPU, 2k x 1 scale, 4k x 2 scale, HiDPI patch, XWayland force_zero_scaling, ...

I must confess that there are some duplicates too:

https://github.com/hyprwm/Hyprland/issues/2288
https://github.com/hyprwm/Hyprland/issues/1366
https://github.com/hyprwm/Hyprland/issues/1071 (maybe, I don't know)

**Comment by vaxerski** [comment]
fixed 63b2189ce81f08ca77894f50e3d484902283189a

**Comment by tagomaco** [comment]
I think the flashing got fixed. But the actual context menu is after this commit still wrong placed.

![grafik](https://github.com/hyprwm/Hyprland/assets/80169692/3193e02c-d26c-40d5-99d2-05e9648ffb01)

**Comment by imxyy1soope1** [comment]
same issue, looks like there should be a logic to place popup menus

**Comment by vaxerski** [comment]
there is logic, but both gtk and qt have it bugged :)

**Comment by tagomaco** [comment]
But I think these are not GTK4 apps. For example, gnome-text-editor (gtk4) not gedit (gtk3) has this bug too. It only affects GTK4 context menus. And I wonder why it works on Sway? 
What I have noticed is that the context menu oddly repositions itself after 1 frame. Here is the 1 frame displayed with the right placement. But it is missing the vertical lines. After that frame, it is placed like the image shown in my comment above.

![grafik](https://github.com/hyprwm/Hyprland/assets/80169692/a6a82dc7-7660-41bc-90f8-0c829c6ee6a6)

**Comment by vaxerski** [comment]
> And I wonder why it works on Sway?

sway doesn't support the latest xdg-shell ver, probably making gtk4 fall back to some legacy mechanism which works.

**Comment by tagomaco** [comment]
Then why some can't repro this issue? It would be very bad when many apps converting to GTK4 would all be plagued with this bug. Do you mean that it relies on GTK4, xdg-shell and not Hyprland to fix this issue? Is there nothing that can be done on the Hyprland site to, I don't know, "trigger the legacy mechanisms" for only GTK4 apps in the meantime? I have no experience on this topic...

**Comment by vaxerski** [comment]
from my experience all gtk and qt apps have been doing this for a long while, so nothing new to me here.

**Comment by DashieTM** [comment]
Not sure if this will still be noticed, however nautilus also does show the popup properly in gnome. I know they are behind with the shell as well, however at least for GTK applications they would probably implement everything that is needed.

Also, the popup from dolphin works fine, perhaps GTK wants something specific that it can't get?

**Comment by q234rty** [comment]
> It is not a hyprland issue, as the apps themselves decide where to place popups.

As far as I understand, the compositor should use [xdg_positioner::constraint_adjustment](https://wayland.app/protocols/xdg-shell#xdg_positioner:enum:constraint_adjustment) to adjust the popup's position when the popup would be otherwise out of screen. Hyprland seems to fail to do that on [xdg_popup::reposition](https://wayland.app/protocols/xdg-shell#xdg_popup:request:reposition) events.

**Comment by DashieTM** [comment]
Not sure if that is the correct way to do it, but I added your input into popup.cpp, seems to work and is also what sway does.
Test if you can :)
