### ISSUE TITLE
Mouse cursor jumping to top left corner upon switching workspaces from fullscreen xwayland window

### ISSUE THREAD

**Issue by Fleimi** [hyprwm/Hyprland#3170]
### Hyprland Version

Hyprland, built from branch main at commit 00bee91bbc12c0aeef83090274ce2613ca49d3c0 dirty (internal: workspace rule handling refactor (3116))

### Bug or Regression?

Regression

### Description

Mouse cursor seems to reset to the top left corner after switching workspace from some fullscreen applications.  In my case, the offending application I noticed this with is Final Fantasy XIV. If I make it a floating window, the bug does not appear. Interestingly, having *another* (in my case, Discord) xwayland application fullscreened in another workspace fixes the bug, i.e. the cursor behaves normally.

I don't remember having this problem before, which makes me think it's a regression.

### How to reproduce

1.  Open and fullscreen Final Fantasy XIV in one workspace
2.  Switch to another workspace

### Crash reports, logs, images, videos

[Video available here](https://fleimi.s-ul.eu/EgsUyi9e)

**Comment by Fleimi** [comment]
Thanks, I was on the `hyprland-git` AUR package which I wrongly assumed to be up-to-date. However, updating to `Hyprland, built from branch  at commit 96d555e8e794627bfc561e294e148ab8a9961fcc dirty ().
Tag: v0.29.1` didn't solve the problem.

**Comment by vaxerski** [comment]
That's 2 days old. It was fixed today. You installed the latest _release_, while the fix is in _-git_.

**Comment by MightyPlaza** [comment]
1 - still not up to date
2 - hyprland-git AUR package builds from git main branch, it doesn't update you have to force it to (`yay -S hyprland-git`)
3 - https://github.com/hyprwm/Hyprland/issues/3158

**Comment by vaxerski** [comment]
safe to say this is a dupe.
