### ISSUE TITLE
Pass bind not releasing

### ISSUE THREAD

**Issue by AaronMillward** [hyprwm/Hyprland#3208]
### Hyprland Version

Hyprland, built from branch  at commit 96d555e8e794627bfc561e294e148ab8a9961fcc dirty (). Tag: v0.29.1  flags: (if any)

### Bug or Regression?

Regression

### Description

I use a mouse button as my push to talk key in discord. after upgrading from 0.28 to 0.29.1 it seems like only the initial press of the button is sent to discord, my PTT stays on even after releasing the button. if discord is focused the press and release will work correctly unless the button was pressed outside of discord first in which case it still keeps the PTT active.

Testing with `bind=,mouse:276,pass,^(discord)$` on `Hyprland, built from branch  at commit 9654749244117f7f150c6f2a2ce4dede6e8cbb25 dirty ().  v0.28.0 (if any)` I get this `wev` output when pressing the button
```
[13:      wl_pointer] leave: surface: 3
[13:      wl_pointer] frame
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000000
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000000
```

Then in `Hyprland, built from branch  at commit 96d555e8e794627bfc561e294e148ab8a9961fcc dirty (). Tag: v0.29.1 flags: (if any)` this is the ouput
```
[13:      wl_pointer] leave: surface: 3
[13:      wl_pointer] frame
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000000
```

The same happens when using an actual keyboard key `o` in this case. ``bind=,o,pass,^(discord)$``
0.28
```
[14:     wl_keyboard] leave: serial: 244; surface: 3
[14:     wl_keyboard] enter: serial: 249; surface: 3
                      sym: o            (111), utf8: 'o'
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000000
[11:  wl_data_device] selection: (cleared)
[14:     wl_keyboard] leave: serial: 251; surface: 3
[14:     wl_keyboard] enter: serial: 256; surface: 3
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000000
[11:  wl_data_device] selection: (cleared)
```

0.29.1
```
[14:     wl_keyboard] leave: serial: 224; surface: 3
[14:     wl_keyboard] enter: serial: 229; surface: 3
                      sym: o            (111), utf8: 'o'
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000000
```

### How to reproduce

1. Add the bind `bind=,mouse:276,pass,^(discord)$` to `hyprland.conf`
2. Connect to a discord channel
3. Press the button without discord in focus
4. Observe push to talk remain active after the button is released

**Comment by vaxerski** [comment]
I believe this is fixed in -git, please verify

**Comment by AaronMillward** [comment]
unfortunately not, I'm still getting the same behavior and output in wev using -git

**Comment by AaronMillward** [comment]
Here's a log with the bug occurring.
In the log I...
1. Start the wm
2. Open rofi to start discord
3. Open discord and join a voice channel
4. Open a terminal and bring focus over to it
5. Press the mouse button
6. Quit wm

[hyprland.log](https://github.com/hyprwm/Hyprland/files/12553257/hyprland.log)

**Comment by shadowmax31** [comment]
I did a few tests (on the main branch) and it does the same thing with non-mouse bindings.

`bind =,G,pass,^(discord)$`

It seems to never send a release signal to discord. It basically just spams g forever. I'll try to look into it more later.

**Comment by shadowmax31** [comment]
If I revert this, it starts working again: https://github.com/hyprwm/Hyprland/commit/f242f94

**Comment by Ghosthree3** [comment]
@shadowmax31 after building master, which has merged your patch, I'm still experiencing the same issue. The keybind (push to talk) is stuck down after pressing it over any wayland window but works normally when selecting an xwayland window (expected).

However, there is a twist.
I use LCTRL as my PTT hotkey and my config bind line is
`bind = , Control_L, pass, ^(discord)$`

This is actually not how the docs (https://wiki.hyprland.org/Configuring/Binds/#binding-mods) suggest this should be bound, suggesting it should be as below.
`bind = CTRL, Control_L, pass, ^(discord)$`
However when I do this the key fails to work at all.

So there seems to be two bugs, and perhaps only one related to this issue. Regardless of if the first bind line should even work at all, it's swallowing the release event for a modkey bind despite your patch (I tested your patch with the G key and that actually worked fine, so I believe it to be modkey specific). Also the what I assume to be correct line doesn't work but I'm not sure that has anything to do with this.

**Comment by shadowmax31** [comment]
I am not at my PC right now, but the doc actually suggest to use `bindr` not `bind` could check if this why it's not working?

**Comment by vaxerski** [comment]
seems to be working for me.

`pass` binds ignore the `r` flag so it's better to not have it.

**Comment by vaxerski** [comment]
```
bind = , Control_L, pass, ^(discord)$
```
now works

**Comment by Ghosthree3** [comment]
Sorry to be annoying about this, but it still does not quite work correctly.
The above does work, but only when Control_L is the only key pressed and released at any given time. If I for example press and hold Ctrl and tap T or W to open or close a browser tab, then release Ctrl, the key does not release in the application (push to talk is stuck down in Discord). Tapping Ctrl afterwards then issues a release.

Thank you for your quick work so far and I'm sorry it's taken multiple attempts to fix this.

**Comment by vaxerski** [comment]
should be fixed with a commit I made 15 mins ago

**Comment by Ghosthree3** [comment]
Unfortunately not, I waited to test this until you fixed the mouse never release issue just earlier (since I couldn't properly use the build while it was active.

```
Hyprland, built from branch main at commit dcb909df0466a8b9fe07ea7c420b840e2e910223 dirty (keybinds: track pressed special binds).
Tag: v0.29.1-42-gdcb909df
```

**Comment by vaxerski** [comment]
right. Fixed in d28725c67844c55393b3f78bfccfe065e5a25373

sorz

**Comment by Ghosthree3** [comment]
It is indeed, thanks for the insanely fast fix.
