### ISSUE TITLE
Crazy mouse cursor!

### ISSUE THREAD

**Issue by mshzsh** [hyprwm/Hyprland#3264]
### Hyprland Version

v0.29.1-50-g3859607b

### Bug or Regression?

Bug

### Description

After updating Hyprland to version 0.29, when I play Dota 2, the mouse cursor automatically moves to the top of the screen, and I can't bring it down. I can only move it left and right. Please note that this issue is not related to Steam or Dota 2, as it worked correctly in the previous version of Hyprland.

### How to reproduce

Play Dota2 :D

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/41986782/5385871d-c023-4242-8c73-5902427df8a0

**Comment by tchofy** [comment]
Might've been fixed already on the -git version after all the recent constraint fixes.

**Comment by vaxerski** [comment]
this is the crazy froooooog

https://www.youtube.com/watch?v=k85mRPqvMbE

@tchofy he is on a version after the constraint fixes

**Comment by tchofy** [comment]
Ah, right, second time I get confused by the release tag.
First we had an issue with league, now with dota, I think this is a signal that it's time to stop playing mobas and go outside.

**Comment by mshzsh** [comment]
It was fixed in v0.30

**Comment by melectronics-it** [comment]
> It was fixed in v0.30

No, it´s not fixed. I installed the v0.30 yesterday and the cursor is strange.
