### ISSUE TITLE
Mouse cursor getting detached from where it actually is

### ISSUE THREAD

**Issue by sawb** [hyprwm/Hyprland#3415]
### Hyprland Version

Hyprland, built from branch main at commit 3b657257ecb7628a12a4fe72e733a60f031bfec2 dirty (layout: check for specialworkspace in floating toggle). Tag: v0.30.0-11-g3b657257

### Bug or Regression?

Bug

### Description

Since yesterday, when I am doing anything that causes a floating window (right click, save file, popup message), the windows will stop responding to mouse input. The mouse actions will not work until I either switch workspaces and back, or if I move my mouse over certain elements (text box usually works) and keep clicking it seems to eventually correct itself. 

At one time, I can confirm the mouse was actually interacting with a separate workspace than the one which was on my screen. I had a fullscreen video paused on another workspace, and when I was clicking it was unpausing and pausing that video.

### How to reproduce

Open a right click context menu, or a floating popup window

### Crash reports, logs, images, videos

No logs as there is no crash, but video of the behavior here: In this video, I am constantly clicking after triggering the right click menu, and towards the end you can see the cursor is over the file browser but actually interacting with the web browser window. Once I placed my mouse over the text box at the top of the file browser, it corrects itself.  https://streamable.com/2qllxn

**Comment by sawb** [comment]
I have found that moving my mouse over waybar and then back will restore normal behavior every time.

**Comment by sawb** [comment]
My hyprland updates since it started happening:
2023-09-23T19:11:30-0700] [ALPM] upgraded hyprland-git (0.29.1.r104.1357b660-1 -> 0.30.0.r7.2c4a06eb-1)

[2023-09-24T11:59:53-0700] [ALPM] upgraded hyprland-git (0.30.0.r7.2c4a06eb-1 -> 0.30.0.r8.352ceb11-1)

[2023-09-24T16:37:24-0700] [ALPM] upgraded hyprland-git (0.30.0.r8.352ceb11-1 -> 0.30.0.r11.3b657257-1)

[2023-09-25T14:51:24-0700] [ALPM] upgraded hyprland-git (0.30.0.r11.3b657257-1 -> 0.30.0.r12.ffacd2ef-1)

Looks like it started happening when moving from 0.29 to 0.30. Is there possibly some change here that is conflicting with my config?

**Comment by hakan-demirli** [comment]
Same issue here. In a vertical waybar config scrolling over workspaces sets the focus to the most left/right window. So, you can't scroll more than one workspace before you have to refocus to the waybar.

It started after updating to 0.30.

**Comment by kevb1973** [comment]
I'm having a possibly related issue on 29.1 when using _movecursortocorner_. I have a bind to move the cursor off screen so I can navigate with keyboard without interference. The cursor visually moves, but the program thinks the cursor is still in the same place. Scrolling a webpage with keyboard still has elements popping up even though cursor has been moved. I tried _movecursor_, but it doesn't seem to work at all for me.

**Comment by vaxerski** [comment]
can I get your config?

**Comment by sawb** [comment]
Here is my config: https://gist.github.com/sawb/81e2155dcabfacc810fa332887f59232

**Comment by kevb1973** [comment]
> can I get your config?

Here's mine: https://gist.github.com/kevb1973/97a58e24cb00cf8ef83015bb50e0c294

**Comment by lukejcollins** [comment]
I'm also experiencing this issue. Here is my [config](https://github.com/lukejcollins/nixos-build/blob/main/hyprland-config.nix). 

I can consistently fix it by mousing up to Waybar, then the cursor reattaches to the active window. Switching active windows also does the job.

Opening a right click context window consistently causes the problem.

**Comment by lukejcollins** [comment]
I've reverted back to b662215fad037e41872d5b820a70577752469520 - and I'm not longer experiencing the issue

**Comment by vaxerski** [comment]
#3659 got fixed by 92cf1c23371e35fa352da13305d8489a9e08d540

is that also the case here?

**Comment by sawb** [comment]
> #3659 got fixed by [92cf1c2](https://github.com/hyprwm/Hyprland/commit/92cf1c23371e35fa352da13305d8489a9e08d540)
> 
> is that also the case here?

I just built the latest source and still see this behavior.

Version:
Hyprland, built from branch main at commit 92cf1c23371e35fa352da13305d8489a9e08d540 dirty (input: fix mouse down handling on unset last surface).
Tag: v0.31.0-42-g92cf1c23

**Comment by vaxerski** [comment]
what bout 47256a6ed8fb486fd351834c85235a0672d69abc

**Comment by sawb** [comment]
> what bout [47256a6](https://github.com/hyprwm/Hyprland/commit/47256a6ed8fb486fd351834c85235a0672d69abc)

Yeah, that fixed it, thanks! I'm not able to link the commit to this issue, so please go ahead and reopen and close if you want to add that info.
