### ISSUE TITLE
Window border creates strange artifacts on 2x scaling

### ISSUE THREAD

**Issue by icodeforyou-dot-net** [hyprwm/Hyprland#356]
Running hyprland on 2x scaling produces strange artifacts related to window borders.

System info:
NixOS 22.05, kernel 5.15.52
Macbook Pro Late 2013 Model A1502
Intel Haswell i5-4258U
Intel Iris Graphics 5100

How to reproduce:
Not entirely sure, started playing with hyprland and noticing it after switching settings to 2x scaling

Screenshot shows both displaced window and strange window border artifacts

![Screenshot_2022-07-12-13-50-20_7081](https://user-images.githubusercontent.com/61844926/178484776-c123827d-380c-4868-b876-891de6419f6e.png)

**Comment by vaxerski** [comment]
dupe of #216

**Comment by vaxerski** [comment]
that was fixed a long time ago. Please use the latest HEAD when reporting issues.

**Comment by icodeforyou-dot-net** [comment]
@vaxerski I used your flake-based setup for getting Hyprland. Am I not using the latest?

**Comment by vaxerski** [comment]
1. it's not mine, it's @fufexan's
2. `hyprctl version`

**Comment by icodeforyou-dot-net** [comment]
1. I was obviously referring to you guys as a team. 

2. yes, that is broken as well. But since it is a flake it should just pick up whatever is on github, right? Since I just installed this yesterday, I'd say it is the latest version.

**Comment by vaxerski** [comment]
well that bug you are experiencing is not the border, it's the window shadow, and that was fixed in 9388bb5d5551a2d8affa7e3adea305711029b5cd, 13 days ago.

**Comment by viperML** [comment]
Just check the hyprland rev on your flake.lock

**Comment by icodeforyou-dot-net** [comment]
That sadly did not resolve the issue.

okay, so the flake is trying to build hyprland-0.6.2beta+date=2022-07-12 ... at least that is what it says ... it would be hardly surprising then that the bug is not fixed on my end. @vaxerski 

However my flake.lock now has this @viperML which corresponds to the newest commit I believe.

```json
    "hyprland": {
      "inputs": {
        "nixpkgs": [
          "nixpkgs"
        ],
        "wlroots": "wlroots"
      },
      "locked": {
        "lastModified": 1657628052,
        "narHash": "sha256-KpOcOnuBpopJYCryxMKRNE/PEbpPf8/34GTUDP6wgLc=",
        "owner": "hyprwm",
        "repo": "Hyprland",
        "rev": "b1e3430405850c24035c8c1f70ebea99a707135a",
        "type": "github"
      },
      "original": {
        "owner": "hyprwm",
        "repo": "Hyprland",
        "type": "github"
      }
    },
```

So what is going on here?

**Comment by viperML** [comment]
The version string is broken, but you are pulling b1e3430405850c24035c8c1f70ebea99a707135a commit which is correct
I guess https://github.com/icodeforyou-dot-net/nix-dotfiles are your dotfiles, and you are correctly doing everything from the nix side of things

**Comment by icodeforyou-dot-net** [comment]
@viperML yeah I thought as much. I just found issue #329 of which this here might actually be a dupe. But the setup suggested there to resolve it is exactly what I have been doing already.

**Comment by icodeforyou-dot-net** [comment]
@vaxerski sorry, but "works on my end" is hardly saying anything, right? Unless you have exactly the same system config as I do of course. Please reopen the issue. 

I just checked again, it does not work on my end.

I am not sure what the issue is, but this needs to remain open if we are going to explore it.

**Comment by icodeforyou-dot-net** [comment]
The issue guidelines state "If your bug is one that doesn't crash Hyprland, but feels like invalid behavior, that's all you need to say." Which is what I did. They say nothing about configs in case of non-crashing bugs as far as I can see. Please update the guidelines in accordance to your needs if you want people to post their `hyprland.conf` as well in case Hyprland does not crash.

Here is the part of the config that is not just keybindings:

```
monitor=eDP-1,2560x1600@60,0x0,2
workspace=eDP-1,1

input {
    kb_layout=
    kb_variant=
    kb_model=
    kb_options=
    kb_rules=
    follow_mouse=1    
    natural_scroll=1
	force_no_accel=0
}

general {
    main_mod=SUPER

    sensitivity=3.0
	apply_sens_to_raw=0
	
    gaps_in=5
    gaps_out=10

    border_size=2
    col.active_border=0xFF96CDFB
    col.inactive_border=0xFF313244

    damage_tracking=full 	# leave it on full unless you hate your GPU and want to make it suffer
}

decoration {
    rounding=-1
    multisample_edges=0

    active_opacity=1.0
    inactive_opacity=1.0
    fullscreen_opacity=1.0

    blur=0
    blur_size=3
    blur_passes=1
    blur_ignore_opacity=0

}

animations {
    enabled=1
    animation=windows,1,5,default
    animation=borders,1,10,default
    animation=fadein,1,8,default
    animation=workspaces,1,5,default
}

dwindle {
    pseudotile=0 			# enable pseudotiling on dwindle
}

windowrule=float,foot-float
windowrule=float,yad|nm-connection-editor|pavucontrolk
windowrule=float,xfce-polkit|kvantummanager|qt5ct
windowrule=float,feh|Viewnior|Gpicview|Gimp|MPlayer
windowrule=float,VirtualBox Manager|qemu|Qemu-system-x86_64

windowrule=float,foot-full
windowrule=move 0 0,foot-full
windowrule=size 100% 100%,foot-full

windowrule=float,wlogout
windowrule=move 0 0,wlogout
windowrule=size 100% 100%,wlogout
windowrule=animation slide,wlogout
```

**Comment by vaxerski** [comment]
`rounding=-1`

is that even legal, lol

ontopic:
![image](https://user-images.githubusercontent.com/43317083/178504718-f65575fe-d5a5-49af-8fd8-fe27f61cfc6b.png)

no issues.

**Comment by icodeforyou-dot-net** [comment]
But we already verified that nix has pulled in b1e3430405850c24035c8c1f70ebea99a707135a. I posted the `flake.lock` file above. And @viperML did double-check my nix dotfiles. They follow your *your team's* guidelines for setting up hyprland using flakes. In that case there must be something wrong on your end in the way the flake gets the stuff on GitHub. 

Also I have no idea about your codebase in general, please bare that in mind. I have no idea what `no_vfr=1` even is. How should I?

**Comment by fufexan** [comment]
![image](https://user-images.githubusercontent.com/36706276/178507287-c3a6e887-08e9-48b1-a4f4-038dc4029018.png)

I get the same issue only on chromium and electron with ozone-platform=wayland.

> no, I am literally telling you that you're on an old commit.

it seems to be from 2h ago though.

**Comment by vaxerski** [comment]
> I get the same issue only on chromium and electron with ozone-platform=wayland.

completely different issue

**Comment by vaxerski** [comment]
@fufexan it's the same issue you had on 29th of june here: https://discord.com/channels/961691461554950145/961694033942564915/991630286083330069

**Comment by vaxerski** [comment]
> Also I have no idea about your codebase in general, please bare that in mind. I have no idea what no_vfr=1 even is. How should I?

the point was estabilishing if the option exists, if it doesnt you'll get a red error. It was added today and would verify for sure you're running a recent commit

**Comment by icodeforyou-dot-net** [comment]
I shall try this then :)

**Comment by icodeforyou-dot-net** [comment]
@vaxerski you may be right, I might not be on the latest commit ... which raises the question of why. Nix is showing the latest commit. Any idea @fufexan since the Nix side appears to be more your speciality?

**Comment by fufexan** [comment]
That's the latest, it's fine then.

**Comment by vaxerski** [comment]
not since 23 seconds ago but it doesn't matter for this issue :P

**Comment by icodeforyou-dot-net** [comment]
Ok so the answer is that neither the bug nor the error message related to `no_vfr=1` are gone. So it must be an issue with how nix is pulling in things from GitHub then?

**Comment by fufexan** [comment]
Certainly not. I rebuilt my system with the new commit and it all works fine.

What GPU are you using? Using nvidia might explain it.
Try to build it by cloning the repo and doing manual steps:
1. clone repo
2. `nix develop`
3. `meson build`
4. `ninja -C build`
5. `./build/src/Hyprland`

If that doesn't work, it's surely some driver issue.

**Comment by viperML** [comment]
> Certainly not. I rebuilt my system with the new commit and it all works fine.
> 
> What GPU are you using? Using nvidia might explain it. Try to build it by cloning the repo and doing manual steps:
> 
> 1. clone repo
> 2. `nix develop`
> 3. `meson build`
> 4. `ninja -C build`
> 5. `./build/src/Hyprland`
> 
> If that doesn't work, it's surely some driver issue.

That will use the pinned nixpkgs, which are not theirs.

If this problem is on nix side, I would bet it is because they are using nixos-22.05 instead of nixos-unstable

**Comment by icodeforyou-dot-net** [comment]
> That will use the pinned nixpkgs, which are not theirs.

but that would still allow me to exclude that it is an issue with the old Intel Graphics I guess. I might just try that tomorrow.

**Comment by icodeforyou-dot-net** [comment]
@fufexan

> 1. clone repo
> 2. `nix develop`
> 3. `meson build`
> 4. `ninja -C build`
> 5. `./build/src/Hyprland`

Attempting to run the binary I am now stuck with this.

```
00:00:00.000 [ERROR] [backend/wayland/backend.c:543] Could not connect to remote display: Connection refused
m_sWLRBackend NULL!
```

What might be the cause here? I have `programs.wayland` enabled in my config, Gnome was entirely gone, so was any display manager.

**Comment by viperML** [comment]
> @fufexan
> 
> > 1. clone repo
> > 2. `nix develop`
> > 3. `meson build`
> > 4. `ninja -C build`
> > 5. `./build/src/Hyprland`
> 
> Attempting to run the binary I am now stuck with this.
> 
> ```
> 00:00:00.000 [ERROR] [backend/wayland/backend.c:543] Could not connect to remote display: Connection refused
> m_sWLRBackend NULL!
> ```
> 
> What might be the cause here? I have `programs.wayland` enabled in my config, Gnome was entirely gone, so was any display manager.

Do yo have `services.xserver.enable = true` ? And yeah, it is as stupid as it sounds

**Comment by icodeforyou-dot-net** [comment]
Yes, I do have this, among other things, in my config for this machine now:

```nix
{
  hardware.opengl = {
        enable = true;
        driSupport = true;
        driSupport32Bit = true;
        extraPackages = with pkgs; [ 
              mesa_drivers
              intel-ocl
              beignet ];
  };

  programs.xwayland.enable = true;
  programs.dconf.enable = true;

  services.xserver = {
          enable = true;
          desktopManager.gnome.enable = false;
          layout = "us";
  };

  services.xserver.displayManager.gdm.enable = false;
  services.xserver.displayManager.sddm.enable = false;
  services.xserver.displayManager.lightdm.enable = false;

  environment.systemPackages = [ pkgs.wayland ];

  security.polkit.enable = true;
  fonts.enableDefaultFonts = true;
  xdg.portal.enable = true;
  xdg.portal.extraPortals = [ pkgs.xdg-desktop-portal-wlr ];
}
```

I just tried with all of this, it still does not start, same error. It tells me `wlr_backend_autocreate()` failed. Which makes me really sad. 

Anything else I might be missing?

**Comment by fufexan** [comment]
I don't see the point of installing `wayland` explicitly. Hyprland will install it as its dependency, you won't even know it's there.

Really weird stuff going on.

**Comment by fufexan** [comment]
https://github.com/icodeforyou-dot-net/nix-dotfiles/blob/main/flake.nix#L46 should be `proteus = nixpkgs-unstable.lib.nixosSystem ...` It's that simple.

**Comment by viperML** [comment]
```diff
diff --git a/flake.nix b/flake.nix
index 91a530f..5651c2e 100755
--- a/flake.nix
+++ b/flake.nix
@@ -14,7 +14,7 @@
     hyprland = {
       url = "github:hyprwm/Hyprland";
       # build with your own instance of nixpkgs
-      inputs.nixpkgs.follows = "nixpkgs";
+      inputs.nixpkgs.follows = "nixpkgs-unstable";
     };
   };
 
@@ -29,6 +29,13 @@
         };
       };
 
+      pkgs-unstable = import nixpkgs-unstable {
+        inherit system;
+	      config = { 
+          allowUnfree = true;
+        };
+      };
+
       lib = nixpkgs.lib;
 
       overlay-unstable = final: prev: {
@@ -43,7 +50,7 @@
     {
      nixosConfigurations = {
 
-      proteus = lib.nixosSystem {
+      proteus = nixpkgs-unstable.lib.nixosSystem {
         inherit system;
 	      modules = [ 
           ./hosts/shared_configuration.nix
@@ -53,7 +60,7 @@
           hyprland.nixosModules.default 
           { programs.hyprland = { 
               enable = true;
-              extraPackages = with pkgs; [ 
+              extraPackages = with pkgs-unstable; [ 
                 wofi
                 waybar
                 swaybg
@@ -72,8 +79,8 @@
               ]; 
               };
           }
-          { nix.registry.nixpkgs.flake = nixpkgs; }
-          { nix.nixPath = [ "nixpkgs=${nixpkgs}" ]; }
+          { nix.registry.nixpkgs.flake = nixpkgs-unstable; }
+          { nix.nixPath = [ "nixpkgs=${nixpkgs-unstable}" ]; }
 	      ];
        };
 
```

**Comment by fufexan** [comment]
Yeah what viper posted.

**Comment by icodeforyou-dot-net** [comment]
Thanks a lot guys for the help with the flake!

However, it did not help. What is funny though is that Hyprland still complains about me setting 

```
misc {
   no_vfr=1
}
```

In my config. Which should not happen if I actually had the newest version, right?

**Comment by vaxerski** [comment]
closing due to inactivity.

**Comment by icodeforyou-dot-net** [comment]
@vaxerski strange to close this while I just wrote, literally, "I obviously will be testing it again" once my new laptop is ready. But I think it's ok to leave it like that. If the problem persists I'll open a new one since this whole thing appears to be more related to the nix setup of hyprland than the actual hyprland code.

**Comment by fufexan** [comment]
I don't think it's a Nix issue, as I know quite a few people who use the flake to install Hyprland and it works well. Maybe check whether you're using the package from this repo or from Nixpkgs. People usually complain about the latter. Best way to check is to run `realpath $(which Hyprland)`. If the dir ends in `-0.6.1` you're not using the flake.

**Comment by icodeforyou-dot-net** [comment]
I wasn't try to imply that nix itself is to blame. Rather that it might be a weird effect of my own NixOS setup interacting with the way you suggest to get Hyprland on NixOS. What you are saying with getting the wrong packages somehow in an unintended way makes quite a lot of sense actually, I will give it a try once I find the time. Thanks!
