### ISSUE TITLE
movefocus doesn't work as expected with multiple monitors

### ISSUE THREAD

**Issue by AniAggarwal** [hyprwm/Hyprland#3567]
### Hyprland Version

Hyprland, built from branch master at commit 1b48642fd15c433c53876f1b933dcd46265caf8f  (update v0.30.0). Tag: v0.30.0  flags: (if any)

### Bug or Regression?

Bug

### Description

Suppose you have 2 windows side by side on monitor 1, called A and B. Additionally, monitor 1 is placed on top of monitor 2 with 2 side by side windows B and C.
Monitor 1: | A  B |
Monitor 2: | C D |

When focused on window A on monitor 1, calling `movefocus d` moves the focus to window C as expected.

Monitor 1: |   A   |
Monitor 2: | C D |
However, if you first go into full screen on window A and then call `movefocus d`, this results in cycling through windows A,B rather than moving focus to C or D. 
I would expect moving to C or D.

Related:
Monitor 1: | A  B |
Monitor 2: | C D |
Call `movewindow d` while focused on A. Results in A moving as expected. Same for B.
Monitor 1: |    B    |
Monitor 2: | A C D |

Monitor 1: | A  B |
Monitor 2: | C D |
However, calling `movewindow u` while focused on C does not move it up but instead swaps it with D.
Monitor 1: | A  B |
Monitor 2: | D  C |
I would expect it to move window C up to monitor 1.

And now when we do these same operations while in fullscreen, nothing happens at all:

Monitor 1: |   A   |
Monitor 2: | C D |
Full screen on window A. Call `movewindow d` while focused on A, nothing happens. Same if A is the only window on monitor 1. 
Same deal with the reverse for monitor 2.

### How to reproduce

See above.

**Comment by imxyy1soope1** [comment]
fixed in bb9d0aed5bd11879f5a532e26fc0a91d1a8af714

**Comment by AniAggarwal** [comment]
Thanks for the quick response. This seemed to add some interesting new bugs and didn't fully fix it. Seems to cycle the window up and down on the same monitor.

**Comment by vaxerski** [comment]
that commit is unrelated to this issue

**Comment by ArtemSmaznov** [comment]
I also find this flow very confusing and 100% agree with the author.
Additionally, not sure if related or separate issue, sometimes, but not always, moving a window to a new workspace with `movetoworkspacesilent` focus switches to the other monitor instead of remaining on current empty workspace.

**Comment by ArtemSmaznov** [comment]
Just found that #3738 addresses the fullscreen app situation - I am so setting this to false

**Comment by vaxerski** [comment]
Hello there!

This issue has been closed, as we are moving from issues to discussions. More about this can be found [here](https://wiki.hyprland.org/Contributing-and-Debugging/Issue-Guidelines/) and in #9854.

Firstly, please make sure this issue is still relevant in latest Hyprland. If so, we ask you to open a [discussion](https://github.com/hyprwm/Hyprland/discussions) (please read the discussion guidelines first, in the pinned post)

Thank you for your understanding!
