### ISSUE TITLE
Regression: crash when waking up laptop from suspend

### ISSUE THREAD

**Issue by rszyma** [hyprwm/Hyprland#3637]
### Hyprland Version

Hyprland, built from branch main at commit 59f27e7f570170783ac01fb46a0ff90e14de53e6 dirty (compositor: send preferred scale and transform events to surfaces). Tag: v0.31.0-24-g59f27e7f  flags: (if any)

### Bug or Regression?

Regression

### Description

This is very similar to my previous bug report about this (#3076). The crash was fixed then, but since some time now, I'm again getting crashes while waking up from suspend. My setup is the same as described in #3076 so I won't repeat myself.

One thing I've noticed is that this crash only happens when I have opened vscode or vivaldi (chromium browser) and then suspend and wake up. 

Another bug, maybe related: sometimes when doing suspend and wakeup, all the xwayland apps exit instead of hyprland crashing.

And sometimes it don't crash hyprland nor any apps, so this is not consistently reproductible.

I'll post more info if I find out something that would help nail down the cause.

(I'm not doing bisect because it would be pain in the ass because the commands for building hyprland changed recently + the recent issues with https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/116. Maybe I'll do it later)

### How to reproduce

0. Have a lot of apps opened
1. Suspend
2. Wake up
3. Hyprland crash or all the xwayland programs exit (or crash?)

### Crash reports, logs, images, videos

[hyprlandCrashReport573.txt](https://github.com/hyprwm/Hyprland/files/13064091/hyprlandCrashReport573.txt)

**Comment by memchr** [comment]
What is the output of `bt -full` in gdb?

**Comment by memchr** [comment]
Also, is this easier to reproduce when you have a full screen window open?

```cpp
CHyprDwindleLayout::fullscreenRequestForWindow(CWindow*, eFullscreenMode, bool)
```

**Comment by rszyma** [comment]
> What is the output of `bt -full` in gdb?

Sorry, no idea how to use gdb. Am I supposed to load hyprland process in gdb first?

**Comment by memchr** [comment]
If your OS uses systemd, try `coredumpctl debug`

**Comment by rszyma** [comment]
Unrelated to the conversation with memchr: I tried running vivaldi from terminal to see if there's are any error logs when it's crashing on wakeup and there are some error messages indeed: 
```
[2874:2874:1022/201212.949554:ERROR:wayland_event_watcher.cc(39)] libwayland: wl_display@1: error 0: invalid object 47

[1022/201212.962579:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1022/201212.963015:ERROR:elf_dynamic_array_reader.h(64)] tag not found
zsh: trace trap (core dumped)  vivaldi-stable
```

**Comment by rszyma** [comment]
> What is the output of `bt -full` in gdb?



> If your OS uses systemd, try `coredumpctl debug`

```
(gdb) bt -full
#0  0x0000557a492d69fa in  ()
#1  0x000003b809a8be18 in  ()
#2  0x000003b809a8be20 in  ()
#3  0x000003b809a8be28 in  ()
#4  0xaaaaaaaaaaaaaaaa in  ()
#5  0x000003b802a2dec0 in  ()
#6  0x0000000000000026 in  ()
#7  0x8000000000000030 in  ()
#8  0xaaaaaaaaaaaaaaaa in  ()
#9  0x646e616c72707948 in  ()
#10 0xaaaaaaaaaaaaaa00 in  ()
#11 0x08aaaaaaaaaaaaaa in  ()
#12 0xaaaaaaaaaaaaaaaa in  ()
#13 0xaaaaaaaaaaaaaaaa in  ()
#14 0xaaaaaaaaaaaaaaaa in  ()
#15 0xaaaaaaaaaaaaaaaa in  ()
#16 0xaaaaaaaaaaaaaaaa in  ()
#17 0xaaaaaaaaaaaaaaaa in  ()
#18 0xaaaaaaaaaaaaaaaa in  ()
#19 0xaaaaaaaaaaaaaaaa in  ()
#20 0xaaaaaaaaaaaaaaaa in  ()
#21 0x0000000500000002 in  ()
#22 0x00007ffd535e4380 in  ()
#23 0x0000557a43ecd050 in  ()
#24 0x0000000000000000 in  ()
```

**Comment by memchr** [comment]
You have more recent coredumps. Coredumpctl debug command would only load the last one. Please use `coredumpctl debug Hyprland`

**Comment by rszyma** [comment]
> Also, is this easier to reproduce when you have a full screen window open?

I did some more testing with fullscreen on/off and indeed it makes a difference between crashing Hyprland and crashing only xwayland programs.

1st case (fullscreen):
1. Open alacritty
2. run vscode using `code` comamnd
3. fullscreen vscode (fullscreen with gaps) 
4. `systemctl suspend`
5. wait around 10 seconds (when monitor goes off) (it's necessary to wait, otherwise no crash if wake up too quickly)
6. wake up
7. around 50% of time Hyprland crash (crash report in top comment)

2nd case (no fullscreen):
1. Open alacritty
2. run vscode using `code` comamnd
4. `systemctl suspend`
5. wait around 10 seconds (when monitor goes off) (it's necessary to wait, otherwise no crash if wake up too quickly)
6. wake up
7. around 50% of time all xwayland apps crash, but Hyprland or native wayland apps don't crash.

**Comment by rszyma** [comment]
It's 100% xwayland issue, not just electron. Also getting crashes with xeyes.

**Comment by rszyma** [comment]
> You have more recent coredumps. Coredumpctl debug command would only load the last one. Please use `coredumpctl debug Hyprland`


<details>
<summary>`bt -full` output</summary>

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = <optimized out>
        old_mask = {__val = {3544667369688283184}}
        ret = <optimized out>
#1  0x00007f6d961bf8a3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007f6d9616f668 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#3  0x00007f6d961574b8 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x20, sa_sigaction = 0x20}, sa_mask = {__val = {3834028060872880693, 4122262835138213429, 3690192153011957814, 3978426927277290550, 3546356245318744118, 3834591019416367671, 4122825793681700407, 3690755111555444792, 3978989885820777528, 3546919203862231096, 3835153977959854649, 4123388752225187385, 140731244043264, 140731244043279, 12120026524858770944, 140731244043267}}, sa_flags = 11, sa_restorer = 0x7ffe8bcf6340}
#4  0x000055f8c1536f71 in  ()
#5  0x00007f6d9616f710 in <signal handler called> () at /usr/lib/libc.so.6
#6  0x000055f8c1639406 in CHyprDwindleLayout::fullscreenRequestForWindow(CWindow*, eFullscreenMode, bool) ()
#7  0x000055f8c154f502 in CCompositor::setWindowFullscreen(CWindow*, bool, eFullscreenMode) ()
#8  0x000055f8c15fced9 in Events::listener_unmapWindow(void*, void*) ()
#9  0x000055f8c1626282 in handleWrapped(wl_listener*, void*) ()
#10 0x00007f6d96d3f01e in wl_signal_emit_mutable (signal=<optimized out>, data=0x0) at ../wayland-1.22.0/src/wayland-server.c:2241
        pos = 0x55f8c40513a0
        l = 0x55f8c40513a0
        cursor = {link = {prev = 0x55f8c40513a0, next = 0x7ffe8bcf6590}, notify = 0x7f6d96d3c110 <handle_noop>}
        end = {link = {prev = 0x7ffe8bcf65b0, next = 0x55f8c3fb18e0}, notify = 0x7f6d96d3c110 <handle_noop>}
#11 0x00007f6d96e04b69 in wlr_surface_unmap () at /home/n/gh/Hyprland/subprojects/wlroots/build/libwlroots.so.12032
#12 0x00007f6d96e05802 in surface_handle_role_resource_destroy ()
    at /home/n/gh/Hyprland/subprojects/wlroots/build/libwlroots.so.12032
#13 0x00007f6d96d4099f in wl_priv_signal_final_emit (data=<optimized out>, signal=<optimized out>)
    at ../wayland-1.22.0/src/wayland-server.c:2377
        l = 0x55f8c3fb1950
        pos = 0x55f8c3fb1950
        resource = 0x55f8c3a207d0
#14 destroy_resource (element=0x55f8c3a207d0, data=data@entry=0x7ffe8bcf6674, flags=0) at ../wayland-1.22.0/src/wayland-server.c:729
        resource = 0x55f8c3a207d0
#15 0x00007f6d96d410db in for_each_helper (entries=0x55f8c3a92580, data=0x7ffe8bcf6674, func=0x7f6d96d40900 <destroy_resource>)
    at ../wayland-1.22.0/src/wayland-util.c:416
        idx = <optimized out>
        ret = WL_ITERATOR_CONTINUE
        entry = {next = <optimized out>, data = <optimized out>}
        start = <optimized out>
        count = <optimized out>
        serial = 0
#16 wl_map_for_each (data=0x7ffe8bcf6674, func=0x7f6d96d40900 <destroy_resource>, map=0x55f8c3a92580)
    at ../wayland-1.22.0/src/wayland-util.c:430
        serial = 0
#17 wl_client_destroy (client=client@entry=0x55f8c3a92550) at ../wayland-1.22.0/src/wayland-server.c:928
        serial = 0
#18 0x00007f6d96d4160e in destroy_client_with_error (reason=<optimized out>, client=<optimized out>)
    at ../wayland-1.22.0/src/wayland-server.c:325
        client = <optimized out>
        connection = <optimized out>
        resource = <optimized out>
        object = <optimized out>
        closure = <optimized out>
        message = <optimized out>
        p = {45, 524288}
        resource_flags = <optimized out>
        opcode = <optimized out>
        size = <optimized out>
        since = <optimized out>
        len = <optimized out>
#19 wl_client_connection_data (fd=<optimized out>, mask=<optimized out>, data=<optimized out>)
    at ../wayland-1.22.0/src/wayland-server.c:454
        client = <optimized out>
        connection = <optimized out>
        resource = <optimized out>
        object = <optimized out>
        closure = <optimized out>
        message = <optimized out>
        p = {45, 524288}
        resource_flags = <optimized out>
        opcode = <optimized out>
        size = <optimized out>
        since = <optimized out>
        len = <optimized out>
#20 0x00007f6d96d40ae2 in wl_event_loop_dispatch (loop=0x55f8c2cc8a80, timeout=timeout@entry=-1)
    at ../wayland-1.22.0/src/event-loop.c:1027
        ep = {{events = 1, data = {ptr = 0x55f8c3a4bff0, fd = -1012613136, u32 = 3282354160, u64 = 94526922604528}}, {events = 1, data = {ptr = 0x55f8c3fb27b0, fd = -1006950480, u32 = 3288016816, u64 = 94526928267184}}, {events = 3800360448, data = {ptr = 0x55f8a832fbe8, fd = -1473053720, u32 = 2821913576, u64 = 94526462163944}}, {events = 1, data = {ptr = 0xb4, fd = 180, u32 = 180, u64 = 180}}, {events = 3288513232, data = {ptr = 0x8bcf6930000055f8, fd = 22008, u32 = 22008, u64 = 10074386546330457592}}, {events = 32766, data = {ptr = 0x55f8c402eae8, fd = -1006441752, u32 = 3288525544, u64 = 94526928775912}}, {events = 3288517336, data = {ptr = 0x8bcf6970000055f8, fd = 22008, u32 = 22008, u64 = 10074386821208364536}}, {events = 32766, data = {ptr = 0x7f6d96d3d500 <wl_connection_flush+304>, fd = -1764502272, u32 = 2530465024, u64 = 140108658627840}}, {events = 0, data = {ptr = 0xb400000000, fd = 0, u32 = 0, u64 = 773094113280}}, {events = 0, data = {ptr = 0x7ffe8bcf6990, fd = -1949341296, u32 = 2345626000, u64 = 140731244046736}}, {events = 0, data = {ptr = 0xb7c, fd = 2940, u32 = 2940, u64 = 2940}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x7f6d966786e0 <(anonymous namespace)::num_get_c>, fd = -1771600160, u32 = 2523367136, u64 = 140108651529952}}, {events = 3288520276, data = {ptr = 0xb4000055f8, fd = 22008, u32 = 22008, u64 = 773094135288}}, {events = 0, data = {ptr = 0x55f8c4016068, fd = -1006542744, u32 = 3288424552, u64 = 94526928674920}}, {events = 4, data = {ptr = 0x1400000000, fd = 0, u32 = 0, u64 = 85899345920}}, {events = 0, data = {ptr = 0x100000001, fd = 1, u32 = 1, u64 = 4294967297}}, {events = 111, data = {ptr = 0x50, fd = 80, u32 = 80, u64 = 80}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x55f800000008, fd = 8, u32 = 8, u64 = 94523640250376}}, {events = 2345625976, data = {ptr = 0x96678d2000007ffe, fd = 32766, u32 = 32766, u64 = 10837786196868890622}}, {events = 32621, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 3800360448, data = {ptr = 0x8bcf6848a832fbe8, fd = -1473053720, u32 = 2821913576, u64 = 10074385552719936488}}, {events = 32766, data = {ptr = 0x55f8c3a5c980, fd = -1012545152, u32 = 3282422144, u64 = 94526922672512}}}
        source = <optimized out>
        i = 0
        count = <optimized out>
        has_timers = <optimized out>
#21 0x00007f6d96d412d7 in wl_display_run (display=0x55f8c2cc8990) at ../wayland-1.22.0/src/wayland-server.c:1493
#22 0x000055f8c1523792 in main ()
```
</details>

**Comment by andresilva** [comment]
I reported this already a couple of weeks ago https://github.com/hyprwm/Hyprland/issues/3422 and even pointed to the commit that introduced the issue.

**Comment by memchr** [comment]
There is no source location, can you build hyprland from source with debug options? 
```
make debug
```
Close the current session and run hyprland in a tty.
```
./build/Hyprland
```
And reproduce the crash, you will get a new coredump.
Then start gdb and run `bt -full` again 
```
coredumpctl debug Hyprland
```

**Comment by vaxerski** [comment]
crash report should be fixed in 015664eb4cde5ab93cfacbfd8c2e831eeb876634

**Comment by rszyma** [comment]
ok cool, now it doesn't crash but the xwayland (and electron running native wayland, according to andresilva's comment) apps still crash

**Comment by vaxerski** [comment]
hamburger cheeseburger big mac whopper

**Comment by rszyma** [comment]
me neither

I'll drop this here maybe you figure out something

[hyprland.log](https://github.com/hyprwm/Hyprland/files/13065111/hyprland.log)

1. opened alacritty, 
1. opened vscode, 
1. pressed shortcut for suspending (line 586)
1. woke up from suspend

end of file is the moment when system woke up from suspend

In between 586-EOF vscode and waybar died

**Comment by phonetic112** [comment]
waybar log when re-enabling monitor: 
```
Gdk-Message: 21:22:49.762: Error 22 (Invalid argument) dispatching to Wayland display.
```

xeyes (xwayland):
```
X connection to :0 broken (explicit kill or server shutdown).
```

discord (electron): 
```
[17638:1022/212952.603461:ERROR:wayland_screen.cc(163)] output_id is not associated with a Display.
[17638:1022/212952.607106:ERROR:wayland_event_watcher.cc(36)] libwayland: wl_display@1: error 0: invalid object 42
```

**Comment by brettalcox** [comment]
Anything else we can provide? I'm experiencing this as well--a regression from 0.30.0 -> 0.31.0. Has anyone done a git-bisect to determine the offending commit?

**Comment by andresilva** [comment]
Yes, it's https://github.com/hyprwm/Hyprland/commit/46d66f4bcc95d9fb7fede18ad5c2c043796b9071.

**Comment by ksolowoniuk** [comment]
I'm having a similar issue on FreeBSD 14-RC3. If I run Chromium and either turn off the monitor or suspend with `acpiconf -s3`, when the system resumes the Chromium window is gone but the process is still running. If I kill the process with `pkill chromium` and try to restart Chromium, Hyprland crashes. I just started a discussion on the issue then came across this post.

**Comment by ICE-GB** [comment]
my bt -full

**Comment by vaxerski** [comment]
can yall try #3713
