### ISSUE TITLE
regression: groupbar incorrect position

### ISSUE THREAD

**Issue by andresilva** [hyprwm/Hyprland#3841]
### Hyprland Version

9afdd61adeaf413afbe853dbc5fdf6853c8bde21

### Bug or Regression?

Regression

### Description

Groupbar gets rendered below waybar. Sometimes it just completely disappears. Doesn't seem to get resized with the window.

### How to reproduce

Groupbar settings:

```
group:groupbar:render_titles = false
group:groupbar:gradients = false
```

**Comment by andresilva** [comment]
Tested on e974d1fe and it's still very broken.

https://github.com/hyprwm/Hyprland/assets/123550/d51d1e29-7e34-40f3-bb41-f29fb798395e

You can see the groupbar being incorrectly sized and even disappearing at some point.

**Comment by vaxerski** [comment]
deez nuts

**Comment by vaxerski** [comment]
0ba2e6870478bcf1af1b6508677b46a3484fb21f  tryt t t  :)))

**Comment by andresilva** [comment]
Most of the issues seem to be fixed. Only thing broken I was able to find was when moving a window into the group the padding would be wrong until you move to the next window in the group.



https://github.com/hyprwm/Hyprland/assets/123550/32b044aa-77c2-4a81-8713-24ae477886e3

**Comment by goggi** [comment]
https://github.com/hyprwm/Hyprland/assets/1946339/ec22f669-12ee-44ff-8797-8ac2cd021692

Hi! Something also seems off with how the groupbar interacts with the animations

**Comment by vaxerski** [comment]
fixed above in 45e86d4fdf425452a39010de582081c466657045

**Comment by goggi** [comment]
> fixed above in [45e86d4](https://github.com/hyprwm/Hyprland/commit/45e86d4fdf425452a39010de582081c466657045)

That fixed the issue, thanks!

**Comment by goggi** [comment]
> Most of the issues seem to be fixed. Only thing broken I was able to find was when moving a window into the group the top padding would be wrong until you move to the next window in the group.
> broken-groupbar3.mp4

This is also the only issue left for me with regards to the groupbar. Here is another video for reference with the render_titles option enabled. 

https://github.com/hyprwm/Hyprland/assets/1946339/986b77a7-e60e-4cab-9bb5-d85c64d61706

**Comment by q234rty** [comment]
For me it doesn't render correctly at all even with the latest commit:
![图片](https://github.com/hyprwm/Hyprland/assets/11485439/a2dfbd72-53ae-4e5b-b80a-df7be887e780)

**Comment by vaxerski** [comment]
> This is also the only issue left for me with regards to the groupbar. Here is another video for reference with the render_titles option enabled.

fixed that one in 5edb4e4a304bbef1de30a36f7b921ea328d7efc6

Can this be closed then?

**Comment by andresilva** [comment]
Can no longer replicate with Alacritty, but still happens when you open a GTK app.


https://github.com/hyprwm/Hyprland/assets/123550/b1472cc8-af07-4d86-b9fb-e316b4f1c7fb

Also there seems to be some weird flashing when opening a new window into the group, that wasn't there before I think (will test later with an older version). Either way, not a deal-breaker for me.

**Comment by goggi** [comment]
> > This is also the only issue left for me with regards to the groupbar. Here is another video for reference with the render_titles option enabled.
> 
> fixed that one in [5edb4e4](https://github.com/hyprwm/Hyprland/commit/5edb4e4a304bbef1de30a36f7b921ea328d7efc6)
> 
> Can this be closed then?

That issue has been fixed! Any chance you can lower the padding back to how it was previously? 

![image](https://github.com/hyprwm/Hyprland/assets/1946339/d7a10a95-fce3-42df-b320-22a8fbd7346c)
vs
(will add it soon)

**Comment by goggi** [comment]
> > This is also the only issue left for me with regards to the groupbar. Here is another video for reference with the render_titles option enabled.
> 
> fixed that one in [5edb4e4](https://github.com/hyprwm/Hyprland/commit/5edb4e4a304bbef1de30a36f7b921ea328d7efc6)
> 
> Can this be closed then?

That issue has been fixed! Any chance you can lower the padding back to how it was previously? 

![image](https://github.com/hyprwm/Hyprland/assets/1946339/d7a10a95-fce3-42df-b320-22a8fbd7346c)
vs
![image](https://github.com/hyprwm/Hyprland/assets/1946339/2f4b8d89-bce5-46e4-b006-ab41ed881abb)

**Comment by andresilva** [comment]
@goggi Have you tried to replicate by opening a GTK app into the groupbar?

**Comment by goggi** [comment]
> @goggi Have you tried to replicate by opening a GTK app into the groupbar?

@andresilva  I tried with gimp just now and did not notice any issues

**Comment by goggi** [comment]
> > This is also the only issue left for me with regards to the groupbar. Here is another video for reference with the render_titles option enabled.
> 
> fixed that one in [5edb4e4](https://github.com/hyprwm/Hyprland/commit/5edb4e4a304bbef1de30a36f7b921ea328d7efc6)
> 
> Can this be closed then?

I did find another issue now when opening chrome. Same as before. 

https://github.com/hyprwm/Hyprland/assets/1946339/7e291655-18b9-4a9c-8884-cbe05ab2ef5b

**Comment by andresilva** [comment]
> > @goggi Have you tried to replicate by opening a GTK app into the groupbar?
> 
> @andresilva I tried with gimp just now and did not notice any issues

Yeah GIMP seems to work. Can replicate with Thunar, Catfish, LibreOffice (and didn't look for more).

**Comment by andresilva** [comment]
> > > This is also the only issue left for me with regards to the groupbar. Here is another video for reference with the render_titles option enabled.
> > 
> > 
> > fixed that one in [5edb4e4](https://github.com/hyprwm/Hyprland/commit/5edb4e4a304bbef1de30a36f7b921ea328d7efc6)
> > Can this be closed then?
> 
> I did find another issue now when opening Chrome. Same as before. But it only happens when opening chrome inside a group. If I move a already opened Chrome window into a group it works fine
> Kooha-2023-11-13-21-12-23.mp4

This is the same bug I'm reporting AFAIU.

**Comment by andresilva** [comment]
https://github.com/hyprwm/Hyprland/commit/5edb4e4a304bbef1de30a36f7b921ea328d7efc6#diff-2d1b7537c82c5e3e8f7ec279b41ce3643526625913c3d4138f31f3b0354e2957 

The `forceRecalcFor` here that's done when adding a window decoration is superfluous, it always early exists because the window isn't mapped by this point. Not sure if this is the root cause of the problem, but maybe it helps to debug the issue (I couldn't fix it) 🤷.

**Comment by fleurc** [comment]
Sometimes, also, for a split second when switching workspaces the groupbar will appear in the new workspace despite the Group not being moved to that workspace, then it disappears after a second or two.

**Comment by andresilva** [comment]
> Can no longer replicate with Alacritty, but still happens when you open a GTK app.
> broken-groupbar-compressed.mp4
> 
> ~Also there seems to be some weird flashing when opening a new window into the group, that wasn't there before I think (will test later with an older version). Either way, not a deal-breaker for me.~ Just tested with old version and the flashing was always there. The only difference in behavior is that now the groupbar seems to be animated as well. That's fine with me.

This is now fixed for me, not sure which commit fixed it. I don't have any other problem with groupbar positioning. If anyone still has problems please say so, otherwise I'll close this issue.
