### ISSUE TITLE
Firefox problems when 'follow_mouse=0'

### ISSUE THREAD

**Issue by g3r** [hyprwm/Hyprland#390]
When ```follow_mouse=0``` Firefox popups are not automatically focused and bookmarks in the toolbar cannot be moved.

Steps to reproduce:
In firefox open the application menu or the right click menu
Hover the cursor over the popup
The item below the cursor is not highlighted

**Comment by vaxerski** [comment]
dunno if I understand you correctly, but if I do, then fixed in 21217bcb2bb691ea015563a7ba7ce2d334de6b39

**Comment by g3r** [comment]
That fixed the popup focus but the bookmarks in the toolbar still can't be moved with follow_mouse disabled.

**Comment by vaxerski** [comment]
i see ok

**Comment by vaxerski** [comment]
sorry for the delay, fixed in 9564a4cd127d2d24324fc8a9adb6096960248ec8.

New option, by default enabled, `misc:always_follow_on_dnd` will make the pointer focus follow the mouse when drag and dropping, which should also fix drag and dropping in general. **It's enabled by default, so you dont need to change any config opts**

If you have any issues with that, lmk, or open another issue.
