### ISSUE TITLE
Crashes with menus in GTK applications

### ISSUE THREAD

**Issue by dev11n** [hyprwm/Hyprland#434]
## Reproduce
Install WebCord and press one of the buttons in the navbar, then cycle through them fast. Sometimes Hyprland instantly crashes after just pressing a single button in the navbar, and sometimes it takes a while.

This also happens in virt-manager, KeePassXC (Right-Click menu), Firefox (Right-Click menu) and other applications.

Last log from a WebCord crash: https://privatebin.net/?ccaebe028f02db97#6NxwzoCXBQJQJQ753Nf3QaeeV2WsReLnY7wh6rnKqaXF

Coredump : https://privatebin.net/?82a2b4f88bb410e9#D12k7EpCgLG8FrvM8LHGdCAa5Qq7u1fcZg4K95Zqe2vm

**Comment by vaxerski** [comment]
Was fixed in the newest commit. Please recompile. Cheers.

**Comment by dev11n** [comment]
Just tested it, still crashes with this coredump https://privatebin.net/?ca4a4006494b9c2d#Y7UMVDYdTuWGitctvkbZnFbA7txNSToHS3QgHCCfxXA

**Comment by vaxerski** [comment]
trouble is i cant reproduce this. Will check more thoroughly tomorrow though.

**Comment by vaxerski** [comment]
should be fixed in d3c1d3435c2667c48c22926c48c7d5690d2c7009

**Comment by dev11n** [comment]
Tested and seems to be fixed, can cycle through both virt-manager & webcords navbars w/o it falling on its head and crying. ty 👍🏽
