### ISSUE TITLE
Top layer + slurp refocus issues

### ISSUE THREAD

**Issue by MightyPlaza** [hyprwm/Hyprland#4460]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch makepkg at commit f14c5ea5c56858260c1133d8003fc5961ace373d dirty (groupbar: separate gradients from title (4444)).
Date: Mon Jan 15 15:17:42 2024
Tag: v0.34.0-47-gf14c5ea5

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

After using slurp and releasing mouse button on top of yambar (can't repro on waybar), the focus does not return to the previous window, instead the window looks like active (border, ...) but does not have keyboard input

This patch removes the issue
```diff

diff --git a/src/events/Layers.cpp b/src/events/Layers.cpp
index d6e21d9d..c5e8e8ce 100644
--- a/src/events/Layers.cpp
+++ b/src/events/Layers.cpp
@@ -232,7 +232,7 @@ void Events::listener_unmapLayerSurface(void* owner, void* data) {
         foundSurface = g_pCompositor->vectorToLayerSurface(g_pInputManager->getMouseCoordsInternal(), &PMONITOR->m_aLayerSurfaceLayers[ZWLR_LAYER_SHELL_V1_LAYER_OVERLAY],
                                                            &surfaceCoords, &pFoundLayerSurface);
 
-        if (!foundSurface)
+        if (!foundSurface && false)
             foundSurface = g_pCompositor->vectorToLayerSurface(g_pInputManager->getMouseCoordsInternal(), &PMONITOR->m_aLayerSurfaceLayers[ZWLR_LAYER_SHELL_V1_LAYER_TOP],
                                                                &surfaceCoords, &pFoundLayerSurface);
 
```

### How to reproduce

<details> <summary>How to Repro</summary>

(I am using `follow_mouse = 2` and it likely is required to repro)

Use yambar
(Example config, top layer required (overlay doesn't seem to have the issue))
```yml
bar:
  height: 20 
  location: top 
  background: 000000ff
  layer: bottom 

```

start slurp from a terminal
end selection on top of yambar
terminal looks like focused but doesn't have keyboard focus

</details>

**Comment by MightyPlaza** [comment]
i have a patch to propose
```diff
diff --git a/src/managers/input/InputManager.cpp b/src/managers/input/InputManager.cpp
index 23e183d0..2a05b5b5 100644
--- a/src/managers/input/InputManager.cpp
+++ b/src/managers/input/InputManager.cpp
@@ -1464,6 +1464,11 @@ void CInputManager::refocusLastWindow(CMonitor* pMonitor) {
         const auto PLASTWINDOW = g_pCompositor->m_pLastWindow.lock();
         g_pCompositor->focusWindow(PLASTWINDOW);
     } else {
+        if (foundSurface && pFoundLayerSurface && pFoundLayerSurface->interactivity == 0) {
+            const auto PLASTWINDOW = g_pCompositor->m_pLastWindow.lock();
+            g_pCompositor->focusWindow(PLASTWINDOW);
+        }
+
         // otherwise fall back to a normal refocus.
         refocus();
     }
```
seems like `refocus()` will set mouse focus to the surface (yambar)  but keyboard focus is never set because the layer doesn't support keyboard interactivity
is this a proper solution @vaxerski ?

**Comment by vaxerski** [comment]
no clue, needs testing. I would say its ok

**Comment by BluewyDiamond** [comment]
the patch fixes my problem which i opened the issue as https://github.com/hyprwm/Hyprland/issues/6929

**Comment by BluewyDiamond** [comment]
> i have a patch to propose
> 
> ```diff
> diff --git a/src/managers/input/InputManager.cpp b/src/managers/input/InputManager.cpp
> index 23e183d0..2a05b5b5 100644
> --- a/src/managers/input/InputManager.cpp
> +++ b/src/managers/input/InputManager.cpp
> @@ -1464,6 +1464,11 @@ void CInputManager::refocusLastWindow(CMonitor* pMonitor) {
>          const auto PLASTWINDOW = g_pCompositor->m_pLastWindow.lock();
>          g_pCompositor->focusWindow(PLASTWINDOW);
>      } else {
> +        if (foundSurface && pFoundLayerSurface && pFoundLayerSurface->interactivity == 0) {
> +            const auto PLASTWINDOW = g_pCompositor->m_pLastWindow.lock();
> +            g_pCompositor->focusWindow(PLASTWINDOW);
> +        }
> +
>          // otherwise fall back to a normal refocus.
>          refocus();
>      }
> ```
> 
> seems like `refocus()` will set mouse focus to the surface (yambar) but keyboard focus is never set because the layer doesn't support keyboard interactivity is this a proper solution @vaxerski ?

just in case, im talking about this patch and i haven't tried the first one.

**Comment by vaxerski** [comment]
isnt this fixed in git

**Comment by BluewyDiamond** [comment]
this commit 963816b9a6524a99a6716fa1aa30b2c4f369d2f0 which meant to solve it didn't fix it for me while applying the 2nd patch proposed by @MightyPlaza on top of the commit 963816b9a6524a99a6716fa1aa30b2c4f369d2f0 fixes my problem

**Comment by MightyPlaza** [comment]
> isnt this fixed in git

nop from me as well

the other issue seems like a dupe of this one
the mouse is on top of a layer that accepts mouse input but not keyboard input, so keyboard input isn't set in `refocus()`

**Comment by vaxerski** [comment]
odd, it fixed it for me. Anyways, sure.
