### ISSUE TITLE
hyprpm headers missing even when updating

### ISSUE THREAD

**Issue by deviantsemicolon** [hyprwm/Hyprland#4479]
### Hyprland Version

<details> <summary></summary>

```sh
Hyprland, built from branch  at commit v0.34.0  ().
Date: 2024-01-01
Tag: 

flags: (if any)
```
it also doesn't work on the flake development version
</details>

### Bug or Regression?

Bug

### Description

hyprpm told me that i should run hyprpm update because the headers were missing. i did that, and headers were still missing when running hyprpm update

### How to reproduce

On NixOS 24.05, type hyprpm update.

### Crash reports, logs, images, videos

hyprpm update output:

```
! Cloning https://github.com/hyprwm/hyprland, this might take a moment.                                                                                                                                      
✔ cloned                                                                                                                                                                                                     
✔ checked out to running ver                                                                                                                                                                                 
! configuring Hyprland                                                                                                                                                                                       
✔ configured Hyprland                                                                                                                                                                                        
! in order to install the sources, you will need to input your password.                                                                                                                                     
  If nothing pops up, make sure you have polkit and an authentication daemon running.
✖ failed to install headers with error code 2                                                                                                                                                                
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5 / 5  Failed                                                                                                                                           

✖ Headers missing. Please run hyprpm update to fix those.
```

**Comment by deviantsemicolon** [comment]
also yes i did the polkit thing. i'm using lxqt polkit because i couldn't get kde polkit to work

**Comment by deviantsemicolon** [comment]
it also doesn't work on the flake development version. I checked

**Comment by vaxerski** [comment]
can you `-v`

**Comment by fufexan** [comment]
@vaxerski where are headers installed? If it's anywhere outside `$HOME`, tough luck.

**Comment by vaxerski** [comment]
it is outside home. `/usr/include`

**Comment by deviantsemicolon** [comment]
> can you `-v`
> 
> Plus, NixOS is special. Idk how hyprpm will work there. @fufexan ?

Like this?

```
[v] version returned: Hyprland, built from branch  at commit c4365f20ed8ff0dd480b7ed7cf1bfff1a0b6911a  ().
Date: 2024-01-17
```

**Comment by deviantsemicolon** [comment]
also i'd imagine the only way to make them remotely work is by making them a nixos module, because configuration.nix is the only file that actually makes your system build. I could be wrong though

**Comment by deviantsemicolon** [comment]
ok. apparently the only way to make plugins work right now is to declare them in home manager. that's how you get them to work. hyprpm doesn't work on nixos

**Comment by jeanlucthumm** [comment]
This is also failing on Arch Linux, I don't think it's a NixOS thing.

**Comment by dieBakterie** [comment]
Same issue with Arch Linux too

**Comment by ThatOneCalculator** [comment]
Can repro

**Comment by ThatOneCalculator** [comment]
Update: installing `hyprland-git` seems to have fixed the problem, likely from https://github.com/hyprwm/Hyprland/commit/eeca50e3dcf472d92431f0f06151a76c453c865e

**Comment by vaxerski** [comment]
it should be fixed in arch's 0.39.1

**Comment by ThatOneCalculator** [comment]
Yep. I use the ALHP repo for x86-64-v3 builds which doesn't have it yet. Manually specified `extra/hyprland` until it's up there.

![image](https://github.com/hyprwm/Hyprland/assets/44733677/da94a9db-54ee-4e0e-8e7a-90e846fbff7e)

**Comment by tvlpirb** [comment]
I'm still getting the error on Arch Linux, I've updated and rebooted just to be sure. Here are the relevant details:

```
╰─>$ hyprctl version                                                                                                                                              23:23:34
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)
```

**Comment by vaxerski** [comment]
relevant details are the output of whatever cmd you're running with `-v`

**Comment by tvlpirb** [comment]
Apologies for the lack of detail, I was getting the same error as the OP but I've been able to fix it based of the -v output. My cmake version was too low as it was using a user installed one rather than the distro packaged version.

**Comment by MrManiacc** [comment]
I was getting the same error, on arch with hyprland `Tag: v0.39.1, commits: 4460` until I stumbled upon this  #4682 

Just make sure you have `cpio` installed. 

On arch, you can get cpio with `sudo pacman -S cpio`.

**Comment by chakay37** [comment]
I had the same error.
Installing the `hyprwayland-scanner` worked for me. on arch `sudo pacman -S hyprwayland-scanner`.

**Comment by Vulpesx** [comment]
If you have `cpio` and it still doesn't work, install `hyprwayland-scanner`
that worked for me at least

**Comment by ALEX5402** [comment]
> If you have `cpio` and it still doesn't work, install `hyprwayland-scanner` that worked for me at least

I am facing the same issue but this one work for me as well thanks

**Comment by leoamaro01** [comment]
Hey sorry to necro this thread, but in case someone finds this and has the same issue even after following every advice here, turns out you need to install `make` with `sudo pacman -S make` to be able to build your headers, not only `cmake`

**Comment by ashupednekar** [comment]
```bash

~ ✗ sudo pacman -S make
[sudo] password for ashu: 
warning: make-4.4.1-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Package (1)  Old Version  New Version  Net Change

core/make    4.4.1-2      4.4.1-2        0.00 MiB

Total Installed Size:  1.67 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                [----------------------------------] 100%
(1/1) checking package integrity                              [----------------------------------] 100%
(1/1) loading package files                                   [----------------------------------] 100%
(1/1) checking for file conflicts                             [----------------------------------] 100%
(1/1) checking available disk space                           [----------------------------------] 100%
:: Running pre-transaction hooks...
(1/1) Wait for limine-snapper-sync to finish before updating, installing or removing.
:: Processing package changes...
(1/1) reinstalling make                                       [----------------------------------] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Updating the info directory file...

~ ❯ hyprpm update

✔ Headers up to date.
✖ No repos to update.
✔ Ensuring plugin load state
✔ Plugin load state ensured

~ ❯ hyprpm add https://github.com/outfoxxed/hy3
✖ Headers outdated, please run hyprpm update.

~ ✗ `
```

That didn't work either 🥲

**Comment by Zebra2711** [comment]
> ~ ✗ sudo pacman -S make
> [sudo] password for ashu: 
> warning: make-4.4.1-2 is up to date -- reinstalling
> resolving dependencies...
> looking for conflicting packages...
> 
> Package (1)  Old Version  New Version  Net Change
> 
> core/make    4.4.1-2      4.4.1-2        0.00 MiB
> 
> Total Installed Size:  1.67 MiB
> Net Upgrade Size:      0.00 MiB
> 
> :: Proceed with installation? [Y/n] 
> (1/1) checking keys in keyring                                [----------------------------------] 100%
> (1/1) checking package integrity                              [----------------------------------] 100%
> (1/1) loading package files                                   [----------------------------------] 100%
> (1/1) checking for file conflicts                             [----------------------------------] 100%
> (1/1) checking available disk space                           [----------------------------------] 100%
> :: Running pre-transaction hooks...
> (1/1) Wait for limine-snapper-sync to finish before updating, installing or removing.
> :: Processing package changes...
> (1/1) reinstalling make                                       [----------------------------------] 100%
> :: Running post-transaction hooks...
> (1/2) Arming ConditionNeedsUpdate...
> (2/2) Updating the info directory file...
> 
> ~ ❯ hyprpm update
> 
> ✔ Headers up to date.
> ✖ No repos to update.
> ✔ Ensuring plugin load state
> ✔ Plugin load state ensured
> 
> ~ ❯ hyprpm add https://github.com/outfoxxed/hy3
> ✖ Headers outdated, please run hyprpm update.
> 
> ~ ✗ `
> 
> That didn't work either 🥲

`hyprpm purge-cache` -> logout-login

**Comment by ashupednekar** [comment]
worked
```bash

~ ❯ hyprpm add https://github.com/outfoxxed/hy3
[sudo] password for ashu: 

✔ Headers up to date.
! Disclaimer: 
plugins, especially not official, have no guarantee of stability, availability or security.
Run them at your own risk.
This message will not appear again.
✔ adding a new plugin repository from https://github.com/outfoxxed/hy3
  MAKE SURE that you trust the authors. DO NOT install random plugins without verifying the code and author.
  Are you sure? [Y/n] Y

→ Cloning https://github.com/outfoxxed/hy3
✔ cloned
✔ found hyprpm manifest
✔ parsed manifest, found 1 plugins:
→ hy3 by outfoxxed version 
→ Manifest has 31 pins, checking
✔ Hyprland headers OK
→ Building hy3
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)
```

Thanks 👍
