### ISSUE TITLE
The plug-in failed to hook some functions in hyprland V0.34.0

### ISSUE THREAD

**Issue by DreamMaoMao** [hyprwm/Hyprland#4484]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh

Hyprland, built from branch main at commit https://github.com/hyprwm/Hyprland/commit/c4365f20ed8ff0dd480b7ed7cf1bfff1a0b6911a dirty (damage: use buffer_damage instead of effective_damage).
Date: Wed Jan 17 23:01:20 2024
Tag: v0.34.0-51-gc4365f20


```

</details>

### Bug or Regression?

Bug

### Description

 when I try to hook a function:`IHyprLayout::requestFocusForWindow`, it   success in hyprland V0.30.0 but fail in hyprland V0.34.0.
![image](https://github.com/hyprwm/Hyprland/assets/30348075/3360fe1c-13aa-4bc4-a5ea-6777364db5bd)

When I added a log print to this function, it suddenly became hookable in V0.34.0.The results of this operation have been tested repeatedly and  it always occur.

![image](https://github.com/hyprwm/Hyprland/assets/30348075/79903e2d-4974-4f24-b236-28d18da4f602)
![image](https://github.com/hyprwm/Hyprland/assets/30348075/76a4c0dc-4cd2-4827-a6f9-d87ad2880304)

### How to reproduce

1.hook the function `IHyprLayout::requestFocusForWindow`.

 ```cpp
  g_pIHyprLayout_requestFocusForWindowHook = HyprlandAPI::createFunctionHook(PHANDLE, (void*)&IHyprLayout::requestFocusForWindow, (void*)&hkIHyprLayout_requestFocusForWindow);
  g_pIHyprLayout_requestFocusForWindowHook->hook();
```

2.check message in hyprland.log.

**Comment by vaxerski** [comment]
right. Odd that it failed assembling, considering it looks like valid asm, but IIRC the lea with %rip should not be there. I'll fix this uhhh in 2 days. Remind me if I forget.

**Comment by zakk4223** [comment]
I think the negative offset is being fed raw into configStringToInt and failing to parse?

**Comment by vaxerski** [comment]
that is a thought

**Comment by DreamMaoMao** [comment]
not only function, some event hook have same issue: 
for example hook the keyPress event
```
[LOG] [hookSystem] New hook event registered: keyPress
[ERR] [functionhook] failed, unsupported asm / failed assembling:
invalid 
sub $0x18, %rsp
mov (%rdi), %rax
lea -0x42(%rip), %rdx

[LOG] [functionhook] assembler returned:

[LOG] [functionhook] assembler returned:

[LOG]  [PluginSystem] Plugin hych loaded. Handle: 5651a333bbd0, path: "/usr/lib/libhych.so", author: "DreamMaoMao", description: "Window minimization plugin", version: "0.1"
[LOG] Reloading the config!
[LOG] Creating the DecorationPositioner!
[WARN] Failed to change process scheduling strategy
[LOG] Hyprland init finished.
```

**Comment by DreamMaoMao** [comment]
> right. Odd that it failed assembling, considering it looks like valid asm, but IIRC the lea with %rip should not be there. I'll fix this uhhh in 2 days. Remind me if I forget.

As an on-time alarm clock,two days are up. Any progress?

**Comment by vaxerski** [comment]
my flight got cancelled, I should be back home later today. The other thing you posted was fixed some time after 0.34

**Comment by DreamMaoMao** [comment]
What does `the other thing you post` mean?  it mean the event hook error?   I have thy the latest commit, it doesn't fix.

**Comment by vaxerski** [comment]
the one with unsupported asm where it says `invalid` at the beginning of the asm dump.

I think I fixed that after 0.34.0, it was an odd intel op

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14038145/patch.txt)
sorry for the delay, real life stuff.

Please test this.

**Comment by DreamMaoMao** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/30348075/2fca0eb3-c4ca-4fa0-8e50-30ab0f6a1a94)


![swappy-20240124-204358](https://github.com/hyprwm/Hyprland/assets/30348075/119dce4a-546c-4d0f-a5fb-f64dfad68a15)


it work.
