### ISSUE TITLE
VRR state change causes crash

### ISSUE THREAD

**Issue by zakk4223** [hyprwm/Hyprland#4546]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit bc7e488a4c7a4bfdd7bce66265fe8aea516fd2ed dirty (monitor: clear output state after usage).
Date: Sat Jan 27 14:11:14 2024
Tag: v0.34.0-69-gbc7e488a

flags: (if any)


System Information:
System name: Linux
Node name: blkheart
Release: 6.7.1-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sun, 21 Jan 2024 22:13:51 +0000


GPU information:
0d:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] [1002:73bf] (rev c0) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  River Layout by Zakk ver 1.0
  XWayland Primary Display by Zakk ver 1.0
  N_Stack layout by Zakk ver 1.0
  Monitor WS rules by Zakk ver 1.0
  split-monitor-workspaces by Duckonaut ver 1.1.0
  Workspace layouts by Zakk ver 1.0
```

</details>

### Bug or Regression?

Bug

### Description

Any change to the VRR state seems to crash hyprland. vrr=2 -> fullscreen a window -> crash.
It crashes if I edit the config and change vrr=2 to vrr=0.

### How to reproduce

I think it's commit bc7e488 but I haven't tried reverting/bisecting. Looks like it from the coredump tho.

### Crash reports, logs, images, videos

[hyprlandCrashReport24145.txt](https://github.com/hyprwm/Hyprland/files/14073859/hyprlandCrashReport24145.txt)
[vrrcrash.dump.gz](https://github.com/hyprwm/Hyprland/files/14073864/vrrcrash.dump.gz)

**Comment by ZoeBattleSand** [comment]
I am having a very similar issue where putting any window into fullscreen crashes hyprland.
Reverting bc7e488 fixes the issue.

**Comment by vaxerski** [comment]
fucking wlroots.

**Comment by vaxerski** [comment]
untested, but should fix this. See above.

**Comment by ArtemSmaznov** [comment]
Mine still crashes on 9002657bcca1d4f69e2ebd0447d4129fdb950245

**Comment by ZoeBattleSand** [comment]
Yeah, the issue is still present with 9002657

**Comment by vaxerski** [comment]
I am not blind, man. Can see.

**Comment by ArtemSmaznov** [comment]
Man you are a monster - solving issues faster than I even expect the ticket to be reviewed at all. Really appreciate your hard work.
Can confirm this is resolved on my side

**Comment by vaxerski** [comment]
crashes are bad
