### ISSUE TITLE
Mouse wheel scroll doesn't work in some applications

### ISSUE THREAD

**Issue by dragove** [hyprwm/Hyprland#465]
Bug: In some applications (e.g. wezterm, telegram-desktop). scrolling doesn't work.
Version: 0.9.1beta installed from [AUR](https://aur.archlinux.org/packages/hyprland-bin)

**Comment by DiedByDisgust** [comment]
Same here, telegram-desktop.

**Comment by vaxerski** [comment]
If this is a regression, doing a `git bisect` would be nice. If noone here is able to, I'll pester @fufexan to do one tomorrow. It's 1AM atm

**Comment by DiedByDisgust** [comment]
> If this is a regression, doing a `git bisect` would be nice. If noone here is able to, I'll pester @fufexan to do one tomorrow. It's 1AM atm

done, After having performed the bisect process, I discovered that there is no problem if the manual build is done, only when install the 0.9.1 bin release file.

**Comment by fufexan** [comment]
Impossible. Nix builds it on every new commit, and I still have the bug.

**Comment by vaxerski** [comment]
make a bisect then @fufexan

**Comment by fufexan** [comment]
l8r bruv im going to the dentist

**Comment by luxus** [comment]
i can confirm.. cannot scroll on wezterm but it works on kitty

**Comment by KyleUltimate** [comment]
huh, disabing wayland in wezterm fixes it for me

**Comment by fufexan** [comment]
![image](https://user-images.githubusercontent.com/36706276/182853078-f0227c85-a19a-4707-a4e2-42bbe5c4a1e5.png)
We found our culprit.

**Comment by DiedByDisgust** [comment]
> update wlroots dep


i just did

```
git clone https://github.com/hyprwm/Hyprland.git hyprland-git
cd hyprland-git
git submodule update --init
sudo make fixwlr
git checkout 02fbb3a
sudo make install
```
works for me.

**Comment by vaxerski** [comment]
d58233d08bdc5c0a533891c6d1f8458449639992 should close this then.

**Comment by dragove** [comment]
I can confirm the latest git version works. Thanks.
