### ISSUE TITLE
Crash on single window

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#477]
With a border_size of 0, and no_gaps_when_only enabled, Hyprland crashes as soon as there is only one window on the workspace.

**Comment by vaxerski** [comment]
wasnt that fixed in f66365d9dad8ead1bcb7f1b7cdb4820cd9afce2e

**Comment by Dickby** [comment]
It still crashes with my configuration.
[hyprland.txt](https://github.com/hyprwm/Hyprland/files/9271185/hyprland.txt)

**Comment by vaxerski** [comment]
dump then

**Comment by Dickby** [comment]
Do you mean the log (how it's described by the Wiki), or an coredump?

**Comment by vaxerski** [comment]
coredump

**Comment by Dickby** [comment]
Do i have to compile with debug flags first, or is the coredump usefull without?
Sorry for my incompetence.

**Comment by vaxerski** [comment]
give without, I'll see if I can salvage it.

**Comment by Dickby** [comment]
Hope it's the right thing!
[coredump.zip](https://github.com/hyprwm/Hyprland/files/9271302/coredump.zip)

**Comment by vaxerski** [comment]
Not what I asked for - please use the instructions here: https://github.com/hyprwm/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md#obtaining-the-hyprland-coredump

And if you are not on systemd - it's your responsibility to know the tools you're using. Provide me a call stack in that case, the most important part.

**Comment by Dickby** [comment]
[coredump.txt](https://github.com/hyprwm/Hyprland/files/9271447/coredump.txt)

**Comment by vaxerski** [comment]
god bless.

**Comment by vaxerski** [comment]
should be fixed in 74cbfdcda4d91b8914340d25cf78f5c85e7f2e8c

**Comment by Dickby** [comment]
Well, you live you learn!
It's fixed thanks a lot!
