### ISSUE TITLE
Need to manually reload hyprland config after rebuilding on Nixos

### ISSUE THREAD

**Issue by Ligthiago** [hyprwm/Hyprland#4825]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit d92da7959a1d271c585d0a7de4c75a389bd1ac05  ().
Date: 2024-02-24
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: theseus
Release: 6.7.5
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Feb 16 18:14:32 UTC 2024


GPU information: 
09:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev e7) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240223.cbc4211"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
  hycov by DreamMaoMao ver 0.3

```

</details>

### Bug or Regression?

Bug

### Description

Ok, I am not sure if this is a real problem or I just have a bad memory, but now I have to manually reload the hyprland configuration with `hyprctl reload` after rebuilding my nix config with `nixos-rebuild switch`, and I do not remember having to do this in older days.

### How to reproduce

For example:
- I change value (e.g. border rounding) in nix config.
- Build new generation and switch to it
- Nothing changed, borders are the same, but in `.config/hypr/hyprland.conf` the rounding value changed to the new one.
- Border only changed after manually running `hyprctl reload' in terminal. I don't remember having to do this, changes just instantly applied. But maybe I am wrong and it just Mandela effect or something.

**Comment by vaxerski** [comment]
@fufexan for nix

**Comment by fufexan** [comment]
I think the way HM reloads the config broke a while ago, due to some changes in Hyprland. 
This patch should fix it, I'll try to open a PR today.
```diff
diff --git a/modules/services/window-managers/hyprland.nix b/modules/services/window-managers/hyprland.nix
index 168bab65..b280283b 100644
--- a/modules/services/window-managers/hyprland.nix
+++ b/modules/services/window-managers/hyprland.nix
@@ -247,10 +247,8 @@ in {
       onChange = lib.mkIf (cfg.package != null) ''
         ( # Execute in subshell so we don't poision environment with vars
           if [[ -d "/tmp/hypr" ]]; then
-            # This var must be set for hyprctl to function, but the value doesn't matter.
-            export HYPRLAND_INSTANCE_SIGNATURE="bogus"
             for i in $(${cfg.finalPackage}/bin/hyprctl instances -j | jq ".[].instance" -r); do
-              HYPRLAND_INSTANCE_SIGNATURE=$i ${cfg.finalPackage}/bin/hyprctl reload config-only
+              ${cfg.finalPackage}/bin/hyprctl reload config-only
             done
           fi
         )
```

**Comment by Ligthiago** [comment]
I updated HM to latest rev `4ee704cb13a5a7645436f400b9acc89a67b9c08a (xscreensaver: add package option)` after merge, issue is still here.

Also:
```sh
❱ hyprctl instances -j | jq ".[].instance" -r
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoull
```

**Comment by Ligthiago** [comment]
Fixed, my skill issue
