### ISSUE TITLE
Incorrect mouse position when being on clickable buttons on JetBrains IDE (HiDPI)

### ISSUE THREAD

**Issue by lluisaliano** [hyprwm/Hyprland#4888]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: ultraluxor
Release: 6.7.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 23 Feb 2024 16:31:48 +0000


GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-P [Iris Xe Graphics] [8086:a7a0] (rev 04) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
plugins:
```

</details>

### Bug or Regression?

Bug

### Description

The mouse position is incorrect when trying to click on the IDE buttons. It makes you to lose focus on the window and makes it really difficult to click on them.

### How to reproduce

Open any jetbrains IDE and try to touch any button (if they are on corners it is easier to reproduce)
I have the following settings and I am using a HiDPI Display:
env = QT_QPA_PLATFORM=wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION=1
env = QT_QPA_PLATFORMTHEME=qt5c
env = GDK_BACKEND=wayland,x11
env = SDL_VIDEODRIVER=wayland
env = CLUTTER_BACKEND=wayland
env = XDG_CURRENT_DESKTOP=Hyprland
env = XDG_SESSION_TYPE=wayland
env = XDG_SESSION_DESKTOP=Hyprland

env = GDK_SCALE,2
env = QT_ENABLE_HIGHDPI_SCALING,1
env = QT_AUTO_SCREEN_SCALE_FACTOR=1

xwayland {
  force_zero_scaling = true
}

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/21333617/91d49066-e5d6-4077-8e56-a8466a2c1874

**Comment by ravarage** [comment]
update hyrpland and hyprland portal, I had same issue before, it got fixed later, current git is stable install the latest and this problem should be solved

**Comment by ravarage** [comment]
Try to remove those env setting, I am using goland and the only issue I have the search and replace windows close instantly, other than that everything is perfect

**Comment by lluisaliano** [comment]
With no env settings it loses the resolution and the problem is still happening. I can reproduce it in my other setup without HiDPI, It happens less but I can still see it.

**Comment by Sasikuttan2163** [comment]
I also have the same issue but haven't found a fix so far

**Comment by ravarage** [comment]
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORM,wayland
env = WLR_NO_HARDWARE_CURSORS,1
env = XDG_SESSION_TYPE,wayland

Try updating your environment; it is most likely your configuration. I am using jetbrain daily, and do have nvidia gpu, as far as I know not all app play well with hidpi but jetbrain run with no issue for me

**Comment by lluisaliano** [comment]
I am using the latest version and I am still seeing it. I can send you my whole config but using only the envs you sent did not work for me. I am using integrated gpu

**Comment by EmKaCe** [comment]
I had that issue using the right toolbar icons.

What fixed it for me was
`windowrulev2 = stayfocused,class:^(jetbrains-.*)`

**Comment by lluisaliano** [comment]
Works perfectly now. Thank you.

**Comment by AbdoMahfoz** [comment]
For anyone else having this issue, `stayfocused` prohibits you from using any other apps on the same workspace as rider. A solution that fixes this bug, while still allowing you to use other apps in the same workspace, is to use `noinitialfocus`.
`windowrulev2 = noinitialfocus,class:^(jetbrains-.*)`
