### ISSUE TITLE
After 0.36, nothing can make hyprland focuses on windows

### ISSUE THREAD

**Issue by loegaire** [hyprwm/Hyprland#5185]
this just happens immediately after I updated, clicking, keybinds, nothing can make hyprland focus on ANY windows. Running on Arch Linux, hyprland pacman version

**Comment by vaxerski** [comment]
please follow the template.

Additionally, perform a `git bisect`

**Comment by tchofy** [comment]
I wonder if they have an error in the config somewhere that wasn't being caught by pre-hyprlang that is being caught now...posting your hyprland.conf could help as well.

**Comment by loegaire** [comment]
> please follow the template.
> 
> Additionally, perform a `git bisect`

which template may I ask?

**Comment by loegaire** [comment]
> I wonder if they have an error in the config somewhere that wasn't being caught by pre-hyprlang that is being caught now...posting your hyprland.conf could help as well.
yes, will do

**Comment by loegaire** [comment]
> I wonder if they have an error in the config somewhere that wasn't being caught by pre-hyprlang that is being caught now...posting your hyprland.conf could help as well.

`#
# Please note not all available settings / options are set here.
# For a full list, see the wiki
# 

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1,highres,0x0,1

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
exec-once = waybar & hyprpaper & mako & /usr/lib64/libexec/polkit-kde-authentication-agent-1
exec-once = udiskie &
exec-once = fcitx5
exec-once = hyprctl setcursor Bibata-Modern-Pink 24
exec-once = kitty -e starteww
# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

# Some default env vars.
env = XCURSOR_SIZE,24
$w1 = hyprctl hyprpaper wallpaper "eDP-1,~/Downloads/whv4.png" 
$w2 = hyprctl hyprpaper wallpaper "eDP-1,~/Downloads/whv3.png" 
$w3 = hyprctl hyprpaper wallpaper "eDP-1,~/Downloads/whv1.jpg" 
#yes use quotes around desired monitor and wallpaper
#... continued with desired amount

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 2
    gaps_out = 0
    border_size = 2
    col.active_border = rgba(32e338ee) rgba(d1539fee) 45deg
    col.inactive_border = rgba(32e338ee) rgba(d1539fee) 45deg
    resize_on_border = true
    hover_icon_on_border = true
    layout = dwindle
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 7
    
    blur {
        enabled = true
        size = 5
        passes = 2
    }
    active_opacity = 1
    inactive_opacity = 0.88
    drop_shadow = yes
    shadow_range = 10
    shadow_render_power = 2
    col.shadow = rgba(1a1a1a66)
}

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = true
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = off
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
#device:epic-mouse-v1 {
 #   sensitivity = -0.5
#}

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more


# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, Q, exec, kitty
bind = $mainMod, C, killactive, 
bind = $mainMod, M, exit, 
bind = $mainMod, E, exec, dolphin
bind = $mainMod, V, togglefloating, 
bind = $mainMod, R, exec, wofi --show drun
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, D, exec, tofi
bind = $mainMod, J, togglesplit, # dwindle
#toggle waybar
bind = $mainMod SHIFT, W, exec, killall waybar || waybar
# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 1, exec, $w1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 2, exec, $w2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 3, exec, $w3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
#screenshot
bind = $mainMod, Print, exec, grim -g "$(slurp)"
#shutdown
bind = $mainMod CTRL, T, exec, shutdown -h now
#exit
bind = $mainMod CTRL, Q, exec, hyprctl dispatch exit
#suspend
bind = $mainMod CTRL, S, exec, systemctl suspend
bind = $mainMod, F, togglefloating 
#volume
#bind = Fn, F3, exec, pactl set-sink-volume 0 +5%
#bind = Fn, F2, exec, pactl set-sink-volume 0 -5%
bind = $mainMod, F3, exec, pactl set-sink-volume 0 +5%
bind = $mainMod, F2, exec, pactl set-sink-volume 0 -5%
#misc
misc {
   disable_hyprland_logo = true
   disable_splash_rendering = true
}
`

**Comment by fatihmete** [comment]
Up. In my case I have to move cursor to focus the floating window (especially rofi) I downgraded to version 0.35, problem was fixed.

**Comment by vaxerski** [comment]
if it's just rofi, that's a dupe of #5142

**Comment by 3l0w** [comment]
After a bisect the commit d72ea5f2a7fdb0d0a7bf914412327195b05199b0 introduce the change.
As said in https://github.com/hyprwm/Hyprland/issues/5142#issuecomment-2002525918 i will be not fixed since its xwayland shenanigans.
So i suggest you to use a wayland-compatible rofi like https://github.com/lbonn/rofi

**Comment by loegaire** [comment]
my issue is not related to rofi, I just can't focus on ANY window

**Comment by 3l0w** [comment]
> my issue is not related to rofi, I just can't focus on ANY window

You should try to do a git bisect or find a way for anyone to replicate this issue

**Comment by loegaire** [comment]
> > my issue is not related to rofi, I just can't focus on ANY window
> 
> You should try to do a git bisect or find a way for anyone to replicate this issue

can you give me some directions?, I think the issue has to do with my unique setup that's hard to replicate

**Comment by 3l0w** [comment]
> > > my issue is not related to rofi, I just can't focus on ANY window
> > 
> > 
> > You should try to do a git bisect or find a way for anyone to replicate this issue
> 
> can you give me some directions?, I think the issue has to do with my unique setup that's hard to replicate

You need to first clone Hyprland and start a git bisect from HEAD to v0.35.0 and then compile it and test

**Comment by svalbardsleeperdistrict** [comment]
I've gone through the 0.73 changelog and Ctrl+Fd for 'focus' and 'float', finding many references to changes related to focus, but I've no idea if any of these have something to do with this new behaviour. Having little more than zero experience with Hyprland, it is difficult to know what many of these exactly mean:

"input: avoid rampant refocuses on popups"
"xwayland: ignore OR activate requests if surface doesn't want focus"
"keybinds: focus floating on top of fs"
"leave special on focus"
"add forcenofocus prop"

**Comment by lisuke** [comment]
https://github.com/hyprwm/Hyprland/assets/10797357/6a27edd6-4794-494c-bc14-8f0899e8acc8


like this?

**Comment by lisuke** [comment]
> bug.mp4
> 
> like this?

Switching windows when there are both tiled and floating windows within a workspace can trigger a bug.

**Comment by lisuke** [comment]
This bug seems to be caused by another bug. For now, it is recommended to reverse the commit and continue to monitor it.

**Comment by lisuke** [comment]
dup of https://github.com/hyprwm/Hyprland/issues/5185#issuecomment-2053657328 ?
try https://github.com/hyprwm/Hyprland/pull/5598

**Comment by imalder** [comment]
I locked my version on 0.36 for the exact same reason. I will give a try at bisecting it myself.

**Comment by imalder** [comment]
> I locked my version on 0.36 because of that exact same issue. I will give a try at bisecting it myself.

I can confirm that the issue is rampant on my system on 0.37.1, which apparently many distros are considering to be the latest stable (at least that's gentoo's case). Same result when using gentoo packaging or building from source myself.

I wasn't able to reproduce the issue as consistently on >= 38.0 and I ran with 0.39.0 just fine for the entire day.
I still sometimes have focus issues but that's honestly very hard to reproduce and way less frequent.

I didn't go through a full bisect eventually as upgrading mostly solved my problem.

I don't know which version you guys are running, this may also be your problem. Give upgrading a try.

**Comment by NgoHuy** [comment]
> > I locked my version on 0.36 because of that exact same issue. I will give a try at bisecting it myself.
> 
> I can confirm that the issue is rampant on my system on 0.37.1, which apparently many distros are considering to be the latest stable (at least that's gentoo's case). Same result when using gentoo packaging or building from source myself.
> 
> I wasn't able to reproduce the issue as consistently on >= 38.0 and I ran with 0.39.0 just fine for the entire day. I still sometimes have focus issues but that's honestly very hard to reproduce and way less frequent.
> 
> I didn't go through a full bisect eventually as upgrading mostly solved my problem.
> 
> I don't know which version you guys are running, this may also be your problem. Give upgrading a try.

I run with 0.39.1 and have problem. I lost focus when I switched to other application. I need to switch to other application again. It happened recently, I'm not sure a root cause.

**Comment by vaxerski** [comment]
that's fixed in git and there are like 10 dupes already.

**Comment by intropedro** [comment]
I run with 0.39.1 and have problem too.

``` shell
❯ hyprctl version
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460
```

**Comment by kito30** [comment]
Sometimes Hyprland not focus windows after switch it, I have to switch back and forth until it focus on that screen.

**Comment by vaxerski** [comment]
that. is. fixed. in. git.

**Comment by NgoHuy** [comment]
I confirmed it's fixed in git. hope that new release soon. With git, waybar cannot show space number...

**Comment by Aman9das** [comment]
`ln -s $XDG_RUNTIME_DIR/hypr /tmp/hypr` fixes waybar issue

**Comment by izmyname** [comment]
Is this still a thing?

**Comment by NgoHuy** [comment]
when notification appeared from dunst, I cannot click to ghostty, must change to another windows and back...not sure why.

**Comment by MightyPlaza** [comment]
> when notification appeared from dunst, I cannot click to ghostty, must change to another windows and back...not sure why.

this has likely been fixed on -git
