### ISSUE TITLE
Triggering the in-game interaction menu leads to mouse glitching

### ISSUE THREAD

**Issue by Neburski** [hyprwm/Hyprland#5413]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 3875679755014997776e091ff8903acfb311dd2f  (props: bump ver to 0.38.0).
Date: Mon Apr 1 18:30:37 2024
Tag: v0.38.0

flags: (if any)


System Information:
System name: Linux
Node name: nebula
Release: 6.8.2-arch2-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD102 [GeForce RTX 4090] [10de:2684] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

- Holding and pressing the f-key + pressing the left mouse button leads to the mouse glitching downwards & left (character looks down and turn to the left), see video below.
- Holding and pressing the f-key + pressing the right mouse button leads to the mouse glitching downwards & right, see video below.
- However, when slightly moving the mouse while doing the same 'press + hold-down f + click left mouse button', does _not_ lead to the 'mouse glitching'. This is not shown in the video below.

Tested versions of hyprland:
* The following versions worked fine: 0.33, 0.34, and 0.35. 
* The following versions have the glitchy behaviour: 0.37 and 0.38 (I believe 0.37 introduced hyprcursor to my system).

Star Citizen runs in wine-ge-8-25-x86_64. 

In Star Citizen, pressing the f-key changes the mouse interaction mode so that the player can interact with menus and objects in the game (normal behaviour is as if in first person shooter). The interaction mode is an essential system in the game.

_Some speculation from my side:_ It appears as if an incorrect mouse movement direction is used when under these conditions.

However, I'm not certain how to troubleshoot / debug this to obtain better information.

### How to reproduce

1. Ensure hyprland 0.37 or 0.38 is installed
2. Start Star Citizen, once enter into the persistent universe
3. Failure issue 1: press + hold f + click left mouse button -> character will look down and turns left
4. Failure issue 2: press + hold f + click right mouse button will open the interaction menu, the mouse will instantly go to the lower right corner of the screen.

**Comment by Neburski** [comment]
My video didn't get added to the original post.


https://github.com/hyprwm/Hyprland/assets/13607845/858d22ed-9479-4ed2-b43d-4bdd4c99218e

**Comment by Neburski** [comment]
Today, I had some time for git-bisect.

The commit which introduced the glitching mouse behaviour is: 7a76ab01d16cdeb3bbb11449476d2b8ad84a3fda

**Comment by Neburski** [comment]
As a test, I commented out the line which leads to the glitching behaviour on hyprland v0.38.1, i.e., https://github.com/hyprwm/Hyprland/blob/89f775aec20fad9d0fec27bd61139d5e3b0f5c6a/src/managers/input/InputManager.cpp#L161

This stops the glitchy mouse behaviour. 

Obviously, that is not the good way to resolve the issue, however, it is not fully clear to me what that function is supposed to do or why it is needed. The documentation for that function isn't helpful to me as I'm not familiar with wlroots nor wayland programming.
https://wayland.emersion.fr/wlroots/wlr/types/wlr_seat.h.html#func-wlr_seat_pointer_send_motion

> void wlr_seat_pointer_send_motion(​struct [wlr_seat](https://wayland.emersion.fr/wlroots/wlr/types/wlr_seat.h.html#struct-wlr_seat) *wlr_seat, uint32_t time_msec, double sx, double sy);
> 
> Send a motion event to the surface with pointer focus. Coordinates for the motion event are surface-local. This function does not respect pointer grabs: you probably want [wlr_seat_pointer_notify_motion()](https://wayland.emersion.fr/wlroots/wlr/types/wlr_seat.h.html#func-wlr_seat_pointer_notify_motion) instead.

From some debugging and adding some debug logging of the following block of code:
https://github.com/hyprwm/Hyprland/blob/89f775aec20fad9d0fec27bd61139d5e3b0f5c6a/src/managers/input/InputManager.cpp#L155-L161

For my conditions, i.e., in-game, I notice that the BOX coordinates are always (0, 0) which leads to CLOSEST & CLOSESTLOCAL being identical.

https://github.com/hyprwm/Hyprland/blob/89f775aec20fad9d0fec27bd61139d5e3b0f5c6a/src/managers/input/InputManager.cpp#L161
That line seems to add the value of the pointer location to the current pointer location, effectively doubling the pointer coordinates.  
That also seems to be in line with what I notice at the end of my video above, i.e., the cursor teleports to the bottom right corner.

**Comment by vaxerski** [comment]
> That line seems to add the value of the pointer location to the current pointer location, effectively doubling the pointer coordinates.

`wlr_seat_pointer_send_motion` doesn't add, it sets, wdym double?

**Comment by Neburski** [comment]
> wlr_seat_pointer_send_motion doesn't add, it sets, wdym double?

I mean that the coordinates of my pointer seem to be somehow doubled when trying to use the in-game interaction menu.

The steps I do during debugging which trigger the issue:
1. My viewpoint in first person is at the center of my screen
2. I press and hold 'F' without moving the mouse -> I'm thus still looking at the center of my screen. 
3. While still holding 'F' + clicking a mouse button (L or R, both show the issue) makes my cursor instantly move downwards. In particular, when clicking the right mouse button, the cursor shows up at the right bottom, for the left mouse button, It's not clear what happens as it looks like I rotate left while looking down.

I added some logging to both Hyprland around https://github.com/hyprwm/Hyprland/blob/89f775aec20fad9d0fec27bd61139d5e3b0f5c6a/src/managers/input/InputManager.cpp#L161 and to wlroots around https://github.com/swaywm/wlroots/blob/0855cdacb2eeeff35849e2e9c4db0aa996d78d10/types/seat/wlr_seat_pointer.c#L233-L248 

Screenshot of the 'debug' lines I added, Hyprland on the left and wlroots on the right:
![2024-04-08-code_logging](https://github.com/hyprwm/Hyprland/assets/13607845/0462f126-149a-42c4-826f-fa75014e18a7)

From the logs, it appears that my pointer coordinates somehow indeed end up at the lower right corner of my screen.

I believe this is the moment in the logs when I'm pressing 'F' and it seems to create a new mouse constraint and setup a surface? 
When entering the lines of code where I put my debugging -> the cursor location is at (5119, 1439) which is the right bottom of my screen, yet, I did not mouse my mouse there at all.
> [wlr] [types/wlr_pointer_constraints_v1.c:278] new confined_pointer 0x5c0c2ec61b70 (res 0x5c0c2eae4350)
> [LOG] New mouse constraint at 5c0c2ec61b70
> [LOG] Registered signal for owner 5c0c2ebc7810: 5c0c2ec61c30 -> 5c0c2ebc78d8 (owner: CConstraint)
> [LOG] Registered signal for owner 5c0c2ebc7810: 5c0c2ec61c40 -> 5c0c2ebc7870 (owner: CConstraint)
> [wlr] [types/wlr_pointer_constraints_v1.c:378] constrained 0x5c0c2ec61b70
> [LOG] cursorImage request: surface 5c0c2eb84ea0
> [LOG] Registered signal for owner 5c0c2eaad550: 5c0c2eb851b8 -> 5c0c2eaad598 (owner: CWLSurface)
> [LOG] Registered signal for owner 5c0c2eaad550: 5c0c2eb85178 -> 5c0c2eaad600 (owner: CWLSurface)
> [LOG] CWLSurface 5c0c2eaad550 called init()
> [wlr] [types/output/cursor.c:371] Falling back to software cursor on output 'WL-1'
> [wlr] [types/output/cursor.c:371] Falling back to software cursor on output 'WL-1'
> [wlr] [/home/neburski/code/Hyprland/src/managers/input/InputManager.cpp:160] HL 1 -> CLOSEST: (5119.000000, 1439.000000); CLOSESTLOCAL: (5119.000000, 1439.000000); BOX: (0.000000, 0.000000); SCALED: 1.000000
> [wlr] [/home/neburski/code/Hyprland/src/managers/input/InputManager.cpp:174] HL 2 -> CLOSEST: (5119.000000, 1439.000000); CLOSESTLOCAL: (5119.000000, 1439.000000); BOX: (0.000000, 0.000000); SCALED: 1.000000
> [wlr] [types/seat/wlr_seat_pointer.c:248] WLR -> (sx, sy) = (5119.000000, 1439.000000); (sx_fixed, sy_fixed) = (1310464, 368384); 
> [wlr] [types/seat/wlr_seat_pointer.c:255] WLR NEQ -> (ptr_state.sx, ptr_state.sy) = (688896, 135680); (sx_fixed, sy_fixed) = (1310464, 368384); 
> [wlr] [/home/neburski/code/Hyprland/src/managers/input/InputManager.cpp:160] HL 1 -> CLOSEST: (5119.000000, 1439.000000); CLOSESTLOCAL: (5119.000000, 1439.000000); BOX: (0.000000, 0.000000); SCALED: 1.000000
> [wlr] [/home/neburski/code/Hyprland/src/managers/input/InputManager.cpp:174] HL 2 -> CLOSEST: (5119.000000, 1439.000000); CLOSESTLOCAL: (5119.000000, 1439.000000); BOX: (0.000000, 0.000000); SCALED: 1.000000
> [wlr] [types/seat/wlr_seat_pointer.c:248] WLR -> (sx, sy) = (5119.000000, 1439.000000); (sx_fixed, sy_fixed) = (1310464, 368384); 

Apologies, I'm not familiar with Hyprland, wlroots, not wayland terminology and code, so I'm mostly trying  to figure things out in the hopes to find the root cause.

**Comment by FredM7** [comment]
Having the same experience here on my side 🤔

**Comment by vaxerski** [comment]
can you print the region extents

**Comment by FredM7** [comment]
I'm a super-noob when it comes to these things 😅 and I don't know how to go about printing the `region extents`, sorry. 

However if you or someone can give me information, a link, anything; on how to do that, I'll gladly try to get the region extents, I just need to know/figure out how.

**Comment by vaxerski** [comment]
CRegion has an `extents` method which returns a CBox of which you can print `x,y,w,h`

**Comment by FredM7** [comment]
I'm not familiar with C++. At the moment that does not mean much to me, I don't know how to even begin to add that code - sorry. But I'm willing to help out if I have more knowledge about this.

I use NixOS, so I was able to confirm that if I comment out this line of code, the issue in my game disappears, and I can play (Star Citizen) normally without the cursor jumping to the bottom-right corner when I open the "focus/thought" using "F" and click.

![image](https://github.com/hyprwm/Hyprland/assets/12495374/cb4c1edc-5bd3-46f4-8685-da625ca038ba)

I created a patch using `git diff > wlr_seat_pointer_send_motion_comment.patch`. 

I applied the patch:
```
    overlays = [
       (final: prev: {
        hyprland = prev.hyprland.overrideAttrs (o: {
          patches = (o.patches or [ ]) ++ [
            ./wlr_seat_pointer_send_motion_comment.patch
          ];
        });
      })
    ];
```

And now I can play without issues. I also don't notice any negative effects of removing this line of code - everything appears to continue to work as expected without it.

My issues is resolved because of my patch, but I would like to be able to give more information to be able to assist in resolving these issues.

**Comment by Neburski** [comment]
My c++ knowledge is very rusty (rather lost to time), so I got the extents just before printing as follows:

```            
auto ss = CWLSurface::surfaceFromWlr(g_pCompositor->m_pLastFocus);
auto cc = ss->constraint();
auto ll = cc->logicConstraintRegion();
auto bb = ll.getExtents();
```

I created some logs where I also print the `bb.x, bb.y, bb.w, bb.h` as requested. 
The logs have been made using `tail -f /tmp/hypr/..../hyprlandd.log' to be able to see the log populate in real time. Besides the full log, each one of the other logs was created by restarting the 'tail -f ...' command just before initiation an action to create logs for each action separately.

The following logs are attached:
1. `2024-04-13_hyprlandd.log` is the full log
2. `2024-04-13_press_f.log` only pressing  the `F` key, no other action was done beside the pressing `F`.
3. `2024-04-13_press_f_and_LMB.log` pressing  the `F` key followed by pressing the left mouse button.
4. `2024-04-13_press_f_and_RMB.log` pressing  the `F` key followed by pressing the right mouse button. 
 
[2024-04-13_press_f.log](https://github.com/hyprwm/Hyprland/files/14967118/2024-04-13_press_f.log)
[2024-04-13_press_f_and_LMB.log](https://github.com/hyprwm/Hyprland/files/14967119/2024-04-13_press_f_and_LMB.log)
[2024-04-13_press_f_and_RMB.log](https://github.com/hyprwm/Hyprland/files/14967120/2024-04-13_press_f_and_RMB.log)
[2024-04-13_hyprlandd.log](https://github.com/hyprwm/Hyprland/files/14967121/2024-04-13_hyprlandd.log)

**Comment by Neburski** [comment]
This issue has disappeared since Hyprland 0.39.1.

Now there is another issue which seems to be similar as mentioned here: #5774, #5881, and #5895. It seems that in the latest Hyprland (0.40+) these issues have been fixed. 

Closing this issue.

**Comment by grar21** [comment]
Hi there, it appears this issue is actually still persisting. Any known resolution to fix?

**Comment by justinrubek** [comment]
I'm also experiencing this issue on [718afe2](https://github.com/hyprwm/Hyprland/commit/718afe271ecebfe6711453b9cfee90fa49a7e761), so it has not disappeared.

**Comment by Gameovernlp** [comment]
Same issue here. It probably reappeared for some or was never gone

**Comment by Tornado300** [comment]
same problem for me. Has anybody found a solution ?

**Comment by Tornado300** [comment]
@Neburski hey im sorry for the ping. I dont know if your fix still works but could you maybe explain how you did it ? im a noob and i dont know where i need to comment out that stuff. thanks

**Comment by Gameovernlp** [comment]
So I don't know how the original author fixed his problem. But I just switched to Gnome. It works perfectly over there. 
It isn't even close to being similar thou, so if you want something similar maybe search for a different desktop.

**Comment by FredM7** [comment]
Yes the issue still lives on. I have now switched to Arch recently. The offending line now lives here:
https://github.com/hyprwm/Hyprland/blob/c86db7bbb0cf14d4955ee3a4d13c0ed9f8a0e0ae/src/managers/input/InputManager.cpp#L220

Commenting this out locally and rebuilding/compiling again fixes it for me in Start Citizen.

**Comment by izdener** [comment]
This issue is still present.

**Comment by izmyname** [comment]
@Endermanbugzjfc  @izdener you need to open a discussion and leave a link to this issue there.

**Comment by dikkedimi** [comment]
I have this issue on bazzite with a 1070 ti.

everything else seems to be working smoothly, but this makes the game unplayable. Not complaining, just trying to find a solution and adding relevant info for others to find seemed like the kind thing to do.

Seems this issue is not hyprland related, but maybe wine or wayland related.

found [this](https://www.reddit.com/r/starcitizen/comments/1h7web9/comment/m0rx1p0/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button), maybe it's helpful

**Comment by terroreinhorn** [comment]
I have asked the LUG Discord Server for help. The link brings you to my question, the answer is the next message under it. This solved the problem for me. Sometimes I still have to quickly switch workspaces back and forth, then its fixed again.
https://discord.com/channels/539464400734519306/608349808956276737/1408383599450918932

**Comment by hashelq** [comment]
@Neburski may you reopen the issue?
