### ISSUE TITLE
New bugs

### ISSUE THREAD

**Issue by TAforever** [hyprwm/Hyprland#559]
I continue to actively test and here's what I found:
1. The program easyeffects in tiling mode draws drop-down menus with artifacts, in floating mode everything is fine.
2. In programs with their own cursor (retroarch) and games, a conflict of cursors occurs and either two cursors are drawn, system and game, or they are replaced alternately.
3. Also in the game starcraft remastered (proton xwayland), it happens that the true position of the cursor does not correspond to where it is drawn and, accordingly, it will not be possible to capture the controls, but after a while it passes.

**Comment by vaxerski** [comment]
> The program easyeffects in tiling mode draws drop-down menus with artifacts, in floating mode everything is fine.

Oh shiet this is a regression, could you tell me when that started?

> In programs with their own cursor (retroarch) and games, a conflict of cursors occurs and either two cursors are drawn, system and game, or they are replaced alternately.

Video pls?

> Also in the game starcraft remastered (proton xwayland), it happens that the true position of the cursor does not correspond to where it is drawn and, accordingly, it will not be possible to capture the controls, but after a while it passes.

Try running it through gamescope

**Comment by TAforever** [comment]
> 

idk I just recently started using Hyprland

**Comment by TAforever** [comment]
> > The program easyeffects in tiling mode draws drop-down menus with artifacts, in floating mode everything is fine.
> 
> Oh shiet this is a regression, could you tell me when that started?
> 
> > In programs with their own cursor (retroarch) and games, a conflict of cursors occurs and either two cursors are drawn, system and game, or they are replaced alternately.
> 
> Video pls?
> 
> > Also in the game starcraft remastered (proton xwayland), it happens that the true position of the cursor does not correspond to where it is drawn and, accordingly, it will not be possible to capture the controls, but after a while it passes.
> 
> Try runabout the video, apparently there is some kind of bug in wf-recorder, I can watch it, but I can’t play it on reddit and github
ning it through gamescope

**Comment by TAforever** [comment]
about the video, apparently there is some kind of bug in wf-recorder, I can watch it, but I can’t play it on reddit and github

**Comment by vaxerski** [comment]
> about the video, apparently there is some kind of bug in wf-recorder, I can watch it, but I can’t play it on reddit and github

why not use OBS? also, you can reencode it with ffmpeg, it's prolly some odd format

**Comment by TAforever** [comment]
gamescope I will try.

**Comment by TAforever** [comment]
ok., i will try with OBS.

**Comment by vaxerski** [comment]
number 1 fixed in ebe07c66567eae0f564288296f7d2f0f6b92e1f8

**Comment by TAforever** [comment]
here are 2 screenshots. if easyeffects is in tiling mode, then drop-down windows are drawn incorrectly, and if in fullscreen, then it's fine.
![screen-1661111489](https://user-images.githubusercontent.com/52626363/185808522-f7608560-0601-47fe-873b-292fe1727178.png)
![screen-1661111483](https://user-images.githubusercontent.com/52626363/185808524-c0734888-9aa2-440e-999d-25b219186dc1.png)

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/185808568-c4448b32-f618-4d10-996d-54f0359eb9a4.png)

dunno looks fine to me

**Comment by TAforever** [comment]
It’s also normal for me if it’s fullscreen, and if it’s just tiling, then it’s like in the screenshots.

**Comment by TAforever** [comment]
double cursor

https://user-images.githubusercontent.com/52626363/185808859-df88f69f-c257-46d2-b5ff-0b64d5c14b38.mp4

**Comment by vaxerski** [comment]
I only see one tho.

At any rate, it seems like an app bug rather than Hyprland. 

Does it work in sway or wayfire?

**Comment by TAforever** [comment]
only for some reason upside down and there is no second cursor on the record

**Comment by TAforever** [comment]
easyeffects first tiling, then fullscreen.

https://user-images.githubusercontent.com/52626363/185809076-1ba04326-fc9f-4c58-bf04-a28408668413.mp4

**Comment by TAforever** [comment]
> easyeffects first tiling, then fullscreen.
> 2022-08-21.23-09-17.mp4

wtf upside down again

**Comment by TAforever** [comment]
long story short, tomorrow I'll figure it all out and post normal screen recordings.

**Comment by TAforever** [comment]
Tested in sway and sway-git and did not find these problems, the ball is on the side of Hyprland

**Comment by TAforever** [comment]
In fullscreen, without artifacts, but not captured by the cursor, in tiling, it is captured by the cursor, but not correctly drawn.

https://user-images.githubusercontent.com/52626363/185811687-d6f9dc7d-4dd9-4e30-8c0d-358fb7cf1f34.mp4

**Comment by TAforever** [comment]
https://user-images.githubusercontent.com/52626363/185811700-aeec6915-4b29-487f-8048-5beadc11657f.mp4

**Comment by TAforever** [comment]
https://user-images.githubusercontent.com/52626363/185811705-780965f3-8eb7-4498-9786-cf231ace6b2b.mp4

**Comment by vaxerski** [comment]
for the double cursor - do you possibly use the cursor timeout option? Maybe that's the root of the bug.

Starcraft - no clue, try gamescope

Easyeffects - will see tomorrow.

**Comment by TAforever** [comment]
Yes, you are right, the problem was in the timeout. Problem number two is solved.

**Comment by frigaut** [comment]
For me the easyeffect issue is not solved (I have updated 3 hours ago, at `f273ebed9cab738b2f6000a73df7fad08a279c15`).
- easyeffects, and for that matter, gnome-control-panel, look bad/streched when tiled. Indeed they look ok when floating:

Tiled:
![image](https://user-images.githubusercontent.com/613346/185887994-f17a0fe6-9af6-4509-ba40-10812e4590d9.png)

Floating:
![image](https://user-images.githubusercontent.com/613346/185888118-a0d655a3-1781-47f4-8414-13b1506ead8a.png)

**Comment by frigaut** [comment]
Same stuff for gnome-control-center:

Tiled:
![image](https://user-images.githubusercontent.com/613346/185888627-cd48429c-bc26-4271-ba36-0716aab15d51.png)

Floating:
![image](https://user-images.githubusercontent.com/613346/185888755-72e5638b-8397-45a5-ae7c-f9cac4f516c4.png)

**Comment by frigaut** [comment]
Also, somehow, my org.gnome apps now open full screen, even though I do not have a single fullscreen rule in my hyprland config. This did not happen a week ago or so.

**Comment by vaxerski** [comment]
fixed the fullscreen issue

**Comment by vaxerski** [comment]
still, can't repro the easyeffects issue:
![image](https://user-images.githubusercontent.com/43317083/185890794-a7c783f0-7006-4c9d-a513-d13da9daf3ba.png)

**Comment by vaxerski** [comment]
@frigaut is this a regression? in that case a `git bisect` would be cool.

**Comment by frigaut** [comment]
Also, somehow, my org.gnome apps now open full screen, even though I do not have a single fullscreen rule in my hyprland config. This did not happen a week ago or so. 

> fixed the fullscreen issue

yes you did (at 21bea0fcb4401ea8588ea72cf51d75a8d2b85114).

**Comment by frigaut** [comment]
I'll try a bisect for the other issue.

**Comment by frigaut** [comment]
@vaxerski I've gone back to early august and this "streched" bug for gnome-control-center or easyeffects (gtk4?) apps is still there. In fact I am absolutely not sure this ever worked. I am use to open these particular apps in floating where the bug doesn't happen. 

I have attached my env in case it helps (you don't have this issue do you?).
[sasaigo_env.txt](https://github.com/hyprwm/Hyprland/files/9393728/sasaigo_env.txt)

```bash
$ hyprctl version
Hyprland, built from branch main at commit 21bea0fcb4401ea8588ea72cf51d75a8d2b85114dirty (typo).
flags: (if any)
```

**Comment by frigaut** [comment]
oohhh interesting.
I had recently de-install gnome (the arch meta package). If I re-install it, this solves the issue...

**Comment by frigaut** [comment]
I did unset it and it did not change anything.

**Comment by vaxerski** [comment]
> I had recently de-install gnome (the arch meta package)

what package?

**Comment by frigaut** [comment]
the meta package
```bash
sudo pacman -S gnome
```

**Comment by frigaut** [comment]
```bash
Packages (108) abseil-cpp-20220623.0-1  apache-2.4.54-1  appstream-0.15.4-1  brltty-6.5-2
               clutter-gst-3.0.27-4  colord-sane-1.4.6-1  djvulibre-3.5.28-3  dleyna-connector-dbus-0.4.1-1
               dleyna-core-0.7.0-3  dleyna-renderer-0.7.2-1  dleyna-server-0.7.2-1  dotconf-1.3-6
               evolution-data-server-3.44.4-1  folks-0.15.5-1  freerdp-2:2.8.0-1  gfbgraph-0.2.5-1
               gmime3-3.2.12-1  gnome-autoar-0.4.3-2  gnome-epub-thumbnailer-1.6-2  gom-0.4-5
               grilo-0.3.15-1  gtk-vnc-1.3.1-1  gtksourceview5-5.4.2-1  gupnp-av-0.14.1-1  libao-1.2.2-5
               libchamplain-0.12.20-3  libcheese-41.1-2  libdazzle-3.44.0-1  libdmapsharing-2.9.41-1
               libgdata-0.18.1-2  libgdm-42.0+r11+g4a52f026-1  libgepub-0.6.0-2  libgssglue-0.5-1
               liblouis-3.22.0-1  libmediaart-1.9.6-1  liboauth-1:1.0.3+r15+gac4cf3a-1
               libpackagekit-glib-1.2.5-1  libphonenumber-1:8.12.52-3  libportal-0.6-1
               libportal-gtk3-0.6-1  libspectre-0.2.10-1  libspeechd-0.11.1-3  libvirt-1:8.6.0-2
               libvirt-glib-4.0.0-2  mod_dnssd-0.6-8  python-atspi-2.38.2-1  speech-dispatcher-0.11.1-3
               telepathy-glib-0.24.2-2  yajl-2.1.0-5  baobab-42.0-1  cheese-41.1-2  eog-42.3-1
               epiphany-42.4-1  evince-42.3-1  file-roller-3.42.0-1  gdm-42.0+r11+g4a52f026-1  gedit-42.2-1
               gnome-backgrounds-42.0-1  gnome-books-40.0-1  gnome-boxes-42.3-1  gnome-calculator-42.2-1
               gnome-calendar-42.2-1  gnome-characters-42.0-1  gnome-clocks-42.0-1
               gnome-color-manager-3.36.0+r25+g4aab8b59-1  gnome-contacts-42.0-1
               gnome-control-center-42.3-2  gnome-disk-utility-42.0-1  gnome-font-viewer-42.0-1
               gnome-keyring-1:42.1-1  gnome-logs-42.0-1  gnome-maps-42.3-1  gnome-menus-3.36.0-2
               gnome-music-1:42.1-1  gnome-photos-1:42.0-1  gnome-remote-desktop-42.4-1
               gnome-session-42.0-1  gnome-settings-daemon-42.2-1  gnome-shell-1:42.4-1
               gnome-shell-extensions-42.3-1  gnome-software-42.4-1  gnome-system-monitor-42.0-1
               gnome-terminal-3.44.1-1  gnome-user-docs-42.0-1  gnome-user-share-3.34.0-2
               gnome-video-effects-0.5.0+4+g9554041-2  gnome-weather-42.0-1  grilo-plugins-1:0.3.15-1
               gvfs-1.50.2-1  gvfs-afc-1.50.2-1  gvfs-goa-1.50.2-1  gvfs-google-1.50.2-1
               gvfs-gphoto2-1.50.2-1  gvfs-mtp-1.50.2-1  gvfs-nfs-1.50.2-1  gvfs-smb-1.50.2-1
               malcontent-0.10.5-1  mutter-42.4-1  nautilus-42.2-1  orca-42.3-1  rygel-1:0.40.4-1
               simple-scan-42.1-1  sushi-42.0-1  totem-42.0-1  tracker3-miners-3.3.1-2
               vino-3.22.0+74+g7a95e10-1  xdg-user-dirs-gtk-0.10+9+g5b7efc6-3  yelp-42.1-2
```

**Comment by frigaut** [comment]
freaking gnome

**Comment by vaxerski** [comment]
```
vaxry@Arch  ~  yay -Q | grep gnome
gnome-keyring 1:42.1-1
libgnomekbd 1:3.28.0-1
 vaxry@Arch  ~  yay -Q | grep gtk  
breeze-gtk 5.25.4-1
clutter-gtk 1.8.4-3
deluge-gtk 1:2.1.1-1
fcitx5-gtk 5.0.16-1
gtk 1.2.10-18
gtk-chtheme 0.3.1-10
gtk-doc 1.33.2-1
gtk-layer-shell 0.7.0-3
gtk-update-icon-cache 1:4.6.7-1
gtk-vnc 1.3.1-1
gtk2 2.24.33-2
gtk3 1:3.24.34-1
gtk4 1:4.6.7-1
gtkglext 1.2.0-13
gtkmm 1:2.24.5-4
gtkmm3 3.24.6-1
gtksourceview4 4.8.3-1
gtksourceview5 5.4.2-1
kde-gtk-config 5.25.4-1
lib32-gtk2 2.24.33-1
lib32-gtk3 3.24.34-1
lib32-libappindicator-gtk2 12.10.0-13
lib32-libdbusmenu-gtk2 16.04.0-5
lib32-libindicator-gtk2 12.10.1-9
libappindicator-gtk3 12.10.0.r296-2
libdbusmenu-gtk2 16.04.0-5
libdbusmenu-gtk3 16.04.0-5
libindicator-gtk2 12.10.1-10
libindicator-gtk3 12.10.1-10
qemu-ui-gtk 7.0.0-12
spice-gtk 0.41-2
webkit2gtk 2.36.6-1
webkit2gtk-4.1 2.36.6-1
wxwidgets-gtk3 3.2.0-4
xdg-desktop-portal-gtk 1.14.0-1
 vaxry@Arch  ~  yay -Q | grep gdk
gdk-pixbuf2 2.42.9-1
lib32-gdk-pixbuf2 2.42.9-1
 vaxry@Arch  ~  
 ```

**Comment by vaxerski** [comment]
man i need to clean a bunch of those

**Comment by frigaut** [comment]
OK forget it for now. I need to run more tests.

**Comment by frigaut** [comment]
Apparently it's got to do with some more complex monitor/geometry stuff that might explain why you don't see that. 
Look at the following:

In this geometry, things look GOOD:
![screenshot_20220822_211602](https://user-images.githubusercontent.com/613346/185909429-7d335911-a720-4bd7-8399-1d5fedf1869c.jpg)

Here too:
![screenshot_20220822_211641](https://user-images.githubusercontent.com/613346/185909474-9ddf6314-490e-4e28-b1ab-00e1ae4b58b4.png)

But not here:
![screenshot_20220822_211632](https://user-images.githubusercontent.com/613346/185909525-ca718525-bde6-4326-8563-5c1c2012a60e.png)

**Comment by vaxerski** [comment]
only happens to me when the window is REALLY small:

![image](https://user-images.githubusercontent.com/43317083/185912745-7df87c1c-25c6-4eb3-a176-6ca9d430e29a.png)

unfortunately it seems like yet another issue with oversized surfaces.

**Comment by TAforever** [comment]
To reproduce the problem with easyeffects, try setting the minimum gaps value. Regarding starcraft, I understand that this is not a priority, but try to look in your free time. I have tested in other wayland composers (kwin, mutter, sway) and they don't have this problem. If needed, I can provide a portproton debug log. And today I found

https://user-images.githubusercontent.com/52626363/185918753-b92c9dc7-c38b-46b5-b65a-6e6ec527e396.mp4

 such a problem in Telegram.

**Comment by TAforever** [comment]
Yes, I also forgot to say that there is no such problem with gamescope, but in other composers it works fine out of the box. Also, to test starcraft, I can give the password from the battle.net account.

**Comment by vaxerski** [comment]
don't lmao

Just use gamescope for now, Hyprland does have a few bugs with proton games, yes.

**Comment by TAforever** [comment]
> telegram issue was prolly fixed in [d0ec2b7](https://github.com/hyprwm/Hyprland/commit/d0ec2b72aec8a91a904b7678ab093e648bd59cf2)

just tested and the problem still exists, I don't know why.

**Comment by TAforever** [comment]
https://user-images.githubusercontent.com/52626363/185939992-0d1adc76-942a-4165-a861-25432bd72a93.mp4

**Comment by dragove** [comment]
The telegram bug is randomly happening. At most time, it happens.

**Comment by Heisfer** [comment]
I think the telegram issue can be resolved by env QT_AUTO_SCREEN_SCALE_FACTOR=1 
source: https://wiki.archlinux.org/title/HiDPI#Qt_5
But in sway it works just fine?

**Comment by TAforever** [comment]
Decided to try hl today and it impressed me. What a great job done! I am happy to announce that the bug with telegram and starcraft has been fixed! There was only a bug with Easyeffects. I figured out why you couldn't reproduce it: I noticed that on your screenshots you have minimize and maximize buttons, even though by default there is only a close button. Remove extra buttons and you will reproduce this bug exactly. Also thanks for adding the feature to add and remove windows in the Master area in the Master Layout.

**Comment by dragove** [comment]
The telegram issue is fixed in `0.21.0beta` version. 
The bug in easyeffects is not a big problem but cause some drawing issue in float mode.

[output.webm](https://user-images.githubusercontent.com/24190403/215339174-286b0ec6-865a-4f53-a751-eeab4f16d79b.webm)

**Comment by TAforever** [comment]
Today I compiled hyprland-git and I can say that all the bugs have been fixed. Well done.
