### ISSUE TITLE
foot's glitched scrollbar

### ISSUE THREAD

**Issue by bvr-yr** [hyprwm/Hyprland#5610]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 79a139c9495568f69dd995bce1ca579247a98a17  (flake.lock: update).
Date: Mon Apr 15 23:57:27 2024
Tag: v0.39.0-12-g79a139c9, commits: 4456

flags: (if any)


System Information:
System name: Linux
Node name: Arch-ASUS
Release: 6.6.27-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Sat, 13 Apr 2024 11:50:59 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller [8086:0416] (rev 06) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hyprexpo by Vaxry ver 1.0
```

</details>

### Bug or Regression?

Bug

### Description

see https://github.com/hyprwm/Hyprland/discussions/4858#discussioncomment-8610673 for video

scrollbar indicator (as well as URL-labels when shown, `Ctrl+o` in default foot conf) seems to be treated specially. as, you won't believe, it is affected by Hyprland's `rounding` setting. which shouldn't happen I suppose

maybe this could help to investigate the root cause

as mentioned in discussion, `force_introspection = 1` eliminates glitches for me, but it's likely a strange coincidence on my end

### How to reproduce

to properly reproduce you need `pad` value to be greater than default 0 and probably some larger font size than default 8

try launching
```sh
foot --config=/dev/null --override=pad=8x8
```

and zoom with `Ctrl+=` or `Ctrl+MouseUp`

then just print some long stuff and scroll

**Comment by vaxerski** [comment]
the scrollbar really shouldnt be a subsurface...

**Comment by BeyondMagic** [comment]
Can replicate.

**Comment by bvr-yr** [comment]
> the scrollbar really shouldnt be a subsurface...

report upstream? I'm afraid the answer might be like "Hyprland problem, it works in sway"

**Comment by 1player** [comment]
Good for tracking it down to the `pad` setting. I can replicate as well, and here's my config:

```
[main]
font=PragmataPro Mono:size=13
pad=4x4 center
```

**Comment by NikkSaan** [comment]
I noticed the glitch disappeared for the windows in which I set a theme with [theme.sh](https://github.com/lemnos/theme.sh). But that causes foot to have a slightly higher cpu usage. I don't know If this observation will help you guys debug the problem, but It might serve a temporary fix for some.

---
hyprland v37.1, foot v1.16.1 -pgo +ime +graphemes -assertions

**Comment by VehementHam** [comment]
I am experiecing glitched scrollbars.

**Comment by rtgiskard** [comment]
This seems to be fixed with latest hyprland, for me, it works well:

hyprland-git: v0.40.0-146-ga54ab301
foot -v: 1.17.2 +pgo +ime +graphemes -assertions

**Comment by bvr-yr** [comment]
nothing changed for me on 3fd6c1b30e5397432c4640286efaf52a6891f71c
foot version: 1.17.2-31-g0bf5a7e9 (May 24 2024, branch 'master') +pgo +ime +graphemes -assertions

@rtgiskard did u use extra padding and larger font?

**Comment by rtgiskard** [comment]
> nothing changed for me on [3fd6c1b](https://github.com/hyprwm/Hyprland/commit/3fd6c1b30e5397432c4640286efaf52a6891f71c) foot version: 1.17.2-31-g0bf5a7e9 (May 24 2024, branch 'master') +pgo +ime +graphemes -assertions
> 
> @rtgiskard did u use extra padding and larger font?

For me, the pad is always `pad=4x2`, I do have the same problem before, but not find any glitch recently, the foot version is v1.7.2 from archlinux official since 2024-04-21, and I switched to hyprland since 2024-05-01. The glitch is there for several days, then I just get used to it, and recently find no glitch at all. Both `a54ab301`, `dd274b72` works well for me.

**Comment by rtgiskard** [comment]
Well, it's still there, but for some case:

. open a foot window, run `tail -f /run/user/1000/hypr/*/hyprland.log`, then scroll up with mouse so that the scroll cursor is displayed
. open another window, move your mouse around (to generate more logs output for the above tail), you will see the scroll cursor get moved up with some lightly glitch (but much better)
. if just scroll in current foot window, I can't reproduce any glitch like what it was.

**Comment by bvr-yr** [comment]
some progress on 8412ffcc42012888757cd00a004871e8bc353cf2

now I can observe glitches only on tiled windows

**Comment by izmyname** [comment]
Still a thing? Foot's scrollbar renders fine for me on both tiled and non-tiled windows.

**Comment by Steven--** [comment]
I used to be affected from this bug but everything has been working fine for a while (if I had to guess since 0.42).

**Comment by izmyname** [comment]
Nice. I think this is solved.

**Comment by vaxerski** [comment]
closing then

**Comment by fxzzi** [comment]
Can confirm this issue does still happen for me. I'll open a new discussion.

**Comment by arc-d3v** [comment]
> Can confirm this issue does still happen for me. I'll open a new discussion.

Did you open the discussion? I tried to search but I don't see it. Can you link it?
