### ISSUE TITLE
Special workspace focus issues when `misc:initial_workspace_tracking` is enabled

### ISSUE THREAD

**Issue by tchofy** [hyprwm/Hyprland#5726]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit d119513749daf47b9061258a1974b34111ab8bb5  (renderer: fix safety around sendFrameEventsToWorkspace).
Date: Tue Apr 23 17:15:37 2024
Tag: v0.39.1-61-gd1195137, commits: 4521

flags: (if any)


System Information:
System name: Linux
Node name: eryth
Release: 6.8.7-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:00 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] [10de:1f91] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hyprexpo by Vaxry ver 1.0


```

</details>

### Bug or Regression?

Bug

### Description

As seen bellow, special workspace doesn't get initial focus when new windows are created until cursor is moved, and if try to spawn new windows on special workspace they'll spawn on the previous ws instead, but when trying to close the newly created window, the one on the special workspace gets closed instead.

### How to reproduce

Set a rule to spawn something on special ws
`workspace = special, on-created-empty:[tile] foot`
Toggle special workspace
Try to spawn new terminals

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/64620317/22fba07f-fe7c-404e-8fa5-00961c082b05

**Comment by vaxerski** [comment]
aw fucking fuck fuck fuck

**Comment by vaxerski** [comment]
this should be fixed with above, however foot runs in server mode by default so the terms spawning in the bg is because of the token

I should make the initial tokens more configurable like e.g. being one-shot

**Comment by Agent00Ming** [comment]
Still broken because the token pointing to a special workspace is reported as `special:special:name` format in Hyprland log

**Comment by tchofy** [comment]
After 34413d1 I couldn't open new windows on either special or previous workspace, after trying https://github.com/hyprwm/Hyprland/pull/5729 I could.
I can still reproduce the initial focus on the just-spawned foot for the special workspace issue, however.

**Comment by Agent00Ming** [comment]
The focus on latest spawned window behaviour is intended I believe as it has been the case for as long as I have used Hyprland

**Comment by The-Briel-Deal** [comment]
Do you mean if you spawn a window in special then it brings up special? That makes sense.

Thanks for the fix to the Agent! I've definitely ran into this before.

**Comment by tchofy** [comment]
No, I meant like, i toggle special workspace, foot is spawned, but it is not focused, like in the start of the video. Only happens on the first focus tho, to have it happen again I have to close foot and have the workspace rule spawn another one.

**Comment by Agent00Ming** [comment]
That's also been the default behaviour for a while. You keep focus on the workspace under the special workspace until you either: move your mouse or spawn a window on the special workspace

**Comment by tchofy** [comment]
Yes, but I have a workspace rule to spawn foot if special is empty, with `misc:initial_workspace_tracking` disabled then foot on the special workspace is focused as soon as it's spawned, but if `misc:initial_workspace_tracking` is disabled then the workspace under loses focus, but also the foot on special loses focus, so none of the windows are focused until I either move my mouse or spawn a new window.
I can provide a video if necessary, just need to tweak my configs to make it more noticeable.

**Comment by Agent00Ming** [comment]
Ok, seems like that's a workspace rule clashing with the token spawn system.
<details><summary> Token behaviour for 'on-created-empty:foot' workspace rule </summary>

```
[LOG] New window contains HL_INITIAL_WORKSPACE_TOKEN: 5fdb1151-c16d-42d2-b998-e693896d76cd
[LOG] HL_INITIAL_WORKSPACE_TOKEN 5fdb1151-c16d-42d2-b998-e693896d76cd -> 2
[LOG] New window contains HL_INITIAL_WORKSPACE_TOKEN: a08d4699-9d02-4b7e-83b0-7dd7aa4732d8
[LOG] HL_INITIAL_WORKSPACE_TOKEN a08d4699-9d02-4b7e-83b0-7dd7aa4732d8 -> 2
[LOG] New window contains HL_INITIAL_WORKSPACE_TOKEN: 75dd4616-678f-42a6-b935-e5db90831794
[LOG] HL_INITIAL_WORKSPACE_TOKEN 75dd4616-678f-42a6-b935-e5db90831794 -> 2
[LOG] New window contains HL_INITIAL_WORKSPACE_TOKEN: dde5772c-58c4-4b24-a5bd-e2486d3d36df
[LOG] HL_INITIAL_WORKSPACE_TOKEN dde5772c-58c4-4b24-a5bd-e2486d3d36df -> 2
[LOG] New window contains HL_INITIAL_WORKSPACE_TOKEN: 2c239782-e1b5-4566-8b2d-a87f826ff67c
[LOG] HL_INITIAL_WORKSPACE_TOKEN 2c239782-e1b5-4566-8b2d-a87f826ff67c -> 2
[LOG] New window contains HL_INITIAL_WORKSPACE_TOKEN: 7c82ad21-4f4b-4f30-a034-4df9810be0d6
[LOG] HL_INITIAL_WORKSPACE_TOKEN 7c82ad21-4f4b-4f30-a034-4df9810be0d6 -> 2
```

</details>
<details><summary> Token behaviour for manual spawn (with #5729) </summary>

```
[LOG] New window contains HL_INITIAL_WORKSPACE_TOKEN: dd38cccb-4005-4dd7-8496-3a38f1117dbe
[LOG] HL_INITIAL_WORKSPACE_TOKEN dd38cccb-4005-4dd7-8496-3a38f1117dbe -> special:scratchpad
[LOG] New window contains HL_INITIAL_WORKSPACE_TOKEN: 4134bf1f-1df1-4e75-9189-adbbbe77d3bf
[LOG] HL_INITIAL_WORKSPACE_TOKEN 4134bf1f-1df1-4e75-9189-adbbbe77d3bf -> special:scratchpad
[LOG] New window contains HL_INITIAL_WORKSPACE_TOKEN: 1445b336-a8a8-437d-85d2-1f75cd7e8c58
[LOG] HL_INITIAL_WORKSPACE_TOKEN 1445b336-a8a8-437d-85d2-1f75cd7e8c58 -> special:scratchpad
```

</details>

**Comment by zjeffer** [comment]
This issue is still happening for me. I haven't defined `misc:initial_workspace_tracking` so it's set to the default (1). The bug doesn't occur with it set to `0`.
