### ISSUE TITLE
mouse cursor isn't captured by some games (Satisfactory, Cyberpunk 2077)

### ISSUE THREAD

**Issue by Xanazf** [hyprwm/Hyprland#5992]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 0634aaeac6cca12e4f72174c431c2db9da9c0072  (renderer: remove border on fullscreen (5577)).
Date: Sun Apr 14 02:16:26 2024
Tag: v0.38.0-109-g0634aaea, commits: 4442

flags: (if any)


System Information:
System name: Linux
Node name: archdawg
Release: 6.8.9-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000


GPU information: 
08:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3070] [10de:2484] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

the FOV doesn't let me turn past the window borders, because when i move my camera in game, it also moves the cursor, and when it hits the window border - it also stops my camera

### How to reproduce

open first person Proton games

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/56270904/9dd4147b-8f0a-4da9-9153-c722b4bfd60b

**Comment by Kagukara** [comment]
Getting this issue on.
```
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606
```
When I'm using gamescope (I play almost all my games in gamescope) and switching to an other workspace and back with multi monitors, the cursor doesn't stay on the workspace with the game. I have to press escape to bring up a menu. Clicking the window when you're in 1st/3rd person doesn't work.

**Comment by antkss** [comment]
i

> for some reason when you click outside the border and then back in it fixes itself most of the time
> 
> and for me the bug only appears when your switching through workspaces (maybe windows too)

for sure, i am encounter these problems too, when i using angr management

**Comment by nadanke** [comment]
> for some reason when you click outside the border and then back in it fixes itself most of the time
> 
> and for me the bug only appears when your switching through workspaces (maybe windows too)

Lol for me it's the opposite: it works fine until I click outside the game once, then the game doesn't capture the mouse anymore. Happened to me with Nightmare Reaper and Deep Rock Galactic, both with Gamescope. Nightmare Reaper without Gamescope doesn't have this problem (haven't tested Deep Rock without Gamescope). In Plasma both work with Gamescope

**Comment by reinux** [comment]
Clicking out or in doesn't help for me running Starcraft 2 in Lutris. There's a mouse capture option in-game, but turning it on simply makes it impossible to move the window.

**Comment by Insprill** [comment]
Also happening in Modded Minecraft (Forge 1.12.2). Leaving and refocusing the window several times will usually fix it, until the game shows the cursor again - then the process repeats.

**Comment by Wawwior** [comment]
Happening in all games that capture mouse for me

**Comment by Kagukara** [comment]
For a temporary or even permanent fix, I've stuck with using v0.39.1. This version for me has all the mouse fixed with the games I play.

**Comment by stojanov** [comment]
Still present, cannot focus in game, either keyboard is not usable and/or mouse escaping onto other monitor when in game

**Comment by vaxerski** [comment]
Hello there!

This issue has been closed, as we are moving from issues to discussions. More about this can be found [here](https://wiki.hyprland.org/Contributing-and-Debugging/Issue-Guidelines/) and in #9854.

Firstly, please make sure this issue is still relevant in latest Hyprland. If so, we ask you to open a [discussion](https://github.com/hyprwm/Hyprland/discussions) (please read the discussion guidelines first, in the pinned post)

Thank you for your understanding!
