### ISSUE TITLE
Switching to window does not work anymore (neither with rofi nor wlr/taskbar)

### ISSUE THREAD

**Issue by LorenzoBettini** [hyprwm/Hyprland#6236]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: lg-eos-hyprland
Release: 6.9.1-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Wed, 22 May 2024 13:47:07 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2023.05.28"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/general-system/endeavouros-installation"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

When using `rofi -show window` (and selecting a window) or clicking on an icon on `wlr/taskbar`) the window in another workspace is not selected anymore. The workspace indicator on waybar correctly shows that the selected window is on another workspace (the workspace indicator changes its color), but nothing else happens.
Note that the window is not changed even when in the same workspace by using the two methods.

### How to reproduce

Either use the waybar module `wlr/taskbar` and select an application not currently focused or use `rofi-lbonn-wayland-git` and then select a window after running `rofi -show window`.

**Comment by vaxerski** [comment]
IIRC fixed in git, try on git

**Comment by donovanglover** [comment]
Tried with the latest commit https://github.com/hyprwm/Hyprland/commit/0ebb43c1a37e7321e5ed7223ea85ed555cc82735 and still broken with NixOS 24.05 + Ironbar 0.15.1 at https://github.com/JakeStanger/ironbar/commit/6edfe940000d1a54a92fb71dd6254909724f9307

**Comment by LorenzoBettini** [comment]
In Arch, I first removed `hyprland` and then installed the AUR git package

```
yay -S hyprland-git
```

And for me, that fixes both the taskbar and rofi window selection: I can switch to windows even in different workspaces, as I used to do.

**Comment by vaxerski** [comment]
I'd call this fixed then and say it's an ironbar issue
