### ISSUE TITLE
Feature: Having an alternativ for gaps_out that only adds gaps to left and right side 

### ISSUE THREAD

**Issue by goggi** [hyprwm/Hyprland#638]
Scenario:
I have 2 monitors. One of them is a ultra-wide screen monitor. 
To make life a bit easier when I only have 1 window open I want to add gaps to the right and left side for that specific monitor
I have this little script that could automate this for me:

```
#!/bin/sh
function handle {
  if [[ ${1:0:10} == "openwindow" || ${1:0:11} == "closewindow" ]] ; then
    CW=$(hyprctl -j monitors | jq '.[] | select(.name=="DP-3") | .activeWorkspace.id')
    WW=$(hyprctl -j workspaces | jq ".[] | select(.name==\"""${CW}""\") | .windows")
    if [[ $WW > 1 ]]; then 
      # hyprctl keyword general:gaps_out 30
      hyprctl keyword monitor DP-3,c,0,0,700,700 
    else 
      # hyprctl keyword general:gaps_out 100 
      hyprctl keyword monitor DP-3,addreserved,0,0,1000,1000
    fi
  fi
}
socat - UNIX-CONNECT:/tmp/hypr/$(echo $HYPRLAND_INSTANCE_SIGNATURE)/.socket2.sock | while read line; do handle $line; done
```

But using hyprctl keyword monitor is slow, blocking and breaks the flow of the animations.
When I tried the same thing with general:gaps_out it works super good, but it also adds gaps to bottom and top and effects both monitors which I would like to avoid.

Any possibility to get a version of gaps_out that only adds gaps to right and left, and also that only effects a specific monitor or workspace. Or if its possible to speed up addreserved?

Thanks!!!!!

**Comment by vaxerski** [comment]
wrap the script in a code block, this is unreadable

**Comment by vaxerski** [comment]
fixed, addreserved will now be speedy 

49a55f136e01c7fed071687becacea639226127a

**Comment by goggi** [comment]
thanks! It did make it a bit faster, but it still hangs the animations, not as fluid and smooth as the hyprctl keyword general:gaps_out command. 
I did play around with the source and was able to split top_bottom/left_right options into individual options and it works great. 

Is it hard to make the gaps unique per monitor?

**Comment by goggi** [comment]
Here you have two videos, one running addreserved, and other running gaps_out (modified version)
addreserved:
https://user-images.githubusercontent.com/1946339/189207026-09ef2ca0-d94a-4df7-a113-7203de21f241.mp4
gaps_out:
https://user-images.githubusercontent.com/1946339/189207136-494cceb0-bc78-48ad-b315-7f676824e95a.mp4

**Comment by vaxerski** [comment]
dunno if it's the recording software but both seem equally laggy.

**Comment by goggi** [comment]
dude ... you are right its the same video. here is the other one

https://user-images.githubusercontent.com/1946339/189208942-f8f9c45c-26ab-4a47-ae63-cc1d5909329d.mp4

**Comment by vaxerski** [comment]
do you have `misc:no_vfr` set to `false`? if so, try turning it to `true` and seeing if it fixes the issue.

**Comment by goggi** [comment]
unfortunately that didn't speed it up. So for you these two commands execute at the same speed:
hyprctl keyword monitor DP-3,addreserved,0,0,1200,1200
hyprctl keyword general:gaps_out 1200
?

**Comment by vaxerski** [comment]
yeap
