### ISSUE TITLE
movefocus keybind across monitors doesn't create a focusedmon event

### ISSUE THREAD

**Issue by lylac-1** [hyprwm/Hyprland#758]
![image](https://user-images.githubusercontent.com/102007132/193384113-266fea72-9b6c-4205-9d27-76d48f61f5e8.png)
in the attached image chromium to the right is on a different monitor to alacritty on the left listening to the socket
movefocus was used twice, to the left and then back to the right, where alacritty was the original focus.

the expected outcome is that a focusedmon event would also be made as a new monitor is being focused when the movefocus command is used to move focus to a window in another workspace on another monitor

hyprctl version output
`Hyprland, built from branch HEAD at commit e6c9e3f81dda723e289fa31883b326c086979c7ddirty (add case for empty strings in isNumber).
flags: (if any)
debug`

**Comment by vaxerski** [comment]
fixed in 590fbf808b60baceef3b021050dae4c409121bf5

**Comment by lylac-1** [comment]
issue persists.
`~ > hyprctl version
Hyprland, built from branch HEAD at commit a97621b1cb203b0e3a7dd07d88c5422b798cbfd8dirty (Added window swallowing).
flags: (if any)
debug`
