### ISSUE TITLE
Running on tty unknown after lock & dpms off

### ISSUE THREAD

**Issue by robtor-de** [hyprwm/Hyprland#7816]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 0f594732b063a90d44df8c5d402d658f27471dfe  (props: bump version to 0.43.0).
Date: Sun Sep 8 16:48:21 2024
Tag: v0.43.0, commits: 5196

flags: (if any)


System Information:
System name: Linux
Node name: PC-Robin
Release: 6.10.10-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000


GPU information: 
05:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116 [GeForce GTX 1660 SUPER] [10de:21c4] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  560.35.03  Fri Aug 16 21:39:15 UTC 2024


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/robtor/.config/hypr/hyprland.conf: Read Succeeded

################
### MONITORS ###
################

monitor=DP-3,5120x1440@120,0x0,1

###################
### MY PROGRAMS ###
###################

# Set programs that you use
$terminal = kitty
$fileManager = thunar
$browser = firefox
$messenger = element-desktop
$menu = wofi --show drun
$cloud = nextcloud
$lock = loginctl lock-session
$statusbar = waybar -c ~/.config/waybar/waybar.conf

#################
### AUTOSTART ###
#################

exec-once = $terminal
exec-once = $statusbar & mako
exec-once = hypridle
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = sleep 10; kwalletd6 &
exec-once = $messenger
exec-once = whatsapp-for-linux

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,12
env = HYPRCURSOR_SIZE,12
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# NVIDIA specific configuration
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

env = NVD_BACKEND,direct

cursor {
    no_hardware_cursors = true
}

#####################
### LOOK AND FEEL ###
#####################

# https://wiki.hyprland.org/Configuring/Variables/#general
general { 
    gaps_in = 5
    gaps_out = 20

    border_size = 2

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false 

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = master
}

decoration {
    rounding = 10

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 1.0

    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 3
        passes = 1
        
        vibrancy = 0.1696
    }
}

animations {
    enabled = true

    # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}


master {
    orientation = center
    mfact = 0.5
    new_status = slave
    orientation = center
    always_center_master = true
}

misc { 
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}


#############
### INPUT ###
#############

input {
    kb_layout = de
    kb_variant = 
    kb_model = 
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

gestures {
    workspace_swipe = false
}


####################
### KEYBINDINGSS ###
####################

$mainMod = SUPER # Sets "Windows" key as main modifier

bind = $mainMod, T, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, B, exec, $browser
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle
bind = $mainMod, L, exec, $lock
bind = $mainMod, X, layoutmsg, swapwithmaster # master

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Volume and Media Control
bind = , XF86AudioRaiseVolume, exec, pamixer -i 5 
bind = , XF86AudioLowerVolume, exec, pamixer -d 5 
bind = , XF86AudioMicMute, exec, pamixer --default-source -m
bind = , XF86AudioMute, exec, pamixer -t
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioPause, exec, playerctl play-pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous

# Screenshots
bind = , Print, exec, grim -g "$(slurp -d)"

##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

windowrulev2 = workspace special:magic silent, class:(Element)
windowrulev2 = workspace special:magic silent, class:(whatsapp-for-linux)

======Config-End========
```

</details>

### Description

After hypridle (or myself manually) fires the `loginctl lock-session` command and 30 seconds later the `hyprctl dispatch dpms off` command my monitor turns off as it should. When I some seconds (or even longer) later move my mouse or press a button on my keyboard, my monitor turns back on as desired, but (mostly) in the top left corner an italic text in my tty's console font appears saying: 
`Running on tty unknown`
The mouse pointer is visable and also movable.

Recovering from this situation is only possible by doing a restart or restarting my display managers service (ly) and running a completely new hyprland session.

I'm not in the expectation to get a easy-to-fix solution here, but some more Ideas whether this might be a hyprland bug, or how I can further debug this situation, as I _didn't found anything_ about this strange error message, of which I don't know where it originates from.

When looking at the last hyprland logs, It did not log anything suspicious.

When searching the sources, the message "Running on tty xyz" originates from `src/render/OpenGL.cpp`.

### How to reproduce

Lock the session and run the dpms off command. Then move the mouse and watch the error appear

### Crash reports, logs, images, videos

![tty_unknown](https://github.com/user-attachments/assets/e9a19cce-152e-4b77-8935-f314724a9585)

_No response_

**Comment by vaxerski** [comment]
arch package is broken. This should show https://github.com/hyprwm/Hyprland/blob/main/assets/install/lockdead.png but arch's package has had broken assets for months now.

**Comment by blauch** [comment]
@vaxerski  I do get your frustration with broken assets. However, as I understand, the issue lies with the lockscreen app itself, not the assets. the broken lockscreen app is annoying. could you still assist here?

**Comment by vaxerski** [comment]
that part is a dupe of many other issues and iirc fixed in git

**Comment by Snazzyham** [comment]
@robtor-de I'm guessing since this is the lockscreen crashing, did you ever find a fix? I was using hyprlock, tried switching to swaylock but still getting this issue.

**Comment by FreshLem0n** [comment]
Hey guys, I could fix this in my setup by assigning a monitor to hyprlock.conf (DP-1 in my case):

`#  _                      _            _
# | |__  _   _ _ __  _ __| | ___   ___| | __
# | '_ \| | | | '_ \| '__| |/ _ \ / __| |/ /
# | | | | |_| | |_) | |  | | (_) | (__|   <
# |_| |_|\__, | .__/|_|  |_|\___/ \___|_|\_\
#        |___/|_|
#

$DISPLAY = DP-1

background {
    monitor = $DISPLAY
    path = $HOME/.config/ml4w/cache/blurred_wallpaper.png   # only png supported for now
}

input-field {
    monitor = $DISPLAY
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.15 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rounding = -1 # -1 default circle, -2 follow input-field rounding
    outer_color = rgb(151515)
    inner_color = rgb(FFFFFF)
    font_color = rgb(10, 10, 10)
    fade_on_empty = true
    fade_timeout = 1000 # Milliseconds before fade_on_empty is triggered.
    placeholder_text = <i>Input Password...</i> # Text rendered in the input box when it's empty.
    hide_input = false
    rounding = -1 # -1 means complete rounding (circle/oval)
    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34) # if authentication failed, changes outer_color and fail message color
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> # can be set to empty
    fail_transition = 300 # transition time in ms between normal outer_color and fail_color
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1 # when both locks are active. -1 means don't change outer color (same for above)
    invert_numlock = false # change color if numlock is off
    swap_font_color = false # see below
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor = $DISPLAY
    #clock
    text = cmd[update:1000] echo "$TIME"
    color = rgba(200, 200, 200, 1.0)
    font_size = 55
    font_family = Fira Semibold
    position = -100, 70
    halign = right
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
}

label {
    monitor = $DISPLAY
    text = $USER
    color = rgba(200, 200, 200, 1.0)
    font_size = 20
    font_family = Fira Semibold
    position = -100, 160
    halign = right
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
}

image {
    monitor = $DISPLAY
    path = $HOME/.config/ml4w/cache/square_wallpaper.png
    size = 280 # lesser side if not 1:1 ratio
    rounding = -1 # negative values mean circle
    border_size = 4
    border_color = rgb(221, 221, 221)
    rotate = 0 # degrees, counter-clockwise
    reload_time = -1 # seconds between reloading, 0 to reload with SIGUSR2
#    reload_cmd =  # command to get new path. if empty, old path will be used. don't run "follow" commands like tail -F
    position = 0, 200
    halign = center
    valign = center
}`

**Comment by skarpinis** [comment]
> Hey guys, I could fix this in my setup by assigning a monitor to hyprlock.conf (DP-1 in my case):
> 
> $DISPLAY = DP-1
> 
> background { monitor = $DISPLAY }
> 
> input-field { monitor = $DISPLAY }
> 
> label { monitor = $DISPLAY }
> 
> label { monitor = $DISPLAY }
> 
> image { monitor = $DISPLAY }

Nah same no change 😕

**Comment by PaideiaDilemma** [comment]
I think this particular issue is fixed. So update (the fix is in aquamarine-git).
If you can't update aq, try to put `monitor=FALLBACK,1920x1080@60,auto,1` in your hl config.

**Comment by skarpinis** [comment]
> I think this particular issue is fixed. So update (the fix is in aquamarine-git).
> If you can't update aq, try to put `monitor=FALLBACK,1920x1080@60,auto,1` in your hl config.

I am on the latest version and will try your suggestion thanks

**Comment by Spuxy** [comment]
what `dmesg` logs ?

**Comment by skarpinis** [comment]
still not fixed and never will be most likely

**Comment by robtor-de** [comment]
I will now try the monitor=FALLBACK method and report if it helped.
