### ISSUE TITLE
map_to_ouput support

### ISSUE THREAD

**Issue by Safenein** [hyprwm/Hyprland#782]
When using multiple touchscreen, Hyprland has a strange behavior:
When your cursor is on a screen, all tactile input are mapped on this screen.

It would be nice to be able to map tactile input to a screen in the config file.

**Comment by vaxerski** [comment]
yeap I am aware, just unsure how to handle that.

**Comment by vaxerski** [comment]
fixed in d7ef19e2e745c2184fcf5c2ce6ac4208d6a81594

**Comment by Safenein** [comment]
Thank you very much. 
You are really fast ! I'll test it soon.

**Comment by Safenein** [comment]
I'm afraid that your commit didn't solve the problem.

I don't really develop in C++ so I'm afraid I can't fix it for you.
If you want more information on my config to see why it doesn't work, you can ask me.

**Comment by vaxerski** [comment]
are you sure? check your version with `hyprctl version`

**Comment by vaxerski** [comment]
odd.

**Comment by vaxerski** [comment]
some touch devices apparently do not have an output that they're bound to, so you'd have to do that manually.

I'll implement an option to do that.

**Comment by vaxerski** [comment]
done in 724fa4a7d44fe594109213b8a6f438e3539aa332

`input:touchdevice:output=str` for global
`touch_output=str` for per-device.

**Comment by Safenein** [comment]
The stylus doesn't work however.

**Comment by vaxerski** [comment]
a stylus is not a touch device. It's a tablet. Use something like OTD for making it work.

**Comment by Safenein** [comment]
Thank you for all, I won't bother you anymore.
