### ISSUE TITLE
[Glitches] Hyprland doesn't play well with Telegram Desktop (or QT?)

### ISSUE THREAD

**Issue by ghost** [hyprwm/Hyprland#839]
I've checked if this is Telegram Desktop's fault or if this happens only with Hyprland/Wayland sessions. But seems like it's not happening on Sway.

I thought it was an animation bug, but by disabling them it looks like that the bugs becomes even more persisting. At the moment, the only way to get back to the normal window state is by changing workspace or switching to full-screen. Looks like this is a bug present even on [qterminal](https://github.com/lxqt/qterminal), so it may be an issue that affects some QT programs.

## How to reproduce
Reproducing differentiates between applications, but in the case of Telegram:
* Open the application
* Open a photo/video via the Media Viewer
* Try over and over until it glitches out
With `animations:enabled=0`, instead, the glitch appears every time the Media Viewer pops-up.

### Screenshot
![](https://user-images.githubusercontent.com/93444783/195391485-5b51da91-e249-4e16-ae26-813bf37931b5.png)

### Logs
[`log.txt`](https://github.com/hyprwm/Hyprland/files/9766976/log.txt)

**Comment by vaxerski** [comment]
dunno, I've heard telegram does this but have never experienced this on any of the apps I use

**Comment by freundTech** [comment]
I can reproduce this issue and maybe give a bit more information:

When you open media in Telegram it doesn't just display it in the existing window. Instead it opens it in a new fullscreen window with semi-transparent background (Hyperland doesn't render the windows behind this semi-transparent fullscreen window, but that's another topic).
After closing the media viewer Telegram becomes stretched.

What seems to be happening is that the fullscreen windows still take up space in the dwindle tree (which usually makes sense, because it returns there when un-fullscreened), taking space from the Telegram main window.
When closing the media viewer Telegram expands again to take the size previously occupied by the media viewer. However something seems to not get notified correctly about that. Telegram keeps rendering at the size it had while the media viewer was open and is stretched to fill the full size.

In my case both resizing the Telegram window manually and even just switching focus to another window make Telegram update its size and render correctly again. Clicking and scrolling inside telegram don't make it update it's size.

socket2 logs the following when opening and closing the media viewer:
```
activewindow>>org.telegram.desktop,Telegram
activewindow>>org.telegram.desktop,Media viewer
fullscreen>>1
openwindow>>8a532cd0,1,org.telegram.desktop,Media viewer
closewindow>>8a532cd0
fullscreen>>0
activewindow>>org.telegram.desktop,Telegram
```

**Comment by freundTech** [comment]
Here's a workaround: Add the following to your hyperland.conf
```
windowrulev2=float,class:^(org.telegram.desktop|telegramdesktop)$,title:^(Media viewer)$
```

This makes the media viewer window start as floating and therefor not take space in the dwindle tree. It still goes fullscreen.
After closing telegram won't be stretched, because its window size never changed in the first place.

(There are two window classes in the rule, as telegram installed from flatpak has a different window class as telegram installed from for example AUR)

**Comment by freundTech** [comment]
I would prefer to keep this open, because there is still something wrong.
Somehow telegram doesn't get notified of its size change or gets notified in the wrong order or doesn't notice the notification or something.

The workaround just prevents that case from occurring, but it's still broken. In the end it's @vaxerski's decision whether to close this or keep it open though.

**Comment by vaxerski** [comment]
tell me how to reproduce this with any other qt app then.

**Comment by labi-le** [comment]
> tell me how to reproduce this with any other qt app then.

open image\video viewer in telegram

**Comment by vaxerski** [comment]
Managed to repro.

**Comment by vaxerski** [comment]
fixed in 10303259f7c6f3e64e74e9ca8a31d4223071d5f0

**Comment by freundTech** [comment]
I haven't tested the fix yet, as I'm not currently running the -git version.

The emoji picker problem also happens on other tiling DEs (tested on bspwm (X11)). What's happening there is that when you open the emoji picker telegram tries to change it's window size to keep the current content the same and add the emoji picker as additional space to the side.  
When you close it it tries to change the window size again to remove the space previously taken up by the emoji picker.

The problem when using a tiling window manager is that telegram obviously can't modify it's own window size. It however assumes that the change was successful and renders at the new resolution until it gets notified about its real size. A possible workaround might be to notify a window about it's current size every time it requests a size change, though I haven't tested that.

**Comment by q234rty** [comment]
I can confirm that this still happens in both telegram desktop and nheko, thought I'm not sure how to consistently reproduce it.

**Comment by felixsanz** [comment]
@vaxerski  can you reopen the issue? is not fixed yet. i posted my comment on #1462 but this is the issue most related

**Comment by kRHYME7** [comment]
Usually I fixed this by just toggling float. Or as long as I toggle the window. 

Most of the time happens on electron apps, e.g. discord clients, brave, etc

**Comment by DeNice-r** [comment]
I also have an issue with telegram. It is always semi-transparent, like other windows do when not in focus, but when it is not in focus, the transparency effect doubles. Not sure if it is related, yet the issue title is broad enough to include this, imo.

**Comment by izmyname** [comment]
Still a thing? Never had any issues with telegram myself.

**Comment by vaxerski** [comment]
worth testing on 0.44.0 with the resize fixes

**Comment by izmyname** [comment]
Well, I tried to reproduce and nothing buggy happened.

**Comment by vaxerski** [comment]
closing then

**Comment by kRHYME7** [comment]
I can confirm too.
