### ISSUE TITLE
NixOS hyprland fails to start

### ISSUE THREAD

**Issue by TotalTaxAmount** [hyprwm/Hyprland#9449]
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

Probably not a regression / I don't remember it happening before

### System Info and Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland 0.47.0 built from branch  at commit f261fb6fe028a1427cfd672eee6e7d5705cd696f  ().
Date: 2025-02-09
Tag: v0.47.0, commits: 5805
built against:
 aquamarine 0.7.2
 hyprlang 0.6.0
 hyprutils 0.5.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.1


no flags were set


System Information:
System name: Linux
Node name: laptop
Release: 6.13.2-cachyos
Version: #1-NixOS SMP PREEMPT_DYNAMIC Sat Feb  8 09:02:27 UTC 2025


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD106M [GeForce RTX 4070 Max-Q / Mobile] [10de:2860] (rev a1) (prog-if 00 [VGA controller])
65:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix3 [1002:1900] (rev cb) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  570.86.16  Fri Jan 24 21:25:51 UTC 2025


os-release: ANSI_COLOR="0;38;2;126;186;228"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="25.05.20250208.fa35a3c"
CPE_NAME="cpe:/o:nixos:nixos:25.05"
DEFAULT_HOSTNAME=nixos
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
ID_LIKE=""
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 25.05 (Warbler)"
SUPPORT_URL="https://nixos.org/community.html"
VARIANT=""
VARIANT_ID=""
VENDOR_NAME=NixOS
VENDOR_URL="https://nixos.org/"
VERSION="25.05 (Warbler)"
VERSION_CODENAME=warbler
VERSION_ID="25.05"


plugins:
	unknown: not runtime


```

</details>

### Description

When trying to start Hyprland (not after update or anything) it now refuses to start, just hanging the login screen or tty. The only thing that I did was plug in a external monitor into HDMI, it was behaving weirdly  but after I unplugged it the internal display on my laptop doesn't work with Hyprland. I tried reverting to a previous config via my nix config but even reverting to something I know worked in the past did not fix the issue.

### How to reproduce

1. Plug in external monitor to HDMI?
2. Start Hyprland
3. Unplug and restart Hyprland

### Attach not paste

- [x] I understand that all text files must be *attached*, and not pasted directly. If not respected, this issue will likely get closed as spam

### Checklist of files to include below

- [x] Hyprland config - `hyprctl systeminfo -c` (always include)
- [ ] Crash report (always include in case of crash)
- [ ] Video (always include in case of a visual bug)
- [x] Logs (might contain useful info such as errors)

### Additional info & File uploads

Logfile: https://paste.c-net.org/ClaricePrevail
Config (generated via nix): https://paste.c-net.org/WandaScrewed

**Comment by nnyyxxxx** [comment]
try building from latest commit

**Comment by TotalTaxAmount** [comment]
Same issue on 6d25ef0 logfile looks the same at first glance. What about this stuff?
```
[ERR] renderer: couldn't beginRender()!
[ERR] Failed to acquire swapchain buffer for eDP-1
```

**Comment by TotalTaxAmount** [comment]
Appears the issue is Hyprland was trying to start on my laptops dedicated GPU, using `AQ_DRM_DEVICES` to tell it to run on the iGPU fixes the issue. However,  `card0` and `card1` seem to switch between boots (card0 is amdgpu, next boot card0 is the nvidia gpu), is there a way to tell Hyprland to always use the iGPU other than `AQ_DRM_DEVICES`

**Comment by ikalco** [comment]
@TotalTaxAmount try aquamarine-git

cause [this commit](https://github.com/hyprwm/aquamarine/commit/a3dda0d10ce9aa1d1dfb7a6c139ea8c2872c74bd) prob fixes choosing the igpu

**Comment by GameDungeon** [comment]
I think my (Nixos) desktop is currently loading off integrated graphics instead of my actual GPU. How can I use aquamarine-git if I am using hyprland from the flake? I should already be using that correct?

**Comment by mattkang** [comment]
> Appears the issue is Hyprland was trying to start on my laptops dedicated GPU, using `AQ_DRM_DEVICES` to tell it to run on the iGPU fixes the issue. However, `card0` and `card1` seem to switch between boots (card0 is amdgpu, next boot card0 is the nvidia gpu), is there a way to tell Hyprland to always use the iGPU other than `AQ_DRM_DEVICES`

Instead of using `card0` and `card1`, you can create symlinks for
```
/dev/dri/by-path/pci-0000:XX:XX.X-card
```

**Comment by ikalco** [comment]
@TotalTaxAmount 
did your issue get fixed with aquamarine-git or the above fixes? if so you can close this issue

**Comment by TotalTaxAmount** [comment]
Sorry, I will check tonight

**Comment by TotalTaxAmount** [comment]
No, latest Hyprland git and latest aquamarine git did not fix the issue, though it did seem to fail later in the startup(?) before it would just freeze gdm when I attempted to log in, now the screen first turns black then it freezes. Here is the log:
http://paste.c-net.org/DovesMeasure

**Comment by drkwolf** [comment]
Any news about this bug, i'm also affected

**Comment by vaxerski** [comment]
Hello there!

This issue has been closed, as we are moving from issues to discussions. More about this can be found [here](https://wiki.hyprland.org/Contributing-and-Debugging/Issue-Guidelines/) and in #9854.

Firstly, please make sure this issue is still relevant in latest Hyprland. If so, we ask you to open a [discussion](https://github.com/hyprwm/Hyprland/discussions) (please read the discussion guidelines first, in the pinned post)

Thank you for your understanding!
