### ISSUE TITLE
File drag and drop will hang mouse clicks

### ISSUE THREAD

**Issue by atzlt** [hyprwm/Hyprland#9472]
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

Probably not a regression / I don't remember it happening before

### System Info and Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland 0.47.2 built from branch  at commit 882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff  (version: bump to 0.47.2).
Date: Sun Feb 2 00:47:17 2025
Tag: v0.47.2, commits: 5767
built against:
 aquamarine 0.7.2
 hyprlang 0.6.0
 hyprutils 0.5.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.2


no flags were set


System Information:
System name: Linux
Node name: ZIZIonArch
Release: 6.13.3-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Mon, 17 Feb 2025 17:42:11 +0000


GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Meteor Lake-P [Intel Arc Graphics] [8086:7d55] (rev 08) (prog-if 00 [VGA controller])
	DeviceName: VGA


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

Drag & drop files into some Xwayland appllication causes hyprland to not handle mouse clicks

### How to reproduce

Steps to reproduce:

Drag a file from Nautilus / Dolphin to an app like QQ or WeChat (both are running under Xwayland and due to some search results I believe the bug is present on any Xwayland application, but I do not have any at hand). The file drop would not be successful, and until I kill the process of Nautilus / Dolphin, Hyprland cannot recieve and mouse clicks.

### Attach not paste

- [x] I understand that all text files must be *attached*, and not pasted directly. If not respected, this issue will likely get closed as spam

### Checklist of files to include below

- [x] Hyprland config - `hyprctl systeminfo -c` (always include)
- [ ] Crash report (always include in case of crash)
- [ ] Video (always include in case of a visual bug)
- [ ] Logs (might contain useful info such as errors)

### Additional info & File uploads

<details><summary>`hyprctl systeminfo -c`</summary>

```
Hyprland 0.47.2 built from branch  at commit 882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff  (version: bump to 0.47.2).
Date: Sun Feb 2 00:47:17 2025
Tag: v0.47.2, commits: 5767
built against:
 aquamarine 0.7.2
 hyprlang 0.6.0
 hyprutils 0.5.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.2


no flags were set


System Information:
System name: Linux
Node name: ZIZIonArch
Release: 6.13.3-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Mon, 17 Feb 2025 17:42:11 +0000


GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Meteor Lake-P [Intel Arc Graphics] [8086:7d55] (rev 08) (prog-if 00 [VGA controller])
	DeviceName: VGA


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/atzlt/.config/hypr/hyprland.conf: Read Succeeded
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
monitor = , 2880x1800@120, auto, 2

xwayland {
    force_zero_scaling = true
}

env = XCURSOR_SIZE,24
env = GDK_SCALE, 2

env = HYPRCURSOR_SIZE,24
env = HYPRCURSOR_THEME,rose-pine-hyprcursor

$terminal = kitty
$fileMan = nautilus
$runner = tofi-drun
$browser = firefox

input {
    touchpad {
        natural_scroll = true
        scroll_factor = 0.2
        disable_while_typing = false
    }
}

general {
    gaps_out = 10
    gaps_in = 3
    col.inactive_border = rgba(00000000)
    layout = dwindle
}

decoration {
    rounding = 5
    rounding_power = 4
    inactive_opacity = 0.9
}

animations {
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windowsMove, 1, 3, myBezier
    animation = windowsIn, 1, 2, default, popin 90%
    animation = windowsOut, 1, 1, default, popin 95%
    animation = border, 1, 2, default
    animation = fade, 1, 2, default
    animation = workspaces, 1, 3, default
}

misc {
    vfr = true
}

workspace = r[1-3], monitor:0

# Layer Rules
layerrule = blur, waybar
layerrule = ignorezero, waybar
layerrule = blur, notifications
layerrule = ignorezero, notifications
layerrule = blur, launcher
layerrule = ignorezero, launcher

# Window Rules
# pinned window style
windowrulev2 = bordercolor rgb(598da8) rgb(598da8), pinned:1
# windowrulev2 = float,class:(.*)
windowrulev2 = float,class:(QQ) # QQ Popups
windowrulev2 = float,class:(wechat) # QQ Popups
windowrulev2 = float,title:(Volume Control) # Volume Control
windowrulev2 = float,title:(Fcitx Configuration) # Fcitx Config
windowrulev2 = float,class:(clash-verge)

# Window Rules

$mainMod = SUPER
bind = $mainMod, Q, exec, $terminal
bind = $mainMod SHIFT, Q, exec, warp
bind = $mainMod, M, exit
bind = $mainMod, E, exec, $fileMan
bind = $mainMod, R, exec, $runner | xargs hyprctl dispatch exec --
bind = $mainMod, T, togglefloating,
bind = $mainMod CONTROL, DELETE, killactive,
bind = $mainMod, Tab, cyclenext,
bind = $mainMod, O, fullscreen, 1
bind = $mainMod, X, pin,
bind = $mainMod, Z, swapnext,
bind = $mainMod, G, togglegroup
bind = $mainMod, S, togglesplit
bind = $mainMod, F, exec, $browser
bind = $mainMod CONTROL, V, exec, cliphist list | dmenu -b -fn "BlexMonoNerdFont-23" -l 10 | cliphist decode | wl-copy
bind = $mainMod, L, exec, pidof hyprlock || hyprlock
bind = $mainMod, C, togglespecialworkspace, minimized
bind = $mainMod CONTROL, C, movetoworkspace, special:minimized
bind = $mainMod CONTROL, C, setfloating

bind = $mainMod_CONTROL, L, resizeactive, 50 0
bind = $mainMod_CONTROL, H, resizeactive, -50 0
bind = $mainMod_CONTROL, J, resizeactive, 0 50
bind = $mainMod_CONTROL, K, resizeactive, 0 -50

bind = , XF86MonBrightnessUp, exec, brightnessctl s +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl s 5%-
bind = , XF86AudioRaiseVolume, exec, pamixer -i 5 
bind = , XF86AudioLowerVolume, exec, pamixer -d 5 
bind = , XF86AudioMicMute, exec, pamixer --default-source -m
bind = , XF86AudioMute, exec, pamixer -t

bind = $mainMod SHIFT, S, exec, grim -g "$(slurp)" - | wl-copy
bind = $mainMod SHIFT CONTROL, S, exec, wf-recorder -g "$(slurp)" -f "/home/atzlt/Videos/ScreenRecords/recording-$(date +%y%m%d%H%M%S).mp4"
bind = $mainMod, escape , exec, kill "$(pidof wf-recorder)"
bind = $mainMod SHIFT, W, exec, grim -g "$(hyprctl -j activewindow | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')" - | wl-copy
bind = ,print , exec, grim - | wl-copy

bind = $mainMod CONTROL, 1, movetoworkspace, 1
bind = $mainMod CONTROL, 2, movetoworkspace, 2
bind = $mainMod CONTROL, 3, movetoworkspace, 3
bind = $mainMod CONTROL, 4, movetoworkspace, 4
bind = $mainMod CONTROL, 5, movetoworkspace, 5
bind = $mainMod CONTROL, 6, movetoworkspace, 6
bind = $mainMod CONTROL, 7, movetoworkspace, 7
bind = $mainMod CONTROL, 8, movetoworkspace, 8
bind = $mainMod CONTROL, 9, movetoworkspace, 9 
bind = $mainMod CONTROL, 0, movetoworkspace, 10

bind = $mainMod CONTROL SHIFT, 1, movetoworkspacesilent, 1
bind = $mainMod CONTROL SHIFT, 2, movetoworkspacesilent, 2
bind = $mainMod CONTROL SHIFT, 3, movetoworkspacesilent, 3
bind = $mainMod CONTROL SHIFT, 4, movetoworkspacesilent, 4
bind = $mainMod CONTROL SHIFT, 5, movetoworkspacesilent, 5
bind = $mainMod CONTROL SHIFT, 6, movetoworkspacesilent, 6
bind = $mainMod CONTROL SHIFT, 7, movetoworkspacesilent, 7
bind = $mainMod CONTROL SHIFT, 8, movetoworkspacesilent, 8
bind = $mainMod CONTROL SHIFT, 9, movetoworkspacesilent, 9 
bind = $mainMod CONTROL SHIFT, 0, movetoworkspacesilent, 10

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9 
bind = $mainMod, 0, workspace, 10

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod CONTROL, left, movewindow, l
bind = $mainMod CONTROL, right, movewindow, r
bind = $mainMod CONTROL, up, movewindow, u
bind = $mainMod CONTROL, down, movewindow, d

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bindl = , switch:on:Lid Switch, exec, pidof hyprlock || hyprlock, hyprctl dispatch dpms off
bindl = , switch:off:Lid Switch, exec, hyprctl dispatch dpms on

plugin {
    hyprwinwrap {
        class = classwallpaper
    }
}

exec-once = hyprpaper
exec-once = pulseaudio
exec-once = gsettings set org.gnome.desktop.interface cursor-theme BreezeX-RosePine-Linux
exec-once = gsettings set org.gnome.desktop.interface cursor-size 24
exec-once = wl-paste --watch cliphist store
exec-once = wl-clip-persist --clipboard regular
exec-once = waybar
exec-once = libinput-gestures-setup start
exec-once = hypridle
exec-once = mako
exec-once = gsettings set com.github.stunkymonkey.nautilus-open-any-terminal terminal kitty

exec-once = clash-verge

# Why doesn't it work?
# exec-once = ~/Projects/wallpaper/bin/python ~/Projects/wallpaper/classwallpaper

======Config-End========

```

</details>

**Comment by nnyyxxxx** [comment]
yes fixed with #9405

**Comment by atzlt** [comment]
This bug is still present in the current version of `hyprland-git` (commit `d7e7a292613a4f20218074ff8299dff099a80098`) when I drag some file into Microsoft Edge (`microsoft-edge-bin`). I believe this is a regression as the problem doesn't appear in an earlier version (the version the mentioned PR is just merged).

**Comment by nnyyxxxx** [comment]
send a video

**Comment by BeshoyEhab** [comment]
This error happen to me when I drag any file from Nautilus to Brave 
as you can see in this Video my cursor still with Gnome cursor theme will my cursor (bibata Modern Classic) is appear only if I move the cursor to empty workspace + I clicked a lot in video without any response but it seems it's not appears right in the video 

> Sorry for my English 😅

https://github.com/user-attachments/assets/c4224dc4-b394-479a-9c6b-1131f52b5bc4

**Comment by nnyyxxxx** [comment]
attach hyprctl systeminfo

**Comment by BeshoyEhab** [comment]
@nnyyxxxx I added the hyprctl systeminfo in the previous comment

**Comment by nnyyxxxx** [comment]
brudda its already fixed in -git, update to 0.48.0

**Comment by nnyyxxxx** [comment]
your systeminfo says you're on 0.47.2
