### ISSUE TITLE
MPV and games flickering/switching from fullscreen to windowed at random

### ISSUE THREAD

**Issue by AmirDahan** [hyprwm/Hyprland#965]
Steps to reproduce:
1: Install the latest hyprland-git/hyprland-nvidia-git package from aur
2: Launch MPV
3: Fullscreen it
4: Freezes then flickers

Or

1: Launch a game (for instance TF2)
2: Fullscreen it
3: Move your cursor away from the game's monitor

Random flickering happens on spotify
Assumption?
It might be trying to switch from windowed to fullscreen really quickly as it sometimes ends up on windowed mode and vice versa

Expected outcome:
MPV: Fullscreen MPV playback
TF2: game should stay fullscreened
Spotify: no random flicker or occasional window/fullscreen switch

Noted outcome:
Other windows can do the same but these are just examples

**Comment by brodi1** [comment]
same here with an Intel iGPU
it happend right after i updated from c47581f to 976b444

**Comment by vaxerski** [comment]
`misc:no_direct_scanout = yes`

**Comment by vaxerski** [comment]
fullscreen issues are down to how the apps request themselves to be fullscreen'd

**Comment by brodi1** [comment]
@vaxerski thanks!

**Comment by vaxerski** [comment]
fixed the mpv + direct scanout issue in 082f439db2ccb58f2792a4885a0aa09ae666a6b0

**Comment by vaxerski** [comment]
what are the other issues?

No games I tested exhibit random de-fullscreens
Spotify is broken as usual

**Comment by AmirDahan** [comment]
Team fortress 2 still experiences these issues mpv seems to be fixed

**Comment by vaxerski** [comment]
_what's the issue_ your explanation sucks. What do you do, what happens?

**Comment by AmirDahan** [comment]
What i do: launch tf2
Move my cursor to my second monitor
Tf2 goes windowed
I switch my cursor back to the monitor that has tf2 open and it goes back to fullscreen

**Comment by vaxerski** [comment]
is it running through proton?

**Comment by AmirDahan** [comment]
It is not
It's native

**Comment by vaxerski** [comment]
sounds very much like the DXVK issue described before. I am inclined to say it is. At any rate, that seems like tf2 itself requesting that. Unless this is a regression, I am not planning on investigating that. (seen your vid on the discord server, seems very much like tf2 requesting to be minimized)

**Comment by AmirDahan** [comment]
That could very well be the case
i will give a few games a try see if this happens there too
i also want to believe that it's a tf2 thing

**Comment by AmirDahan** [comment]
Yup it's a tf2 specific issue
launching the game in fullscreen mode from the game itself causes it to do that
launching it in windowed mode and fullscreening it from hyprland works just fine
other games do not experience this issue :+1:
